= Angular
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===


== The Complete Communication Skills Master Class for Life

=== Section 1: You Can Be a Communication Skills Master

==== Quick Wins! The High Tech Way to Perfect Communication

Let's hop right in with a quick win, there is a simple high tech solution that will dramatically boost your communication skills. It's right in front of us, and yet most of us never use it. *Here's the tool. It's a cell phone*. But wait a minute. Here's the trick. If you have to communicate to a prospective boss about a job or a raise or you're trying to raise money from investors or you want to ask people for their vote for public office, here's the key practice. What it is you want to communicate on video, look at it, figure out what you like. Don't like once you've got a version on video that you like. Here's the thing that you're not going to have done before. I promise you email that video to a friend or colleague, ideally someone whose mindset is similar to the person you're trying to communicate with and then ask your friend, call them, text them, ask your friend and say not, what do you think? But what do you remember? What messages do you remember if they remember the messages that were important to you? Now you can relax. You know, you are communicating, but if they're not getting it, it's not their fault. It's your full time to practice again. Come up with new messages, a new style for communicating this one. Technology will really dramatically help you. Most people aren't doing it, but now you can.

==== Listening is Key (and why this isn't just a public speaking course)

You can be a great public speaker, a fine orator, you can have tremendous charisma and guess what, still be a lousy communicator. *Your communication skills can be poor because of one thing. You're not listening*, this is a communication skills class, of course, I'll cover a lot of fundamentals and advanced steps for public speaking and PowerPoint presentation skills, but so much of being a great communicator goes deeper than that and so many communication opportunities in life. It's about listening. *The best communicators in the world are often the best listeners*, people who are really great at making the one on one sale, the best sales pitch, sometimes the best politicians who get the votes. It's because they are the best at listening. Now, later on in this course, there's an entire section on listening skills to really help you build the listening skills. But it's something I want you to think about right now. It really applies to every single type of communication, whether you're asking for a job, a raise, a budget to be approved. You need to listen to what other people say. *I've been in countless pitch meetings with a client where PR firms were pitching them for their business and the ones that lost talk the most. They had the most slides up. They stood up and gave the most formal presentations. The PR firms that won, they ask questions. They sat back and they listened. And then they reacted quite often with another question. So this applies to personal communications with friends and families, colleagues, bosses, rather than just pushing out all your preordained ideas, you can't really listen*. And great communication isn't something you just created. Working until midnight on a PowerPoint three weeks ago. You're there present with the person or with the group you're communicating with. You're constantly listening, recalibrating and adjusting. And believe it or not, this even applies to public speakers. The best speakers in the world. Pause. They're looking for responses from their audience. Sometimes it's just a nod. It might be a look of confusion. That's a type of listening if you are the speaker. So we're going to be covering more on listening in this course. *Just realize so much of communication has nothing to do with your lips moving or even your eye contact. It's about really hearing the messages coming out from other people so we can respond to it, let them know we've heard them react to it and deal with their concerns, ideally before we deal with our own concerns*.

==== Become part of the top 1% of communicators right now!

*A very famous movie star and director once said 90 percent of success is just showing up*. I want to apply that to communication now. All of us communicate all the time with friends, family, but so many of us just stop communicating when we get outside of our comfort zone. We're afraid to raise our hand, sometimes in a classroom, sometimes if it's a boardroom. And they're intimidating people around who are afraid to call that talk radio show, we're afraid to post our comments on a newspaper comment section. We're just afraid to communicate our ideas. So I want to put something here right in front of this course for you to chew on and really think about beyond all the skills of framing messages the right way. Good. I can't. And we'll get into all those style and mechanics. *So much of being a good communicator is just having the willingness to speak out, even if you're not quite comfortable*. So I can give you a tip right now. You can automatically zoom up to the top one percent of communicators for this class just by doing one thing. I want you to communicate with me right now. Go to the Q&A section of this course and you'll see it right at the top in the middle of the page. Once you click the dashboard and I want you to communicate, you can do it in a text format and write and tell me what you want to get out of this. Course you can post a video. You are RL, put it on YouTube, post it here, telling us a little bit about who you are, what you want to get out of this court. You can make an audio recording and upload it to a site and put the audio there. You get to choose do what's comfortable for you. But most of you, sad to say, are not going to communicate at all. You're going to sit back passively click. Let's go to the next one. Let's get through this course. Let's see if we can get to the bottom and get our certificate. That's not really learning and it's not communication. So I'm asking you politely, please communicate with me right now. Let me know specifically what you want to do to get the most out of this course. And even though this course is jam packed, there's five hundred and fifty lectures in this course. I can still delete one to add something new if more of you want that. So communication has to be a two way street and too many instances in life, whether it's in school, whether it's in a big corporation, a big government, we're used to just sort of sitting back passively receiving and we buy into this idea that we don't have the right or the credibility or the standing to communicate back. Well, that's just not true, especially in the modern world of technology, Internet, social media. It's never been easier to communicate in any format we want. So please take a moment, communicate something with me. Even if you want to say, D.J., you're born, we get on with it. That's OK. Post your communication now.

==== Good news, the problems we think we have, aren't real

I've got some good news for all of you, but first, let's step back for a moment. We all know that sometimes there's perception, sometimes there's reality. They might be exactly aligned, but they may be skewed. So, for example, my perception is that I will never become a star professional basketball player for the NBA, the National Basketball Association. My perception of that, it's because I'm too slow, I'm too old. I don't shoot well enough. And I'm that shy of six feet tall. I'm not tall enough. That is my perception of why I'm never going to be a star in the NBA. Well, it turns out that my perception of my flaws are exactly aligned with the reality. Those are real flaws. Those will keep me from ever becoming an NBA star. Now, enough of you. By this course, I become a billionaire. Maybe I can buy a team, but that's different. I will never star as a basketball player because I don't have the talent, the physical talents at all to do what it takes so many times in life. Our perception of our weaknesses are actually correct. I'm here to tell you, when it comes to being a great communicator, it's not correct. I have worked with tens of thousands of people all over the globe in person real life for more than 30 years. So I hear time and time again people telling me, oh, T.J., I'm not a good communicator. I can't give good speeches or presentations for the following reasons.

*I say too many arms. I say too many of those years. I'm not good looking enough. My accent is to Southern or to New York or it's to Indian or it's too different from what people are used to. People have this sense of all these problems that are holding them back. People have told me, I know I'll never be a good communicator because I have Bell's palsy in my face droops. Meanwhile, no one else in the room even noticed it. So in my experience as individuals, we come up with all sorts of reasons as to why we'll never be a great communicator*. Oh, I don't like my voice. My voice is no good. Here's what I found. Working with training and studying with the top communicators, public speakers, presenters, communicators, TV hosts in the world. Not that matters the things that make us great communicators. It's not just we didn't say some of the most successful, highly paid TV stars in the world say constantly. It's not necessarily about your looks. *Some of the most successful TV talk show host and reality star host have less hair than I do and are 30 years older than I am*. So it's not about being young and good looking. So I'm here to tell you, relax the things you think are making you a bad communicator really aren't. Those are not your problem. I'm not suggesting you don't have some challenges to overcome, but it's a different set of problems because trying to change your accent is really, really hard and can take hundreds of hours, sometimes thousands of hours. Do you have an extra thousand hours changing? The tone of your voice is extraordinarily difficult. I'm here to tell you, you don't have to do that. I've seen masterful communicators who have high voices, low voices, screechy voices, accents that are not considered desirable or attractive. And these people are still great communicators. So I want you before we really dive in deeply in this course. *It just kind of set aside these preconceived notions you have about what's holding you back*. People think, oh, I move my hands too much. I'm here to tell you I worked with, again, more than ten thousand people around the world face to face for thirty years. I've never yet had an audience say about someone I'm training. Oh, their hands are moving too much. Never once happened. I do hear people say, oh gosh, that person seems frozen and stiff and scared and nervous that I hear all the time. So we're going to work on a number of issues to make you a better and better communicator. Right now, I just want you to relax if you've ever had. One interesting conversation with one friend, one family member, one colleague about one subject, and you felt good about it and the person you were speaking with felt good about it. Guess what? You already have all the skills you need to be a great communicator. We'll try to build those out, build your comfort level so you can do them in different situations. But you don't have to learn a whole new accent or lowers your voice perpetually.