= Getting Things Done
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Getting Things Done

*Maximizing Value*

* [ ] *Fundamentals*: Learn the concepts
* [ ] *Information*: Do POC from the course
* [ ] *Skills*: Use / Implement it in Project
* [ ] *Innovation / Expert*: Value for next 2 Years


*Objective*

* [ ] *History*:
* [ ] *Agenda-While doing this course what is the Agenda [1,2,3,4,5..]*:
* [ ] Exam Notes
* [ ] *Why OneNote Notes*:
* [ ] *What is Pending*:

=== Section 1: Introduction

*The Productivity Problem*

Hello and welcome. My name is Derrick Franklin and I am the creator of the action maps system. And let me just start out by saying that I know exactly why you're here and that's because your life is very busy. You have all these things you need to manage. You need to track, you need to remember and think about. And your current way of dealing with all these things just really isn't working. So instead of moving forward, what happens when you start feeling like you're getting behind and that stresses you out and you're feeling overwhelmed and then frustration sets in and it's just a horrible, horrible feeling. And so the question comes up, well, how do you fix it? Well, the way that you fix it is very simple, and that is that you identify the source of the problem and then you tap into a solution that eliminates that problem. It's very, very simple. So what's the problem? Well, the way that you manage your life lacks order and structure. That's it. I know that's kind of blunt, but that's it. So really, that breaks down to the fact that you you have no process or system or a very inefficient process or system to plug everything that life throws at you into. And so what happens as a result? Well, instead of feeling like you're moving ahead and getting things done, like you want to, like we all want to, you don't. And so that leads to stress and that overwhelm and that frustration like everything is just piling up on you. Right. *Let's talk about just a second why a system is so very, very important*. I like to tell people the reason why systems are so great and this applies to systems, all types of systems, including the action map system. But any system, the reason why they work so well and why they're so very important is all you have to do is look at our universe. And when you look at the universe, you can see that it is totally built around the concepts of order and structure, and you can see it in everything from there, the way the planets rotate around the sun and the moon rotates around the Earth to the laws of math and physics. You have these laws, this order and the structure, and it's really what makes everything just work properly and efficiently. If you didn't have this, what would what would happen if you didn't have laws and order in these things, then you would. Essentially, the opposite is chaos. If you didn't know how things were going to work or if laws weren't in place so that gravity worked the way it did electricity work, the way it did math work the way it did, you wouldn't have computers. We'd be floating around in the air if we'd even exist. So these laws and order are essential for the universe to work the way that it does. And when you think about it, we're just part of that universe, aren't we? I mean, we're smack dab in the middle of it. And so if we work the way that the universe works. Then we win, and if we don't work the way that the universe works, well, then we lose. And life becomes this unnecessary struggle, and so when you consider this and you think about a system, well, a system, essentially all it does is it really helps you to manage your little part of the universe. So you're working within the laws and the rules of how the universe works efficiently. And if you manage your little part of the universe, well, well, you get awesome results because you're working within that flow and order and structure of the universe. Once again, without order and structure or very little order and structure, you're fighting against this flow, natural flow of the universe. So hopefully I've convinced you of that fact. Now that we've identified the problem and determined that the solution is a system that brings order and structure to your life. Let me reveal to you what I think the solution looks like. And it's right here. This is the action map system, and what I'd like you to do is at this moment is just take about 10 seconds to look it over, just give a brief overview of the entire map itself. And look at its structure and its simplicity. You take about 10 seconds to do that, then we'll come back and talk about why it is so unique.

==== The Unique Value of The Action Map System

Now, let's talk about the unique value of the action map system, so at the core of most productivity systems, what is it? Some list, right? Everything is about the list. There are some great list managers out there that really help you to manage lists very well. *But there's a problem in the fact that they're deficient and one of the most important aspects of managing something as complex as our lives, at least in my opinion, and that is that they don't show you the big picture in context*. So you can't see everything at once and you can't see how all the pieces fit together. It's just list after list after list after list. So you might be asking yourself, well, what's the big deal? Why is seeing all this stuff important, considering the idea of building a house with nothing but a list of instructions, step by step instructions, no pictures other than a list of step by step instruction building the house that way. How hard and difficult would that be? It's doable, perhaps, but imagine how much easier it is to do something of that scale with a blueprint in your hand so you could see how the end product is going to look like. And so you can see how all the pieces fit together. That's what a blueprint enables you to do, that a list of step by step instructions or just a list doesn't allow you to do. Or consider another example, imagine driving from New York to California and all you had was a list of turn by turn instructions. Turn left at this street, turn right here, go 10 miles, turn left and so on. Once again, that trip is possible. It would be a real frustrating experience, in my opinion, I would think that would be a very frustrating experience. But imagine how much better that would be and how much easier it would be if you had a map of the entire United States in front of you, where you could see all the roads, you could see all the cities, and you could get a feel for where you are at any point, how the distance that you've traveled from one location to another, you could see if you wanted to take a detour, you could find out where that places that you wanted to go and find the road back to your original destination. That is the real power. Those two examples show you the real power of being able to see the big picture and understand context for how pieces fit together and this kind of context and seeing the big picture. The benefit is that it provides clarity and removes fear. So more clarity. The more clear you can get about anything, the better results you're going to have. And so a list is one way of providing some clarity and some structure. *But a map like this really takes it to a whole new level because you see everything at once and you see how all these pieces of your life come together, which is missing a lot of times when you're just using lists and managing lists*. So as the name implies, the action maps system is built on this unique structure and process that delivers all these kinds of benefits of the big picture and context as it relates to managing your life, helping you make decisions and getting things done.

==== How The Action Map System Was Born

Now, let me talk for a moment about *how the action map system was born*. So over the years, I've been interested in the idea of being a productive person. I've read tons of books and gone to seminars and workshops, all to kind of understand how to run my life more efficient. And I've had to be this way, really, because in the past 10 years, I've done a lot of stuff that I've needed to manage and take care of. I've written five books for Adobe Press over the years. I've self published a bunch of other books. I've designed numerous products and projects that I've launched online. I've recorded dozens and dozens of videos for my business. I maintain a blog in one form or another over the past 10 years and created dozens of websites. And in addition to all that, I'm a one man business. And so I handle all the marketing, all the support, all the management and all the things that come with creating and running a business, marketing, design, programming, you name it. I've done it all. And that's just my business life. My personal life is almost equally as busy. Now, I don't want to give you the impression that I'm a workaholic, though, because I'm not my free time and the time that I spend with my friends and family is very, very important to me. I don't believe in 12, 14, 16 hour days. It's just ridiculous. I won't do that. I've had to manage all these things. Now, why am I sharing this with you? To help you to understand that when it comes to getting things done and taking action, I know what I'm talking about. I speak from experience. To get to this point, as I mentioned just a second ago, I tried all kinds of different methods and systems for managing my time. So I went from list making. I've done lists and notebooks to getting things done, which is very popular in a lot of people. Know about it by David Allen getting things done. And I've tried all these different methods and processes. And along the way I really learned a lot of tips and strategies and ideas for being more productive and more efficient. *But I always felt like something was really missing. And the reason why I felt that way is because I'm a visual thinker and so trying to manage my life using these abstract lists and dialog boxes of software and windows and things like that, was something that I was having a hard time wrap my head around*. And so one day I got this crazy idea and I decided to mix my obsession and my love of mind mapping with some of these various strategies that I knew about and had learned about being more productive just to see what I could come up with and see if it would be practical to use. And so after a few years of using it and testing and tweaking, I now have this awesome system that works really well for managing virtually every aspect of my life, which is the *action map system*. And fortunately, I've simplified it enough to the point where I can teach it to anyone and anyone can learn to use it in their own life. And so they can start seeing the benefits of using the system in their own life, which is one of the reasons why I decided to create this course.

==== Short-Term Pain Brings Long-Term Pleasure/Results

==== A System Is Only As Good As Your Dedication To Using It

==== What You Need To Get Started

==== An Overview Of The Action Map System

Now, let me give you an overview of the entire action map system so you have a clear idea of the different elements and where they are and how they kind of come together in a very basic way. We'll be getting into more details later, but just an overview. So we'll start by this idea of the action map being more than a to do list manager. It's a life management system. And when you think about it, there are there are a lot of ways for managing lists of stuff. And we've already talked about this a little bit. And one of the more popular ways of managing lists to do lists especially is to create a master list of everything that you need to do. And then at the end of the day or at the beginning of the morning, whichever, go to that master list, create a list of things that you want to work on for that day or the next day and then go to work on that. And that can be a great system if all you have to do is manage to DOS. But if you're like me and like most everybody else, there are appointments to manage their decisions to make. There are processes that you use in your life. There are reference materials and content that you like to have access to and all these different elements that go beyond to DOS. And the action map helps you to manage all these these things, which is why I say that it helps you to get life done, not just your tattoos, because life involves more than just a list of to DOS. Keep that in mind. It's more than a to do list manager. It's a life management system and has a much broader scope than perhaps anything else that you've worked with up to this point. A place for everything and everything in its place. What does that mean? Well, the actual map system is built around this universally powerful principle of a place for everything and everything in this place. Now, what does that mean? Well, it means that every element of the action map system has a specific purpose. So to use it effectively, you've got to start looking at everything that comes into your life, that demands your time and resources. And then you need to start thinking about where those things fit into the map itself. And this is going to be hard at first, like we talked about earlier, know this is going to require some changes, doing things different than your normal routine. So it might seem hard at first, especially if you're used to just dealing with stuff by the seat of your pants or off the cuff without having no real plan of why you're processing it a certain way. You might just scribble something down or save the file for some reason or put something on your calendar without really having a clear idea of how that's going to all come together to help you to get things done. And you might forget that that scrap of paper is there or you might forget that you put something on your calendar. You've got to change that behavior. When you give no thought to something like that, as maybe you're used to doing, and you don't have any real rhyme and reason and purpose and intention for managing the stuff that comes into your life a certain way, well, what happens? We get chaos, right? *So you've got to adopt a mindset when you're using the action map system, since there is a place for everything and then everything in its place, you've got to adopt this mindset of stop, think and process*. So as something enters into your life that you need to take care of, whether it's an appointment you need to make or project that you're about to start or something's come up that you need to take care of tomorrow, whatever it may be, as opposed to just scribbling it down somewhere in the closest piece of paper or doing something with it and potentially forgetting about it. You have to just stop. Stop and think about what that thing is. And as you think about it as we go through this course, we're going to tell you some rules that apply to help you to think about this, but you need to stop, think about what that thing is, and then you need to process it some way using the action map. And it's a very simple way of doing things. Once you get used to doing it and you get into the habit of doing initially, it's going to be kind of a challenge. But it's very important that you go through this process of stopping thinking and processing the action that's coming into your life so you can manage it properly using the action map system.

So take time to put everything in its place. That's a crucial part of making this system work. Now, let's talk about the main elements of the system and let me go to the action map itself so you can look at this as we're going through this discussion. First of all, #*there's flow*#. That's element number one. Now, what do I mean by flow? Will flow is all the stuff that comes into your life that you need to interact with or deal with in some way. That includes your to dos, your appointments, errands, emails, anything you're wanting to search on Google events that you want to attend, Web pages that you bookmarked, or decisions that you need to make people you need to keep up with, things that you want to remember, just all these things and more. So that's flow. That's the first element of the system.

The second main element of the system are *locations*. And you see locations here on the maps. The locations are areas on the action map that you'll use to either hold action items that result from the flow that's coming into your life or you'll use these locations to point to information that will help you to manage or take action on that flow in some way. So locations include your *calendar*, which you don't see in the map here, but your calendar is the only external element of the action map system. But that's one of the locations that you'll use to manage the flow coming into your life. The second location is this one right here actions, the third triggers and the fourth is domains. And we'll be exploring each of these in more detail later.*Just to recap up to this point, you have flow coming into your life and that flow is managed and you take action on it using your calendar actions, triggers or domains*. One of those four locations. The next element of the system is *rules*. Now, rules are just exactly what they sound like. They're guidelines that you use to process and determine the location, to place the flow items on your map as those items enter your life. For example, let's say that you've been given a task at work that you need to complete or do once a month. Well, there's a rule to help you to make sure that it gets done so you know where to place it on the action map to make sure that that task gets done once a month. There's a rule for that. Or let's look at another example. Let's say you're driving around town or wherever and you find a place that you like to eat some day. How do you keep track of that so that you actually remember that you want to eat there and you you do it one of these days? Well, there's a rule for helping you to remember to do that also. *So as Flo enters your life, you're going to ask what rule handles this item and that helps you determine where to put things on the map*. And I'm going to provide you with a general set of rules. But as you get familiar with the system and you get comfortable with it, you may want to create various rules on your own and you'll see how that works the more familiar with the system you get. So rules help you to process the flow that comes into your life with intention and purpose so you can maintain control and get things done efficiently. Just a real quick recap. *Flow gets put in locations within the action map system based on rules.* That's where we are up to this point. Now, the next element are *reviews*. A review is the process of setting aside time to look over the map in order to maintain its updated and make sure that everything that need your attention is getting it and that your life's moving forward the way that you want it to move forward. And there are two types of reviews that are part of the action map system. *One is a daily review and the other is a weekly review*. And The Daily Review is what you use to plan and accomplish each day. Now, if you do your daily review in the morning, you'll use it to plan what you want to accomplish for that day if you do your daily review at the end of the day so you can plan the next day, well, you'll use it to plan the next day. And this this daily review typically takes less than three minutes, may take you five, depending on how busy of a day you're having or how busy of a person you are. But it's a very simple process that you use to plan each day. That's a day long review, weekly review. That's what you use to plan and accomplish the week ahead. So you'll also use the time of your weekly review to review your overall map, keep it up to date and make sure that you have and maintain a clear picture of your life. And you can set aside as much time as you need to for this. It might take 20 minutes. It might take a half an hour. You may want to spend even more time. That's totally up to you, probably at least 15 to 20 minutes to do it effectively. And that's once a week. That's a worthwhile investment of your time to make sure that your life is running smoothly. So daily and weekly reviews. Now, the last element of the action map system is doing, and this is what it all comes down to, taking action and not just any action, but the right action so you can accomplish what you need to accomplish. And when it comes time to doing, I'm going to give you some simple but very powerful strategies for helping you to get it done.