= Heather Ackmann Outlook
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===


== Outlook 2019 Essentials By Heather Ackmann

=== Organize and Manage Messages Basics


==== Sort and Filter Messages

Outlook gives you a wide variety of ways to sort and filter messages in Outlook, and I'll be taking you through a couple of popular ways to sort and filter. The *first* method of sorting and filtering is from your Mailbox Pane. No matter the view or how this pane has been customized, you should see in the upper right-hand corner of this pane, underneath that search bar, a drop menu of sort and filter options and an up arrow indicating that messages are sorted with the newest messages up top and the oldest messages on the bottom. Clicking on that arrow will change the sort order, placing the oldest messages on top and the newest on bottom. Clicking the arrow again will toggle it back to the way it was. Clicking on the By Date button will open up and reveal a larger menu with a variety of sort and filter options. Up top, you'll see that you can filter your messages by Unread Messages, hiding any mail messages that has been read. Clicking that again, you can then filter by Mentioned Mail. Now, I don't have any here, but @ mentions is a special thing that you can do within an Exchange Server where you can @ and then type the name of the person that you want to reference in the body of the email to call out or call attention to a specific person in your company. And then, All Mail will return it to show all the mail in your inbox. Clicking here again, you can also arrange your mail messages by specific criteria. The default is set by date, but you can also group it by who it's from or by the flag. So here I have one item that's flagged for today, and the rest aren't flagged at all. That's what that No Date flag means. Clicking again, I can arrange it by the subject of the email or the size of the email or whether or not there were any attachments, what account it's been sent from, or the importance of it. Down below you'll see some of the same sort options we saw before using that arrow. And there's also one more item I want to show you down here, Show Focused Inbox. By default, in Outlook 2019, the Focused Inbox will be turned on. And now that Focused Inbox is this up here, that Focused and that Other tab. The Focused Inbox separates and organizes your email for you, placing your most important email in the Focused tab and the remaining emails in an Other category. Now if you've signed up to receive a lot of newsletters or subscription emails, typically those will appear in that Other category, which is great, as they won't distract you from the more important or pressing matters. However, some people don't prefer that. They find this separation of emails troublesome and prefer that they have just one view for all of their incoming mail. If that's the case for you, you can simply go down here and uncheck Show Focused Inbox, and then they'll return to the old way where you have your All mail messages section and your Unread section. Now, another area where you can go to sort and filter mail messages is from your View tab on your ribbon. In the Arrangement group you'll find a lot of the same options that we were just playing with for sorting, filtering, categorizing, and viewing mail messages that we did from this drop menu here. So if you wanted to restructure this pane here and resort it by date, you can click on Date, and it'll return to the way it was. Or if you want to return and group the messages by recipients, you can click that To button or that From button. Reveal this More button here, and here are all of your other options: Subject, Size, Type, Attachments, Importance. You can also click the View Settings button here or the View Settings button up here in the upper left-hand corner of Current View to reveal the Advanced View Settings window where you can apply multiple sort and filter options all at one time. Or if you want to reset the current view back to their default settings, you also have that button here, and right up here, Reset View. Clicking either of those options, you'll be met with this warning message: Are you sure you want to reset the view Compact to its original settings? Click Yes, and now it's back to the way it was with one exception, and that is the Show Focused Inbox. That will not reset. If you want to turn the Focused Inbox back on, you'll have to come here to your View tab and click Show Focused Inbox, or click that drop-down arrow here, and toggle that back on to turn on that Focused Inbox one more time. So that is your grand tour of all of your sort and filter message options in Outlook 2019.

==== Delete and Archive Messages


Over time, you will acquire quite a few emails and other type notifications in your inbox that you just don't need to hold onto. And to keep your inbox neat and tidy, you can simply delete those messages. The easiest way to delete a message from Outlook is from your Message Pane. To the right of each message, right next to that timestamp, you'll see a big old X icon. To delete that message, simply press that X, or press the Delete key on your keyboard. Now, that doesn't actually delete the message from Outlook, but just move it to your Deleted Items folder. To permanently delete items in Outlook, you will then have to go to that Deleted Items folder, select the message that you would like to delete, and press that X again. Or if you want to clean up or delete all of the messages in that Deleted Items folder, a faster way is to simply right-click right on top of that Deleted Items folder and choose the option Empty Folder. From there, you'll receive a message, Everything in the Deleted Items folder will be permanently deleted. Would you like to continue? Press Yes, and then all of those messages will be cleaned up, or rather, permanently deleted. And by permanently deleted, I mean permanently deleted in most situations. There is one exception to that. If you are like me and are on an Exchange Server account, your Exchange admin may enable a feature that allows users to retrieve deleted messages for a limited time period. If that feature is enabled, you will see an option at the top of your Deleted Items folder and on your Home tab in the Actions group a button that says Recover Deleted Items from the Server. When you choose that option, anything you had recently deleted will appear inside that window, and you can recover that message for a short period of time. So selecting a few and clicking OK, that will restore those items to that Deleted Items folder. Now, another alternative to deleting messages is an option to instead archive messages. If you have already acted on a message, but would still like to keep that message for future reference, archiving it is a perfect solution. So if that message already appears in that Deleted Items area, you can simply select that message and then click on the Archive button located on that Home tab from that Deleted Items folder. And then that message will be moved to the Archive folder. Or if your message appears in your inbox, you can jump on over to that inbox, select the message that you would like to archive, and that Archive button appears on the Home tab there as well. Or you can use the keyboard shortcut backspace as a little bit of a shortcut to move that message to that Archive folder as well. And that is how you can delete and archive messages in Outlook 2019.

Ignore Messages
There are times in a company when someone sends a mass email to an entire department, or to a team, or even to everyone that doesn't pertain to you in the slightest. But the probability of people hitting that Reply All button with comments that also don't pertain to you or with random, sarcastic, or negative comments, that probability is pretty high. So, for situations like that, there is an Ignore button. What that Ignore button does is automatically send this and future messages or replies to that message directly to your Deleted Items folder. To ignore a message thread, make sure that message is selected, and from that Delete group on your Home tab click on the Ignore Conversation button, or use the keyboard shortcut Ctrl+Delete. That will bring up the Ignore Conversation window. Just click the Ignore Conversation button to continue, and then that message will then be moved immediately to the Deleted Items folder. There it is. Now, should you ever change your mind and decide to become a part of the conversation once again, just return to this message or any future part of the conversation in this Deleted Items folder, and you can right-click and uncheck Ignore. That's going to bring up the Stop Ignoring Conversation window where you will see a Stop Ignoring Conversation button. Click on that, and that conversation will then be moved right back to your inbox. But once again, that message or any part of that message has to be kept somewhere in your Deleted Items folder in order for that to work. If you clean out your Deleted Items folder regularly, then you won't be able to recover that conversation. And that is how you can ignore message threads in Outlook 2019.

Apply Categories
One way to organize messages and other items in Outlook is to assign a category to that Outlook item. Categories are very flexible, versatile, and customizable in that you can assign a category across different Outlook items, be it email messages, or appointments, or even contacts and have those categories apply even across multiple Outlook folders. To assign a category to an Outlook item such as an email, from the Home tab in that Tags group, click on the Categorize button. By default, all categories will be assigned generic color names, like Blue category or Green category. You can stick with these color-coded names, but it is by far more beneficial to come up with a system of categorization and labels that will work for the kinds of email items you work with the most. For example, if you travel a lot and receive a ton of flight and hotel or car bookings, creating a Travel category to assign to those incoming reservations will help you locate them in the future. Or, if you are like me and are in the habit of taking pictures of business receipts with an app like Office Lens and emailing it to yourself, you can create a category for business expenses. Or if you manage a bunch of projects, you might consider creating labels of those projects or even category labels to help prioritize tasks and communication about said projects such as urgent, or delegate, or high or low impact. To create your own category labels, click on the All Categories button to open the Color Categories window. From here, you can select a category that you wish to rename and click on the Rename button. Then, simply type out the name for that category. You can then create additional categories from what you see here by clicking on the New button. Or you can change the color of any category by clicking on the down arrow and choosing a different color. Or you can limit the amount of categories you see here by deleting existing categories with the Delete button. Or you can even assign keyboard shortcuts by clicking on the drop-down menu underneath the item labeled Shortcut Key and choosing from the options in this list here, Ctrl+F2 all the way down to Ctrl+F12. Once you've made your adjustments, check the category or categories you wish to assign to your selected Outlook item, and then click the OK button. That category will then be assigned to that item. Alternatively, you can also right-click on any Outlook item, and halfway down through that shortcut menu you'll see those categories appear right there. Simply select the category from that list, and that category will be applied to that selected item. And that is how you can apply categories to items in Outlook 2019.

Mark a Message as Read or Unread
While working in Outlook, you might notice that some messages will appear in bold. That's Outlook's way of alerting you that the message remains unread. You will also see all unread messages totaled up below on your status bar and in the folder inside the Folder Pane. What you may not know is that you also have the ability to mark any message as read or unread in Outlook. To mark a message as unread, the easiest way is to simply right-click right on top of that message, and then choose the option Mark as Unread. Likewise, you can right-click right on top of an unread message and choose Mark as Read. You'll also find these options on your Home tab inside that Tags group. There is a button there, Unread/Read. Clicking on that will toggle that message back and forth between read and unread. You can also use the keyboard shortcuts Ctrl+Q to mark that message as read and Ctrl+U to mark that as unread. Now, if you'd like to select more than one message at a time, you can use your Ctrl key as you are clicking on messages to select multiple messages and then use those buttons to toggle those messages as read or unread. Or if you would like to select every single message inside of a folder, you can use the keyboard shortcut Ctrl+A to select every single message inside that folder. Or yet another way, if you just simply like to mark all unread messages as read, this is a little trick, we can go up to our View tab and temporarily turn off the Show Focused Inbox, jump on over to the Unread tab, select those messages using Ctrl+A, and then simply mark them as read. And there you are. There is a variety of ways to mark messages as read or unread in Outlook 2019.

Create Folders
After a while, even if you've categorized and archived messages that you've acted on, you may find that your inbox is filling up fast with messages. Well, creating folders are a great way to further organize your inbox. To create a folder, the simplest way is to right-click one of the folders in your Favorites area and choose New Folder. That's going to open up the Create New Folder window. If you were to right-click one of the folders in your main area, that's simply going to open up this little tiny box underneath whatever folder you've right-clicked on. And my preference is to open up that full window, so I like right-clicking on one of the folders in the Favorites area to open the grand master list here. At the top of the window you'll see a Name box where you can type out the name for your new folder, and then you can select what type of items that folder will contain. The default, since I've clicked on a mail folder, will be Mail and Post Items, but you can change the type of item from this drop-down list here. There's Contact, InfoPath Form Items, Journal, Note or Task Items, but we're going to leave it as Mail and Post Items. And then simply choose where you would like that folder to appear in Outlook. Selecting the Inbox folder will make this folder a subfolder of the inbox. So selecting Inbox and clicking OK, you can see that that folder is now a subfolder of that inbox. So, if I click this little arrow next to Inbox, it'll collapse the inbox, and then clicking that arrow again will expand to show its subfolders. And that's one way to create a folder. Another way is to jump on over to your Folder tab and choose New Folder. And that'll also bring up that Create New Folder window.

Move Messages Between Folders
Once you have a few folders created, you'll probably want to then begin moving messages to those folders to help organize that inbox. To move messages, there are a couple of methods that you can use. You can right-click a message and go all the way down to Move to view your folders in that shortcut menu. Simply click on the folder that you'd like to move that message to, and that message will be moved to that folder. That's one way. You can also use the Move button on your Home tab, which works the same way as the right-click method, or you can also simply click and drag that message over a folder that you'd like to move it to. Now, if you also have your Focused Inbox turned on, where you have your Focused tab and that Other tab, sometimes you'll see messages showing up in that Focused area that you really don't want showing up in that Focused area. For example, this one, which is an automated message from Outlook, or Office 365 rather. This message and future messages like it, I want to have sent to that Other tab. So to train Outlook, I need to right-click and choose Move to Other or Always Move to Other. And then choosing that option, I'll see Outlook bring up this message: Do you want to move all future messages from Outlook Customer Manager to the Other tab? And I can choose Yes, and now all future messages from that contact will appear on that Other tab. And those are a couple of simple ways to move messages in Outlook.