= Jason Alba Career Plan
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===


== Building and Managing Your Career Plan by Jason Alba

=== Course Overview

==== Course Overview

Hi everyone. My name is Jason Alba. Welcome to my course, Building and Managing Your Career Plan. I'm CEO and founder at JibberJobber.com and a soft skills author at Pluralsight. In this course, we're going to talk about *how to plan out the rest of your career*. I know, I know, things can change, so we talk about change quite a bit. Some of the major topics we will cover include specific steps to define your career plan, understanding how your motivators impact your plan, keys to career success, and finding joy and happiness in and outside of work. *By the end of this course, you should feel confident in your ability to create a career plan that you can really believe in. You'll have plenty of ideas to build a realistic plan and understand how to navigate your career as changes come your way*. From here, you should feel comfortable diving into other career topics with courses on Career Management 2.0, The Future of Technology Careers, and various other courses on soft skills and job search. I hope you'll join me on this journey to learn about your career and your future with the Building and Managing Your Career Plan course, at Pluralsight.

=== Creating the Path to Your Career Goals

==== Introduction

I'm excited about this course because I'm excited to talk about anything that has to do with your career. I'll be the first to say that whatever career plans I had went out the window within a few years of making them. But just having plans, goals, and ideas of paths to take helped me navigate the inevitable changes that would come. In this course, we'll first talk about the idea of a career path or your career plans. Next, we'll talk about working your plan. And then we'll talk about achieving your career goals. The idea is that while the path to get to your goals might change quite a bit, you can still have some amazing accomplishments in your career, maybe even better than what you originally wanted. *Changes in your plan can be frustrating and exciting, scary and overwhelming*. One thing I've learned is that we need to figure out how to handle these changes or we'll be miserable. This course is designed to help you establish your plans and goals, but also to enjoy the journey even as changes come up. Throughout this course, I'll use a fictitious character named Daniel to illustrate some of my key points. Daniel is at a point in his career where he realizes he wants something more. He's interested in getting promotions, but he's not sure how to get them. If Daniel creates, understands, and works his plan, we hope he'll be successful and happy, but that's not always the case. Maybe what Daniel thought he wanted was not as great as he imagined it would be. Join me and my fictitious friend, Daniel, as we walk through steps to create and work a plan and ultimately find fulfillment from our career.

==== Your Career Path

I want to talk about three important components of your career path. Each of these components are important to understand as you create a path that works best for you. *The three points are where you are, where you want to end up, and the points or path along the way*. If you're feeling nostalgic and want to consider the first point where you started, say some life changing experience when you were a teenager, that's fine, but it's also fine to start from where you are right now. Notice the path on this image. The path is not a straight line. There are also hazards. On the top left are mountains and on the bottom right is water. When you think about where you are, consider how you got there. What had to happen in your life to help you get to where you're at? This could include education, experiences, accomplishments, even your personal drive, the things that make you who you are today. It's critical to understand that these contribute to the value you currently add to your employer. For example, do you bring anything special to the customer relationship? Do you have a knack for thinking about things the way an architect might? Maybe you have a great capacity for understanding mathematical challenges or you're highly skilled with user interfaces. Take a moment and list the value you bring to your current role. The second component of your career path is where you want to end up. On the map, this is the X, the final destination. How you define your final destination could be by a certain title or because you work at a certain company or making a certain amount of money. There's no wrong answer for how you define your destination. For some it will be being CEO of a company while for others it will be a regular title, but with the right compensation and fun and meaningful work. Once you clarify where you want to end up, think about why you want to end up there. Why do you want to have the title you wrote down? Is it because you are translating that title to money, power, control or prestige? For example, if you wrote down that you want to retire as a senior engineer, why is that? Perhaps you value having more autonomy and want to make decisions that junior engineers don't get to make. As you list reasons for what your final destination is, you might realize the title or salary, or whatever, isn't necessarily as important as the reasons you wrote down. Between the beginning of your career path and the end of your career path is the journey along the way. There are a lot of points that can be significant in your journey. They could be finishing school, getting promotions or raises, transitioning to a manager role, starting your side business, etc. Some of these clearly help you move towards your objectives. For example, if you get a junior developer role, a logical progression would be to a senior developer role. If you want to manage a team, any leadership opportunities will be a logical step to get you there. Planning your career path is important. Just remember to respect changes that will come. Changes come from many different places. I usually speak at job clubs and see people who have had changes imposed on them by bad health, changes in their family, the economy, organizational changes or even just a change in personal priorities. Plan enough flexibility into your paths so that when these changes come, they don't derail you. If everything goes according to plan, great. If not, that could be okay and you could still find a lot of satisfaction and fulfillment along your career journey.


==== Creating Your Vision Statement

Early in my entrepreneurial journey, I came across a really cool exercise that made a big impact on how I think about vision. I don't remember exactly where I heard this, but I know the impact it had on me and hope you will take some time to do this so you can have a similar impact. *A personal vision statement can be multiple sentences, even multiple paragraphs, of very specific declarations of what your career looks like*. Of course, you could include things about your personal life and goals. Even though this is a vision of the future, of things you're working towards, *it is written in present tense*. Your vision statement is so specific, it almost feels tangible. Your vision statement becomes a tool to help you create your plan and make big decisions. It helps you monitor your progress and determine if what you've been doing will really help you achieve your career goals. Without further ado, let's go into an example of part of a vision statement. Take note of how specific this is. Imagine our friend, Daniel, has written his own vision statement. We'll break this down in a minute. First, here it is in its entirety. I am a successful software architect at a top tech company. My company makes a difference in the world, impacting almost every household on the planet. As an architect, I have a significant role in contributing to the company's success and to make the world a better place. I am respected amongst developers and architects, even outside of my organization, and influence developers, architects, and product managers. I make X every year and I feel rewarded and respected. Note, I intentionally left the compensation ambiguous, mostly because Pluralsight has learners around the globe and I don't want to limit your own thinking. In your vision statement, you would put a specific amount. The first thing Daniel says is, I am a successful software architect. He's speaking in present tense and with the title he aspires to, not the one he has right now. Remember, this is your vision of something in the future. He continues. At a top tech company, he could put the name of a company to be more specific, but I didn't because in 10 or 20 years when he realizes his goals, the top tech company he'll work for might not even exist today. But if you have a company you want in your vision statement, definitely put it. The more specific, the better. In this statement, he talks about fulfillment received from working at a company that makes a difference and impacts people. Early in my career, I didn't think much about this, but as I have grown, this has been a more important driver of my goals. In this statement, Daniel talks about his specific role and the impact he has. More than just being at an awesome company, he wants what he brings to actually add value to the organization and mission. I love this statement. He talks about the impact he has on the tech industry and who he influences. Again, make sure you have a specific financial target written down. He writes, I feel rewarded and respected. This is part of that intrinsic reward for having worked so hard in his career and gotten to where he is. What I've shared could easily be expanded. Yours can be this short, but don't be afraid to make it longer and more detailed. Keys to making a great vision statement are to keep it present tense, using phrases like I am, including as many specifics as you can, and being flexible as the years go by. There's nothing wrong with your career going differently than what your vision statement declares. The point is that you are intentional and purposeful about your career objectives. If you are decisions you make will contribute to a rich, rewarding career.

==== AA

---

Your Dream Job
When I was young, I wanted to be a top executive at a big company. I wanted all the glamour and prestige I thought came with that role. In college, I had an internship where I had easy access to a magazine titled CIO. I absorbed every page of every edition. I was enamored with the idea of being CIO, a top executive managing and strategizing the most exciting part of a company. CIO became my dream title. After a few twists and turns in my career, I was in a new organization created after a company merger and was asked what I wanted my title to be. I would be second to the president and knew immediately I wanted to be CIO. It had been my dream for years. Of course, my job responsibilities were much more varied than what I read about in the CIO magazine, but at least I was in the leadership role. I worked for that title and was proud to have it, even though the company was virtually unheard of. Later, I assumed the top position at the company, but the title changed from President to General Manager. I was bluntly told this was because I was too young to be president and executives in the parent company would be jealous of me having that title. While I wasn't thrilled with that reasoning, I was thrilled to be at the head of strategic and operational decisions. Fast forward a year and a half and I found myself laid off. People who looked at my resume saw my titles and experience and said I should quickly land a job. I was so glad I had those titles. But here's the funny thing. I remember going to a job seeker networking meeting and sat next to a guy who had the same exact titles I had on my resume, but he had 20 years of experience over me. I was shocked. The realization that he was way ahead of me and still unemployed was scary. It was then that I really understood, a title alone was not what I should have worked for. If I could go back and counsel the young me, I'd tell myself to make sure I understood roles and responsibilities and list what skills would make me exceptional at my role. Titles can change based on location, industry, company size, and, yes, tenure, but if you can talk about what you do, what value you bring, how you make or save money for a company, how you make things better or faster, then your title matters less. I was hung up on a title without realizing I should have been working for specific roles and responsibilities. For you, that might mean you want to have a certain budget or manage a team of a certain size. Perhaps it means you're the person responsible for architecture, quality, product, uptime or conversions. Knowing what I know now, I would define my dream roles and responsibilities and what those look like instead of simply targeting a certain job title. Then, get really good at talking about what you actually do instead of just what your title is. In some settings, saying your title will be fine, but in other settings you'll communicate better if you say what you do rather than what your title is. While you are defining your dream job, make sure you define target compensation, growth opportunities, even where and when you work. Do you want to ever be on call even in a rotation? Do you want to be able to work remotely for months at a time? What kind of accountability do you want? These are all things that go into defining your dream job

The Path to Your Dream Job
Now that you have a more solid definition and vision of your career objectives, a roadmap and the jobs and roles you want to have, it's time to figure out what the path moving forward might look like. A word of caution, though. Early in my career, I thought the path to my career goals was linear and logical. And really on paper it was, but things don't always work out in real life the way they do on paper. I've talked to a lot of people about their careers over the years and have rarely talked to someone whose career path was logical and linear. And if it was, I'm thinking about dentists and doctors, it was much harder than they thought it would be. Whatever the opposite of linear is, that's how my career path has been. One of the most important things I've learned from this is that my plans need to be flexible. During that flexibility, I need to keep a proper perspective so I don't feel like my planning was overly optimistic and useless. With that as a preface, I still believe we should have career goals and aspirations and that we should work towards them. There's this idea that if we shoot for the moon, we may not hit it, but we'd make a lot of good progress. That progress comes in personal and professional growth, finding joy and happiness along the way, and learning from every opportunity, experience, team, and project you find yourself in. I'm very objective‑driven and I would not let myself be happy or satisfied until I had achieved my objectives. I finally realized I was missing out on a big part of life, namely the journey I was on. Instead of saying, I'll be happy when, I started to appreciate where I was at on the journey, the things I was able to learn and do, and the opportunities ahead. No longer was I waiting to enjoy my career and my life. I was able to really appreciate where I was at. So, do we just do away with the plan? No, definitely not. I strongly encourage you to make a plan, define a path or multiple paths, just make sure you revisit the plan regularly and figure out if the goals are still the same and if the path still makes sense or needs adjustments. You have your objectives defined, and the best thing to do is work backwards from those objectives. It's a lot easier to figure out how to get where you want to go by working backwards, then working forward. I learned this while doing mazes. It's way easier to do a maze on paper from the exit than from the beginning. If you want to be a senior developer, how do you get there? Well, who are the people that are getting senior developer roles? They're likely people who have some solid training, whether from school or courses, and know how to learn new technologies. They also know how to evaluate technologies and when to implement something and when to ignore it. They might have X years of experience and have worked with Y different technologies. This is what working backwards looks like. From there, you can say, okay, how do I get X years of experience working with Y different technologies? As you go through this process, you can see the value of staying at a company that gives you these types of learning experiences. When new opportunities arise, you can determine if they will help you get the experience to achieve your career goals. Your plans and this information you put together become tools to help you make better career decisions along the way. And changes will come. You will change, companies change, industries change, opportunities and technologies change, but your career objectives might stay the same during these changes. As you stay true to your goals, believing in them and yourself, you can make wise career decisions to help move you closer to those objectives. If you find your objectives changing, that's okay too. This happens as you mature and have stronger convictions of what would really give you career happiness. Maybe you realize a management role is not for you. You would actually hate it. There's nothing wrong with that or with you. I know plenty of technologists who will never be managers, but will have very satisfying careers. What you thought you wanted 5, 10 or 20 years ago should change. Don't be shocked by that. As you mature, your goals can mature also. When I was a kid, no one had any notion that there would be opportunities for careers and leadership in the massive changes created by online shopping, which has impacted every aspect of the logistics industry, or changes coming from advancements in the electric vehicle industry or alternatives to currency. These are just three examples of industry changes that have impacted goals and career paths just in the last few years. Be open to change, even embrace it, and you might find the path you take to be vastly different than the path you designed. This could be as exhilarating as it is frustrating, but it's your path. Be purposeful, strategic, and flexible along the journey.

Finding Your Motivators
In 2009, an acclaimed book was published titled Start With Why, by Simon Sinek. Simon has a few TED talks, one of which is on the topic of this book. Finding, defining, and understanding your why has become a big conversation at many levels of an organization. I remember going to a sales call where in the conference room I saw a poster talking about starting with why. Just recently I was talking with a friend who manages sales people who said he sat down with one of his new hires and had a long conversation about the new person's why. From the executive suite to the entrepreneur, we should all seriously think about what our why is. Your why becomes your motivation to get up in the morning and show up ready to work. It can motivate you through difficult interpersonal issues, as well as through boring meetings. Having a why can drive everything you do, while you're at work, as well as when you are away. Simon didn't invent this idea of why. The famous author, Mark Twain, who was born in 1835, is credited with saying, "The two most important days in your life are the day you are born and the day you find out why." My last boss lead with that quote in his presentations, and it really had an impact on me. I wondered, have I found out why I was born? If so, am I living my life in a way that honors why I was born? I'm sure Mark Twain didn't pioneer this idea of starting with why or figuring out your why, but I know when you understand your why, amazing things can happen. This might mean you accomplish things that change the world or you change individuals' lives. Maybe you just change one life. Maybe your why helps you break chains of abuse or addiction or simply finds peace and joy in your own existence. Finding your why and understanding what motivates you will have a huge impact on your job satisfaction, your performance, and what you strive to accomplish. Knowing your why will impact what your goals are, as well as the path you take to meet those goals. It will impact how you treat yourself and others. It will impact the risks you take and how you define and deal with success and failure. I believe finding your why impacts how successful you feel you are. Your motivation could be financial, perhaps it is to become wealthy, or at least to provide a better life for yourself and your family. It could be the prestige of working for a certain company or having a certain title. Your motivation might be your societal standing, the recognition you get, fame or things like that. I've learned to not judge others by their why. What motivates even my own kids is different than what motivates me. That's okay. It has to be okay. I've worked with a lot of people over the years and have learned many people have whys different than my own. Here's a secret. Understanding their why will help you impact, inspire, and even influence them. I'm not saying you should manipulate them, but understanding and respecting their why is a powerful part of being able to effectively work with others. Your motivation can easily change based on circumstances. If you start a family, your why might change. Buying a house, downsizing, dealing with debilitating or chronic illnesses are all circumstances that could impact your why. My why changed after I got laid off in 2006 and went through depression and a very poorly executed job search. My why now is much more meaningful and much more fulfilling. I think my main takeaway from this is that you might need to be flexible with your why. I know my motivation when I was, say, 12 was much different than when I was 21, and different now in my late 40s. I'm sure as my health and family dynamics change, as well as my finances, my why will shift. I'm emphasizing flexibility here because I don't want you to create a vision for what your career should look like and then not respect changes in your life that have a real impact on your vision. Changes in your aspirations or circumstances does not mean you're a failure, nor does it mean you have given up. Life is all about changes, but defining your why now can give you significant direction and motivation as you move forward in your career.

Job Satisfaction Factors
It seems most of the time when someone new to the job market thinks about a job, they think about target companies, job titles, and salary. We tend to measure our success, future happiness, ability to finance our lifestyle, etc., on what our salary is. I knew an executive who was transitioning from a very successful career and looking for his next opportunity. He had a good 10 years before he was ready to retire and wanted to find a job where he could make a lot of money in those last 10 years. I remember chatting about some options he had. He identified a company that had some red flags, or what I like to call yellow flags, that is not something so blatantly bad but indicators that could be concerning. He said he could work through any issues and inconveniences as long as he optimized his earnings. Well, long story short, the yellow and red flags became unbearable. The promised income was modified, and not in a good way. Looking at a sole criteria for a major career decision was not the best long‑term strategy. There are a lot of factors that impact your job satisfaction or career happiness. I want to talk through some of these factors that might be more important than compensation. You might have other factors to add to your own list, and perhaps some of these factors won't matter very much, but at the very least I want you to make decisions on jobs, and even career objectives, based on factors like these. Here are some considerations regarding job titles. Having a title at one company is not the same as having a title at another company. I was a general manager, but of a very small company. I wasn't qualified to be a general manager for a large organization. Still, titles could be important as you move towards your career objectives. Sometimes the progression in titles is linear and logical, other times you might want to consider how a nonlinear career path with titles that seem to take a weird turn can help you achieve your long‑term objectives. For example, having development, DevOps, and sales engineer experience can really prepare you for a management or leadership role, if that's what you're interested in. Another factor is the brand and prestige of organizations you work at. I've found working at organizations that are well known, maybe they're a household name or a hot name in the tech field, can help you later in your career. Their brand can complement your personal brand. You can probably think of a few companies that would add considerable prestige to your resume. I'll often advise people just starting their careers to seriously look at some of those organizations, even if just for a few years. I like to look at the size of the organization. Small, medium, and large organizations have their own pros and cons. At a smaller organization, you'll likely wear many hats and have a lot more responsibility preparing you for leadership roles, but they could be more volatile and perhaps not have ideal budgets. Larger organizations have those budgets, but you might find yourself very siloed and feel like you aren't contributing. I can't say what's best for you, but you need to strategically think about the best organizational size for you. I've known plenty of people who travel for work all the time. At first, traveling as kind of fun. You get an expense account and can spend as much time on planes, in hotels, and at restaurants as you want. I remember a time in my career when I was flying to Atlanta, Georgia. The first time was exciting and fun. The second time, the romance was over the minute I took my seat on the airplane. I would have rather spent more time with my family than in a hotel room for weeks at a time. There might be a good time to do a lot of travel in your career, but when it's not the right time, you might find yourself miserable no matter how much money you're making. Consider the team you'll work in. How big is it, and who is on your team? What are the leaders like? What about your colleagues? Are any of them thought leaders? What kind of expertise do they have, and what can you learn from them? Working on an awesome team is exhilarating. Working with challenging people who aren't as bought in or are difficult to work with is no fun. There are other considerations. I worked on a team that had a huge task to accomplish, but the organization dedicated a very small budget to get the work done. Instead of having access to the resources we needed, my small team was expected to do everything on our own. It really was an unfair challenge and didn't end well. I always wanted to know what impact my work will have on the organization and maybe even society. I want to build things that create value. When I'm on tasks where I'm not doing that, I question whether I'm in the right place or not. Working on meaningless projects can be demoralizing. Along those lines, I want to be in an exciting, technical environment as opposed to an environment that makes me wonder if all of my colleagues are keeping up with tech, but I'm stuck maintaining stuff while not learning anything. Do you want to work in an environment that seems stale and outdated or do you want to work in an environment that seems to be on the leading edge? Pros and cons to either, really. Other considerations include your potential for growth, either personal growth or growth within the organization, total compensation, including bonuses, profit sharing, etc., other neat or unusual perks that actually add value to you, the organizational culture, and work from home options. I've realized some of these considerations have had a big impact on how happy I was. I need to reemphasize what happens when circumstances change. For example, you add some kids or a spouse to the equation or you move to somewhere that is more or less expensive or your finances are in a better place. Some of the factors that mattered to you don't matter as much anymore. This, like almost everything else we've talked about, is fluid. Don't feel bad about these changes. In fact, reevaluate over time to determine which factors continue to be important.

Education and Your Career
I am a product of the 1900s. I was born in the early '70s, which means my formative years were during the epic '80s. Everyone knows the music and movies of the '80s were amazing. An interesting dynamic of the '80s is that anyone who is thinking about a career back then was learning from family and mentors how to have a great career. The '80s are what I consider to be the tail end of a romantic idea of the past, the notion of job security. Job security was a promise that you would work at one company for most of your career, seriously, for decades. You would have a decent life and then retire with a company pension. It didn't seem like a bad idea. Get a good job, do a good job, and retire with what amounted to a paycheck until you die. The way you got this was by doing a few things, one of which was getting the appropriate education. The type of job you wanted would direct you to either university classes or a trade school. Education was a valuable thing back in the '80s. Education meant you had some institution train you and give you a paper saying you accomplished certain objectives. We all know things have changed. Fast forward to the early 2000s when I got my MBA. It seemed like everyone had an MBA. I once told a recruiter who asked me about myself that I had a CIS degree and an MBA. His response shocked me. Oh, yeah, I know the type. He had talked to so many people with IS degrees and MBAs that we were completely stereotyped. I'm not here to tell you you need to or don't need to get a university degree. Regarding your career objectives, there are three very important aspects of your personal education I want to talk about. First, you need to identify the educational requirements to be successful, as well as the education you should have to excel. If you want to be a doctor, you go to medical school. If you want to be a lawyer, you likely go to law school. If you want to be a programmer, you, uh, well, do you get a degree in CS? You certainly could, and it could provide an excellent foundation for your career, but I know plenty of developers who don't have CS degrees. They range from self‑taught to boot camp trained. One of my favorite developers was a theater major and dropped out after his first year, not even close to finishing his degree. He's gone on to have a very successful career as a developer. You probably know someone like that, someone who didn't have the intense CS classes, but somehow has become a valuable, contributing team member. How do you get the right education? The truth is, there are plenty of opportunities and programs to learn how to become a developer. Combine continual education with practice and over time you can have excellent developer skills. When I hire developers, I take their educational background as one of many data points. I might be impressed by it, but as long as the candidate can communicate their proficiency, I'm not too concerned if they don't have that formal training. A quick story. After being a developer for 18 months and doing a contract programming job on the side, I was in a conference room being offered a job. The company I did contract programming work for had gotten to know my work, my personality, my work ethic, and had a solid idea of the value I would bring to the organization. It's a cool story I don't have time for during this course, but basically I had written the job description and defined a salary, assuming it was for someone else, because I was going to move to Texas to be close to Dell Computers. After I was offered the job, I said to the guy who would become my boss, wait a minute, you didn't even ask me what my GPA was. He replied, I don't care what your GPA was. I was quite taken aback because for years in high school and college, the importance of GPA was emphasized so often. But in the end, it didn't matter, not for that job or for any job I've had after that. Think about your education as something for you, not to satisfy a requirement to get a job. Of course, if you want to work for an organization that requires or values it, then put that in your career plans. Second, as you look at the journey you have laid out and the objectives you have, think about what additional education will help you find success. For example, if you want to be in management, consider accounting and finance classes. If you want to work with customers, consider sales and onboarding courses. If you want to be an executive, learn about business strategy, leadership, negotiation, and communication. You should be able to pinpoint specific parts of your career journey you have outlined and determine what training will help you both qualify for the role and excel in future roles. I know people who are in the last decade of their career who sign up for courses, either at a college, online or whatever, to learn about new topics or areas to help them prepare for a promotion or added responsibilities. I recently tweeted, If you have chosen a career in technology, you have chosen a career of lifelong learning. There was a time in my life when that really intimidated me, but I've since embraced the idea that I'll always be learning. Third, one of the most important things you'll need to do is learn how to communicate the value of the education you have chosen. No longer can we say we took a course or a class or earned a degree and assume people will really understand how that has helped us. We need to be ready to say what we have learned and why that qualifies us for a certain role or for more responsibility. Of course, education alone won't always get us what we're after, so talking about practical experience with what we've learned can really set us apart. Think about your personal brand and how to best communicate your educational journey. When I talk to candidates about what they know and have done, I want to get an idea that they appreciate learning and are not afraid of it. I'm excited when I talk to someone who values lifelong learning and realizes there is a lot of opportunity for growth. With technology changing so fast, that's the mindset I need. Education really is a lifelong journey. My hope early in my career was that I'd be done learning by the time I was done with my degree, then I could focus on my career, but I found that to be too naive. Everyone has to continue learning, even people outside of tech fields. Figure out what education would really help you along your journey and position that education so it helps you get the right opportunities.

Valuable Experience
Experience is a tricky thing, especially when you are new to a field. People want to hire someone with a certain amount of experience for beginner roles, but beginners typically don't have a lot of experience. This isn't just a problem for beginners. You might be mid‑career and find yourself passed over for a role on a team you want to be on because you don't have or haven't communicated you have the right experience. There's no doubt about it. Having the right experience can open doors. There are two important considerations I want you to think about with experience as it relates to your career objectives. First, you need to get the right experience. If you want to do front‑end development in the next year or two, what experience will help you land a front‑end role? If you know what organization, department or team you want to work in, talk to people there to find out what technologies they use and which technologies they are looking at. Getting this kind of insight helps you focus on the right things. Then, dig in. Learn as much as you can, and if you can, start using those technologies on your current projects. If that doesn't make sense, create your own projects where you can use those technologies. I strongly encourage you to journal your experiences with each project as you go. I call this a job journal, by the way. As a hiring manager, I will ask questions to understand how well you understand certain technologies. If you can't really talk about them, I won't be impressed. Rather, I'd question whether you just copied code without knowing what you are doing. I want you to be able to walk me through your projects, what you learned, what your challenges were, and what some of your creative solutions were so I can feel confident that your experiences really would add value to my team. Also, journaling this will help you focus on the learning aspect of your development. It should help you be more purposeful and strategic about your craft. The second aspect of experience is how you communicate your experiences. Too often, I think we tell someone we did something or show someone what we did and trust they will really understand the nuances of what we have accomplished. Instead of assuming they'll figure out those nuances, why not craft ways to talk about those nuances? That way, you will be sure to highlight the specific things you want to bring up, diving deeper into challenging technologies or thought processes or problem solving examples. You'll also be able to emphasize the points of your experience that really speak to the needs and challenges of the team you want to work with. This is especially important when you don't have the exact experience someone is asking for. Learn how to communicate what you've done in the past and how that applies to what they are asking for. This is called transferable skills. We need to understand and appreciate our past experiences and apply what is applicable to current needs. Learning how to talk about those experiences can help you move forward in your career. A great tool to communicate your experience is a portfolio. Your portfolio can showcase projects you have worked on, including side projects, pet projects, even open source contributions, showing your experience with certain technologies. Your own projects could be things you're interested in. For example, some idea you've come up with on your own or any of the many programming projects or challenges you can find online. Over time, you should have a collection of projects that really show your proficiency. My two points are simple. Get the experience you need, even if it means you do side projects or projects outside of work. Maybe you get paid for these, maybe you don't. As long as you are working towards your career objectives, either scenario might be acceptable. Then, make sure you know how to talk about the important parts of your experiences, positioning yourself as someone who can be a valuable addition to the team because of real projects and experiences you've had in the past.

Your Personal and Professional Brand
I am profoundly interested in personal and professional branding. This isn't because I read some books on it. My passion and interest came from when I lost my job and went through a very difficult job search. I realized the two things holding me back were not having a personal brand and having completely neglected professional relationships. Even though I had a technical degree, an MBA, and some impressive job titles, I felt like I was starting from scratch. Professional relationships, or networking, go hand in hand with branding. People needed to know who I was, they needed to know about me and even how to think or talk about me. Unfortunately, this meant I needed to know about me and how to think or talk about myself. I found this to be a lot harder than what I was expecting. I didn't make the connection that this was self‑marketing, specifically branding. I'm not sure I had even heard of personal branding. I quickly realized this was going to be a gargantuan task. I've since learned we can control our brand, that is how others perceive us. We definitely don't have to wait until we're in transition. Here are some ideas regarding your brand. First, your personal and professional brand are one in the same. How you act outside of work can impact your professional brand. We've seen this play out time and again over the years where people do something off hours that is so revolting they lose their job or somehow suffer consequences professionally. I'm not saying you can't have privacy, but who you are and what you strive to become will impact your brand. Next, I see a lot of misunderstanding about what branding actually is. People think their brand is who they are or what they do. The reality is it's not who you are or what you do, it's not even necessarily what you want it to be. Your brand is simply how others perceive you. For example, you might be the best programmer on your team, but your brand might be that you're exceedingly difficult to work with. How you think about yourself can differ from how others perceive you. Next, we need to figure out how we can influence how others perceive us. Professional marketers help customers and prospects perceive and talk about them the right way. We want to do the same thing. We can do this by sharing the right language, perhaps through a tagline or elevator statement. This is not as easy as you might think. I usually see taglines that are more confusing than they are helpful. They try to use clever or cute phrases, usually with cliché or jargon, and they confuse more than they clarify. Next, I've learned my brand needs to be purposefully, explicitly stated. I used to think you could look at my background, what I do, and my title and figure out my brand, but I've learned that we are usually quickly categorized. We are put into general buckets, many times doing us a disservice as these categorizations do not accurately reflect who we are and what our value is. I learned from professional speakers to never let a conference host come up with your introduction. You always want to write your own introduction or else they will focus on things that are different than what you want them to focus on. I could go on and on about personal branding, and actually I have. One of my favorite courses I've created here in Pluralsight is called Developing Your Personal Brand. It's one of my favorite because it can have such a big impact on your career. I strongly encourage you to watch it because your brand and how you communicate and understand your value will be an important part of achieving your career success.

Summary
In this module, we talked about considerations to understand and define your career path. Your defined career path has a beginning, an end, and points along the way. We talked about visualizing your career and creating a vision statement. We talked about your dream job and what that really means. We talked about the realities of the path to your dream job. We talked about your motivators, or your why. We talked about factors of job satisfaction and happiness, education and experience, and your personal and professional brand. In the next module, we'll build on this foundation and talk about specific tactics to move forward with your career goals.

Thriving during Your Journey
Introduction
In this module, we'll talk about how to move forward with your career plans. This module is more tactical where we break down ideas to help you define next steps to achieve the objectives you laid out and execute on the plan and vision you've defined. Before we get started, I want to share an important message with you. Some of you might find this message a little silly, but I know there are people who need to hear this message. The message is, I give you permission. I give you permission to think bigger. I give you permission to think about those big job titles and know you deserve to have them and can earn them. Some of you are wondering if you're good enough, if you have what it takes or even if you deserve to have a position that right now seems out of reach. If that describes your thinking, I want you to know it's okay to think bigger and I give you permission to do so. But really, you don't need permission from me. I know you can work towards your big dreams without my permission or validation. With that, let's jump in.

Identify Your Target Jobs
After watching the last module, you should have a good idea, hopefully even a written list, of your ideal job titles and roles. These are the big jobs you might have at the end of your career, or the dream jobs you want to spend a lot of time in. Daniel, our fictitious friend, has listed three target jobs. Each of these are quite different from one another. The first one is in senior management. He wants to be an executive in an organization. His second ideal job is as a senior individual contributor. This would be non‑management and deep into technology. His third ideal job is being an entrepreneur. He thinks he wants to own his own business, even though he's not sure what that means. I'm guessing one of your ideal jobs is similar to one of Daniel's. We'll use these three very different end goals as we walk through this module to figure out plans, paths, and considerations to help you move forward.

Working Backwards from Titles
Once you have defined your ideal job titles, work backwards to create a plan. We'll use Daniel's three ideal jobs he's identified as an example of how to work backwards. There isn't necessarily a best way to approach this puzzle. What I do is figure out where I want to be, where I am, and then understand the gap between those two points. I might find I'm actually pretty close to my goal or that I have a long way to go. Then, I want to identify the titles and roles that are inside this gap. When I was close to finishing school, my professor told me my first job would be tech support on the phone. I did everything I could to figure out how to skip that role. Putting titles in a logical progression between where you are and where you want to be does not mean you actually have to have those jobs, but it helps you identify skills and experiences that would help you in a subsequent role. Speaking of skills and experiences, you might consider how much time to spend in each role. Having a role for three months gives you exposure, whereas having the role for three or more years gives you enough time to really dig into some of the problems and opportunities. Exposure might be enough in some roles while deep experience in other roles would really help you get future jobs. I've managed developers for many years and am so grateful I started out as a programmer. My experience as a programmer has helped me lead and communicate with my teams during critical situations. Make sure you enjoy each step along the way and learn from every job. I've had jobs that gave me very difficult experiences. I didn't know it at the time, but working through those hard times would prove to be beneficial later in my career. Having said that, you don't need to have every title you've put on your list. You could go from a developer straight to a team leader or CIO. There are so many factors involved, including the current job market, as well as the size of organizations you work at. Having certain titles isn't necessarily a prerequisite for your next steps. I've talked to plenty of people who worked at massive organizations and think they could never get to director or CIO level, but then find those opportunities at small or medium‑sized organizations. Moving to a smaller organization could be your path to skip some titles. Diving deeper past titles, you could list job requirements. Some organizations call these KSAs, which stand for knowledge, skills, and abilities. It's fun to think about the knowledge, skills, and abilities you need to achieve your career goals. Gaining the right KSAs comes as a result of your drive, learning, and opportunities you get from work or volunteer experiences. You should be able to list different knowledge, skills, and abilities you will need for future roles. But if you run out of ideas, find job descriptions to see what hiring managers or recruiters are asking for. Looking at current job descriptions is a great way to make sure you're including the right requirements for roles you are interested in. Make sure you look at multiple job descriptions, looking for commonalities between them. Let's start with an executive role, which might be CIO, CTO or VP. Titles you might have along the way include Director of IT, Director of Engineering, and perhaps something with leader or manager. Executives should be versed in strategy, finance, operations, and other tactical areas. Soft skills such as communication, presenting, and persuasion are important for executives. You might need certain educational credentials, such as a master's degree. Working backwards from a senior engineer role, we can do the same exercise. Because this is a non‑management, highly technical role, the list of requirements will be a bit different from the executive role. A senior engineer needs to have a certain depth with certain technologies and likely exposure to a variety of related technologies. Senior engineers should have a work history that shows years, maybe decades, of experience. The more examples of experience with these technologies Daniel can collect throughout his career, the easier it will be to communicate his breadth and depth to show he is qualified for a senior engineer role. I know senior engineers who are self‑taught without a formal education. Whether you have a formal education or not, communicate your ability to learn and evaluate new technologies. What other characteristics would you add to Daniel's list? Daniel's third career aspiration is to become an entrepreneur. What are the things he can do to prepare to become an entrepreneur? We could talk about this for days. Let's start with creativity. Whether that has to do with product creativity or creativity in getting funding, there's a lot of creativity involved in being an entrepreneur. Daniel should know that being an entrepreneur will test his work ethic. He'll need to be able to push through the hard parts of being an entrepreneur, be self‑motivated, and figure out where to get answers to his questions. As an entrepreneur, Daniel should work on his network and find people who can help him move to the next level. Understanding personal and business finances, as well as his risk tolerance will be helpful. I should mention, he can practice all of these in a job if he gets a chance to be what's called an intrapreneur, which is someone at an organization who thinks like an entrepreneur. These simple examples give you an idea of how to work backwards from your target jobs, list anything that helps you define the steps to get there, including education, soft skills, and experiences.

An Example of Working Backwards
Let's walk through an example of working backwards. We'll pick the specific role of a team leader, which is one of the jobs Daniel listed on his path to becoming an executive. The initial question is, what does it take to get this job and to do it well? You could rephrase that by asking what knowledge, skills, and abilities will help me become a team leader? Daniel, having listened to the last video, goes to a local job board and finds a few job descriptions for a technical team leader. He pays most attention to tech companies because he works at a tech company. In the job descriptions he found, he sees a lot of technical requirements because technical team leaders usually spend a good portion of their time in tech as opposed to just managing their team. He sees team leaders need strong technical skills, as well as interpersonal skills to lead a small team. There isn't P&L or financial responsibility, but he sees multiple job descriptions talking about having strong communication skills. He sees successful team leaders have experience leading and managing technical teams, perhaps with large and complex projects. He also sees there's a preference for a college degree or the equivalent of a degree. There's definitely a gap between where he is now and the qualifications he needs to be a team leader. He doesn't have a degree, but he has a lot of course work and personal study. One of the things career coaches teach us is that we need to learn how to communicate how any skills or experiences we have can contribute to our success in the role we want. This is called transferable skills. There's a lot of great information online about how to craft stories or quantify your skills and experiences in such a way that you could satisfy requirements you would not otherwise meet. As Daniel goes through this experience and creates a detailed list of things he should work on, he wonders if he'll get the training and opportunities he needs while at work. I would recommend he talk to his boss and maybe other executives to let them know he wants growth opportunities. He might also look at volunteer opportunities, perhaps serving on a school board, doing work for a local nonprofit or even helping a tech meetup. Daniel needs to find experiences wherever he can so he can build stories to show he works well with others, that he can lead a team, that he can deal with change or conflict resolution, work with other teams or whatever is listed on those team leader job descriptions. I know it can feel uncomfortable to look for, even volunteer for, these other responsibilities that might be out of your comfort zone. I'm reminded of my first tech interview I went to. I already had a fairly decent job. Why, then, did I get dressed up in my out‑of‑fashion suit and go to an interview? I needed to get my career moving forward. My job at the time was not a career job. I remember walking towards the interview. In the parking lot, I shook my head and started laughing, wondering just what was I doing? I was doing my career management. I was doing what only I could do. I'm inviting you to do things that might feel uncomfortable, but they are the right things to do to progress in your career. This might mean you go back to school. If the organizations you want to work in require formal education, it might mean you develop professional relationships, also known as networking, with people who need to be in your network. It might mean you show up, even when you'd rather skip or reschedule a meeting. Showing up is so powerful. Finally, let me invite you to listen to others. Listen to people who have the jobs you want or are further along on their path than you are. Listen to what they have done right, where they turn to for learning, and who they network with. Ask questions to learn more about what they did right and what advice they might give to someone following in their footsteps. Listen to hiring managers, recruiters, leaders, and HR. They might not have a technical background, but they see how upward mobility in an organization happens. They are involved in interviews and promotions and their insight might help you move forward. I find a lot of inspiration listening to other people's stories. One thing to remember is that your path may be unusual. Mine sure has been. I still encourage you to make a plan at this level of detail. Just remember to stay flexible and learn from others. If nothing else, your plan will give you direction and hope as you move forward through some of the difficult times in your career.

Four Keys to Career Success
There are four common themes you should get from this course. I want to take a few minutes to highlight them and dig into each one from a different angle. They are experience, education, relationships, and communication. I want you to be intentional about how you approach each of these as they relate to your career plans. Let's start with experience. Questions that help you figure out what your experience has been and what experience you might need include what have you done that will help you later in your career? What can you do right now or in the future to add relevant experiences to your list? What experiences are needed for a particular role? What experiences will help you prepare for another role or give you an advantage in other roles? What experiences have helped others get the roles they have here are questions regarding your education? What education is needed for each of the rolls along your path? Are there formal educational needs? What licenses or certifications would help you? How could you quantify your self‑study to show you are a constant learner? What could you teach others as part of your educational journey? Questions regarding your relationships or networking include who has the jobs you want in the organizations you want to work at that you should get to know? Who can help you network into those people? Who can you help network towards their career goals? What networking introductions can you make for others? Who should know about you? Regarding communication, I want you to effectively communicate what you need to know about yourself. This is also known as personal branding. Here are some ideas. Networking and your personal brand go hand in hand. Figure out what you want others to know about you and who should know those things. Create a tagline or a very short branding statement. This can be used in multiple places, including your social media bios. I talk about this in my personal branding course. You want to figure out stories that help communicate your professional breadth and depth. In the personal branding course, I walk you through creating many stories. These can come in handy in various conversations, including interviews and networking. One of my favorite videos has Elon Musk responding to a question about figuring out who really has the technical skills he needs. Elon said he asks a candidate how they solved a problem and details about the problem and solution. He says it becomes clear whether they were heavily involved in the problem or they were just on the sidelines while others fixed the problem. Learn to communicate your transferable skills. Draw on related experiences to say something like I don't have exactly what you're asking for, however, I did have this experience, which is pretty close. These are my four keys to your career success. Did you catch the word I used a few minutes ago, intentional? I want you to be intentional about your career plans and the actions you take to carry out your plans. You'll find these four keys to your success will be important throughout your career.

Building Your Path in a SMART Way
The great thing about defining your plan is that you end up with a list of things to work on. You can visualize a methodical path forward. Your plan could help you make better career decisions. On the other hand, this same list can feel overwhelming. Even if it feels a bit overwhelming, create a plan where you can see the steps along your path towards progress. Working backwards helps identify those steps, putting them in a logical sequence. I've found the SMART goals model to be helpful when defining what each of these steps entail. You've probably heard of SMART goals. We'll do a quick review, walking through an example so you know how to apply this concept to your own plan. If you have a different model you use to work on your goals, that's fine. Otherwise, creating SMART goals will be a great start. Let's go back to Daniel who has identified a certain certification he needs to work on in order to move forward with his career plans. Daniel uses SMART goals to define a successful completion of this goal. The first letter, S, stands for specific. Instead of saying I'm going to get a certification, Daniel would say the name of the certification. Seems obvious, but many times our goals are ambiguous, which is not as good as being specific. M is for measurable. When Daniel writes this goal, he puts some measurement on it. For this goal, it could be that he passes the test, which is different than just studying for the exam. Usually, measurable results in a yes or a no, a 1 or a 0. The A stands for achievable. Create goals you can actually achieve. I know this sounds weird, but I have heard plenty of goals that are dreams and wishes, but not achievable. If you continually create goals that are not achievable, you risk losing confidence in your ability to ever hit your goals. If Daniel says he'll get the certification by next week, but he hasn't studied, doesn't know enough about the topic, and doesn't have the money for it, this is an unachievable goal. A more achievable goal might be to put in 40 hours of study in the next month. R is for relevant. A goal to climb a mountain might be fun, but as far as helping Daniel with his career plans, it seems irrelevant. Now, if we're talking about health goals, then yes, it would be relevant. When your goals are aligned with your overall objectives, they are relevant. I think of T as time bound, although some people say it is timely. Going with time bound, Daniel thinks there might be an opening he wants to apply for in six months, and having this certification could give him an advantage. So he needs to earn this certification within six months. In defining your goals, include specific times to achieve them. You don't need to write all of your goals with these five considerations, but I've found I naturally try to define my goals more explicitly, which helps me work on them more purposefully. When you're ready and serious about each of your goals, the more you define, the better you can accomplish them. The SMART model helps ensure you're working on the right things at the right times.

The Reality of the Path
By this point, you may be overwhelmed with the things we've talked about, making a bunch of lists, prioritizing them, being detailed, thinking about all the work you'll need to do for the next few years or decades, it can really be a lot. There's no doubt, there will be a lot of work involved. When I think about huge, long‑term projects, I think about the old question, how do you eat an elephant? The answer is, of course, one bite at a time. I want you to create an awesome plan, but just respect and honor the reality that it can take years of work to see the progress you're making. Start the huge process with one bite at a time or one step at a time and just make good, consistent progress. This is your career path. Nobody else is going to do this for you. You can't outsource it. Nobody else should care about it as much as you should care about it. You'll work on this for many years. That's the reality of your career path. But I don't want you to be overwhelmed. I hope you'll be excited. Let me share a story about being overwhelmed. A few years ago I was finishing construction of my basement. I got to the point where it was time to paint the ceiling and walls. By this point, I had done a lot of work and was tired of being in my basement. Out of all the jobs involved in finishing a basement, painting is one of my least favorite. It's messy and needs prep and cleanup time. Somehow, I'm good at letting drips sit on the walls to dry. Anyway, I spent a lot of time getting ready to paint. I got the paint out, I got all of my equipment, I taped things off that needed to be taped off, I walked around and around making sure everything was just right. What I hadn't done was start painting. Finally, I got to the point where I said, okay, it's time. I need to get the first roll of paint on the wall, and that's what I did. I picked up my roller, got paint on it, and made the first line with my roller. Once started, I was unstoppable. I didn't need to do anything else except finish that wall and then the next wall and then the next wall. My point is, we can plan and talk and dream and think a lot about these things, but we really need to pick up the paint roller and just start that first roll. Right now is the time to get to work on executing your vision.

The Rules of Getting a Job
On the internet, you'll find plenty of articles and blog posts that talk about the rules involved in getting your next job. Most of the titles are clickbait, meaning you think you are getting a short list of definitive, critical rules, but the article doesn't have a lot of substance. I'm going to take a different approach. Let me present two types of rules for landing your next job. The first type is the set of obvious, logical rules. The spoken rules to get a job or a promotion include finding open opportunities, applying for the job, and hoping to get an interview. Of course, great interviewing skills and salary negotiation might lead to a job offer. It's a pretty logical, linear process, but it's not the way everyone finds a job. I've been in the job search space since 2006 and I've heard of many paths to finding a job or getting a promotion that are way outside of the spoken rules, which brings us to the other type of rules for landing your next job, the fuzzy rules. I think most of us know what these rules are, but they seem harder and sometimes more uncomfortable than the spoken rules. It's easy to second guess whether what we are doing is actually a good use of our time and it's harder to measure the effectiveness of what we're doing. The fuzzy rules involve networking, personal branding, and effective communication. Networking can be scary. Personal branding can feel self‑aggrandizing. I remember feeling it was a lot easier to measure my success as a job seeker. When I could say I had applied to three jobs in a day, that seemed like I was getting closer to my next offer, but saying I had talked to three people in a day, I might feel good about those conversations, but it was really hard to know if that was getting me closer to an offer. After more than a decade immersed in this space, here's what I've learned. Don't underestimate either set of rules. How you find your next job or why you get your next promotion might surprise you. I've heard stories of how people find jobs, and there are many roads that lead to career success. For example, I had lunch with a programmer who landed a really cool job at an amazing company. I asked him how he got such a great job. Expecting to hear he networked in, that's the way I heard all great jobs were found, he surprised me when he said, well, I found the job on a job board, applied online, and they called me in for an interview. Then, they offered me the job. Experts would have told him to network in, but he got this amazing job doing things people say are ineffective. The reality is, I don't know, you don't know how you're going to get your next job or promotion. It might be through a lot of networking. It might be because your brand is so well known that people call you up and say, hey, we have an opportunity and we need you on our team. Or, you might find yourself applying to jobs and getting interviews. There are pros and cons to all job search tactics. You need to figure out what works best for you, your circumstances, where you live, the types of companies and jobs you're interested in, and then create a custom job search strategy that works best for you.

Mentoring Relationships
I've found mentoring to be a critical part of my career over the years. Mentors can help you think bigger, move forward, and get unstuck. I'm talking about having your own mentors, as well as being a mentor for others. Here are a few thoughts regarding mentors for your career progression. First, recognize the difference between formal mentoring, where your mentor agrees to a mentoring relationship, and informal mentoring, where they likely don't know they are a mentor to you. I've had both types of mentoring relationships, and both are valuable. Both have pros and cons. With formal mentoring, there's more responsibility by both parties, and you should have metrics to track progress based on objectives you talked about. An informal relationship could be much more forgiving and easily end since there aren't any formal expectations of the mentor. If you get busy with other things, that is okay. Informal mentoring is a great opportunity to learn and grow without worrying about the obligations set forth in a formal mentoring relationship. Second, your mentoring relationships can regularly change. Each mentoring relationship starts with a purpose. When your needs or circumstances change, when the purpose shifts, it's okay to change the relationship. Conversations can change to focus on what's most important. It might make sense to end the mentoring relationship or meet more or less frequently. I've been mentoring a colleague through writing a book, and we've shifted the conversation and our focus multiple times as they've moved through different stages of writing a book. The shifting can feel weird, but as long as you recognize it can happen and shifts can be okay, you should be fine. Third, you can have multiple mentors at the same time. I have different mentors for different parts of my life and career. I have mentors who excel in very specific areas and mentors who are more general purpose. I have a mentor for my finances, my relationships, my businesses, a mentor for my home technology. I think you see where I'm going. There isn't one person who can give me all of the mentoring I need. I'd rather get the best mentoring I could from specialists than have one mentor who is excellent at one thing, but mediocre at others. If you want to be a CIO or CTO in 10 years, you would find mentors to help you at different stages of those 10 years. You'll find mentors with different specialties, such as continuing education, those who specialize in emerging technologies, emotional intelligence, soft skills, business strategy, business operations, whatever you need to grow to the next level. Don't expect one mentor to be everything for you. I created two courses on Pluralsight for mentoring. One is How to be a Great Mentee, the other is How to be a Great Mentor. In those courses, you'll learn, among other things, how to define expectations each party has, how to set and work towards goals, establishing the rules of the relationship, and communication considerations in a mentoring relationship. If you're ready to get serious about mentoring, check out those courses.

Actively Monitoring Opportunities
A few years ago, I was at lunch with a friend. I was surprised that this person, an executive at a thriving company who already had a great career with a promising future, told me he received daily email alerts of job openings. More than surprised, I was shocked. Why did someone who had a great job at a growing company get daily emails of openings? I asked him why, considering most people see these emails as spam and annoying. He said, I just want to know what's out there. Of course, I'm heavily involved in the career and job search space, so it made sense to me, but this was the first time someone admitted they were that proactive about their career management. I would like you to think about actively monitoring opportunities. Here are some thoughts on doing this. First, make your path public. When people know you want a certain job title or role, they are in a better position to help you find it. They might hear about openings you don't know about or have relationships with people you should be introduced to. I know it can feel uncomfortable sharing your career goals, but once you figure out what to share and who to share it with, you might find real value in allowing your network to help you. How do you make your path public? You can easily do this by saying, I'm looking for, and explain what you're looking for. People can best help you if they know what you're working towards. If they don't know what you're looking for, they won't know how they can help you or what introductions would be valuable to you. Speaking of introductions, I'm a fan of networking as a career management tactic. You might ask for introductions with these questions. Do you know anyone who works in, and then say the specific company, department or industry you're thinking of, or, do you know anyone who could introduce me to, and then say a specific person or type of manager, perhaps based on job titles. Monitoring opportunities can be easy with technology, like job boards and news feeds, and by networking with others. While working on this course, I asked my friend about his strategy. With his permission, I'll share what he sent me. He said, Jason, I'm the only person who can plan and execute my career and take that responsibility very seriously. I hope you take your responsibility to plan and execute your career very seriously. He continues, as part of my career plan, I've added continual interviewing, even when I'm happily employed. This is so profound. Interviewing when you're happily employed? I think this is smart for a few reasons. It gives you opportunities to practice interviewing, which isn't something that comes natural to many of us. It also gets your name and brand into different companies, departments, and to people you probably should network with, but haven't. Learning what other organizations are looking for can help you understand what skills and abilities you should work on to stay current and relevant. I know it will take work and could be uncomfortable, but this is proactive career management. My friend wrote, I have two guiding principles. First, I will only interview for a company or role I might seriously consider. Second, I limit interviews to no more than three per year to force me to seriously consider companies and roles and avoid wasting my time. He then shared the four reasons for this interviewing strategy. First, he writes, this forces me to think about where I am in my career and keep my goals top of mind. Second, this forces me to continually update my resume and freshen my interviewing skills. Third, this gives me perspective in my current role and company. And finally, he says, this builds my professional network by meeting new leaders, as well as help others find positions I've decided to forego. I love it when people take the same strategic and methodical approach they have in their work to their career management. Whether or not you adopt his ideas on interviewing, even when you aren't looking, I encourage you to be strategic and purposeful while executing on your career plans and become more aware of opportunities.

Career Management and Diets
Can I spend a few minutes drawing a correlation between career management and diets? I'm sure you have either tried or know someone who has tried an extreme diet. One of the hardest, most extreme I've heard of is the cabbage soup diet. For weeks, maybe months, all you eat is cabbage soup. I'm not advocating that, by the way. I know someone who did it decades ago and they still can't stand to eat cabbage. A more moderate approach might be called a lifestyle diet where you are careful about what you eat. You have boundaries, but they aren't so strict that messing up ruins your diet. Lifestyle diets are sustainable over time with plenty of forgiveness. As opposed to going to extremes, it is a realistic diet. I don't want you to watch this course or any career course on Pluralsight and go to an extreme where you get burned out and then stop doing it. Instead, I want you to think about how to approach these things in a real and sustainable way. I work with job seekers who are heavy into networking, but as soon as they land a job they stop networking. It's almost as if they vow to never network again. It feels painful, uncomfortable, so they only do it when they have to do it. I don't want you to think that if you take a break from career management tactics you have ruined your career or harmed your plans. If you, as they say in dieting, fall off the wagon, it's okay. You can start and stop whenever. Stopping for a while might not be the best, but you can pick these tactics up any time. When you have a real and sustainable plan, a plan that is forgiving when you don't have time or energy to do things for your career, it is okay. Just like a diet that allows a cheat meal or a cheat day, your career plans can be put on pause. Instead of feeling bad about it, just pick up from where you left off. After you take a break from your career plans, try to avoid the trap of, I'll start this next week or I'll start this on January 1st. There's no bad or wrong time to start working on your career plan. Why not start today, right now? There are probably 20 specific tactics I've mentioned in these first two modules. Or, pick any hard or soft skill that will help you move towards your objectives and work on that. One of my favorite quotes is from my friend, small business coach Mark LeBlanc. Mark says, consistency trumps commitment. We might be committed to doing something, but until we consistently do things, even if it's just one thing every day, we're not going to make the progress we need to make. I invite you to create a career management plan with a vision that is realistic, sustainable, and something you can start working on right now. Do a little more every day, and if you take time off, quickly move forward and get back on track. This is a long game strategy.

Summary
In this module, we talked about things to help you move forward with your career plans. We talked about identifying ideal target jobs and visualizing your journey. We talked about breaking down your vision to help you create an actionable plan you can work on and to guide you through decisions that will come your way throughout your career. We talked about critical components to help you succeed in your career and make sure you create realistic, achievable goals. We talked about the rules of getting a job, mentoring relationships, and keeping tabs on opportunities. We ended with comparing career management tactics to diets. In the next module, we'll talk about job satisfaction and finding real happiness in your career. Let's go.

Realizing Career Happiness
Introduction
In this module, we talk about this elusive idea of happiness in our careers. During high school, I worked summers at a big organization and commuted with people who only talked about retiring, even though that was decades away for them. It was discouraging to never hear them talk about any kind of job satisfaction. At HR conferences, employee satisfaction is a big topic. As I've dug deeper into employee satisfaction, I've learned how satisfaction and happiness at work lead to higher performance, better retention, and even a stronger employer brand. These are things your employer is concerned about. I want you to intentionally think about your own satisfaction and happiness at work too. Let's get started.

Daniel the CIO
Let's fast forward through Daniel's career. He created his career vision, and even though everything didn't go as planned, he finally became a CIO. As we say, he has arrived. Daniel found the good things about being a CIO were just what he thought. He got a bigger salary and learned about executive compensation. He had more decision making power with technologies his organization would use, direction of the tech strategy and vision, and autonomy to build his team. He also got more recognition since his role was more visible. He enjoyed these and other perks. These were things Daniel thought he wanted. Of course, there were things he didn't anticipate. Daniel found the CIO job was not as easy as he thought it would be. There were big decisions he needed to make that would have deep, lasting impacts. Choosing the wrong technology could put products and internal systems on a path to failure. Keeping certain people on his team or not investing in the right people could negatively impact the team and organizational culture. Daniel has learned more about his employee's personal issues than he wanted and found it's different and more delicate than he had thought. As CIO, Daniel has found himself in a place where he has to deal with bureaucracy and office politics in a way he never imagined. Daniel didn't realize he would miss being so hands on with technology. His new duties and responsibilities had him in a lot of meetings and he could feel his tech skills getting rusty. Even with these new realizations, he loves his new role. Being CIO is not everything he thought it would be, and definitely not as easy as he imagined, but he loves most of it. He loves the challenges and the opportunities he has to impact organizational success and people on his team. During the emotional roller coaster he's been on since he landed this role, he's thought a lot about employee satisfaction. It keeps coming up in meetings with other executives and HR. He's thought about his own employee satisfaction and how individuals on his team feel. During the rest of this course, we'll discuss things he's learned about employee satisfaction and happiness because these things have real impact on performance.

Happiness, Joy, and Satisfaction
Back in 2006 when I started my company, people would ask me if I was happy. I had chosen to stop looking for a job and try my hand at being an entrepreneur. It was definitely an intense change. The first time someone asked if I was happy, I had to think about it. Indeed, I was happy, but I had some unsettling feelings I didn't understand. Finally, I figured it out. I was very happy, I just wasn't satisfied. Thinking about being happy, but not satisfied, even fulfilled, was eye opening. It was even empowering. I started an intentional journey thinking about my own happiness, even when I wanted more. I felt like I had more to give, more to learn, and more to earn. Instead of thinking I'll be happy when, when I finished school or when I got a certain job, title or income, I realized I could be happy along the journey. It's hard to come up with clear definitions of joy and happiness. Too often you'll see joy and happiness used interchangeably. I'd like to try to make some important distinctions between the two because I think this can help put your career satisfaction into perspective. One of the best definitions of happiness I've found was in an article by Phoebe Charn. On the Coach Campus website she said, happiness tends to be externally triggered and is based on other people, places, thoughts, and events. Contrast that with how she defines joy. She writes, joy is more consistent and cultivated internally. It comes when you make peace with who you are, why you are, and how you are. Because happiness comes from external things, it can come and go fairly quickly. Joy, coming from that internal place of self‑realization, can be more lasting and consistent, even enduring hardships and changes. What does this have to do with satisfaction and, specifically, job or career satisfaction? An online definition said, satisfaction is fulfillment of one's wishes, expectations or needs, or the pleasure derived from this. I would add that you can have satisfaction if you feel you are on the path to that fulfillment. Even though we tend to use joy, happiness, and satisfaction interchangeably, there is power in differentiating them and understanding that even when we are unhappy, we can still be satisfied and still have joy. Isn't that powerful? You can have an unhappy experience at work or with a colleague, but still enjoy your job and the path you are on. The question becomes, how can you become more intentional and honest about your own joy, happiness, and satisfaction? I invite you to think deeper about your own joy, happiness, and satisfaction and how you will endure along your journey. I've found the more intentional I am about it, the better my journey is.

Lessons from Booker T. Washington
I read a book that had a huge impact on the way I think about many things, including job satisfaction and happiness. The book, Up from Slavery, is Booker T. Washington's autobiography. Booker T. Washington was born into slavery in 1856. Through a series of events, he was able to escape the bonds of slavery and became very successful. His story is so inspirational. I invite you to read anything you can buy and about him. If you haven't read Up from Slavery yet, please put it on your reading list. I would like to share part of his story with you. Booker T. Washington had a special and unique opportunity to get a formal education. This was a really big deal, but in order to enroll he had to travel hundreds of miles by himself to get there. This was, for many reasons, a dangerous journey, especially for someone so young. By the time he got there, he was out of money, didn't have any food, and didn't really have presentable clothes. Under those circumstances, how in the world would he pay for his tuition and expenses? He convinced the headmaster of the school to let him work as the janitor in exchange for tuition, room, and board. He took his janitorial job very seriously. When the headmaster approved of this plan, Booker decided he was going to be the very best janitor he could be. He took immense pride in doing his job. As he tells his story, he talks about opportunities he had to do an excellent job and the recognition he received because of the way he did his job. He talked about promotions he got because he took his job seriously. Let's focus on a few ideas from his story. Sometimes we have an opportunity to do something. It might not be a glamorous opportunity, maybe it's not something we're aspiring towards. Nonetheless, we get an opportunity. Booker decided to be the very best at a job many of us would consider to be too menial. He could have easily just done what was required, checking tasks off a checklist, but that was not his nature. He took pride in his work and he made sure he did his job right. I've had experiences in my career where I could have just done the bare minimum and it would have been fine, but I was proud of my work and my output and I wanted to make sure my work was done right. Not only does this impact my brand or how others perceive me and my work, but it means I don't have to keep coming back to fix things I thought were done. You've probably had work in your career that maybe should have been done by someone at a lower pay grade than where you were. I've learned these are learning experiences. These opportunities have given me insight into different processes, products, tools, and teams. I try to do the best I can even when it is hard or boring. Interestingly, those hard and boring jobs have helped me later in my career, whether after receiving a promotion or on my entrepreneurial journey. I invite you to embrace opportunities, learn from them, do the best you can, and take pride in whatever role you have. These are the steps that make up our journey and prepare us for the future.

Changes to Joy, Happiness, and Satisfaction
I mentioned Daniel has been on an emotional roller coaster since he became CIO. Why would that be? It has been a career goal of his for years, and he finally made it. All his hard work has paid off. How can you work for years, even decades towards what you thought you wanted and still not realize the joy, happiness, and satisfaction you thought you'd have? A theme of this course is change, or fluidity. Our goals can change as we mature and as our circumstances change. What we thought we wanted 5 or 10 years ago might not matter as much now. These changes can come from within us. For example, you think you want to make a certain amount of money, maybe much more than you need to finance your life, but once you get there, you realize the tradeoff, perhaps of time or responsibilities you'd rather not worry about, are not worth it. I've talked to plenty of people who have found themselves in that situation and choose to go from a management role back to an individual contributor. They lose some of the things they had as manager, but they like being an individual contributor more. The extra money didn't make it worth it. I've seen this over the course of my career. When I was a student, having an extra $10 was very meaningful to me. As my finances have changed, that same $10 is less meaningful. I remember friends I had in school who celebrated a 10 cent per hour raise. To them, that was significant. I don't mean to downplay the value of money. My point is that as you make more or less money, the value can change. I've learned the hard way that working with colleagues I don't like or who have different value systems than I have can be immensely stressful. That stress can manifest in physical problems. I once found myself in an urgent care facility hooked up to heart monitoring wires, thinking I was having a heart attack. It turned out to be ulcer symptoms caused by stress I had because of someone I worked with. When I planned my career path, I never imagined being stressed out so much by certain people and how that would impact my path. I've since decided my mental and physical health are not negotiable when it comes to my career ambitions. If I'm in a situation where my mental and physical health are at risk, I'll adjust my ambitions and protect myself. Sounds pretty obvious, but when you look at the statistics related to employee satisfaction, it's unsettling to see how many people stay in jobs that are not good for them. I stayed because of loyalty and fear. Daniel has found in his new role that he is not having the joy, happiness or satisfaction he thought he would have. Because of the career he's had and the maturing he's done, he decides to evaluate what factors are hindering his satisfaction. It might be the responsibilities of his role, it could be the industry he's in, the people he works with or who he reports to. It could be the health of the company or any of the many other factors. As he understands what is impacting his feelings, he can make better decisions about his next steps. Don't let these changes shock you, rather expect them as you mature as a professional and learn about yourself. Allow your goals to evolve as you evolve.

Navigating Change
Since we've talked a lot about change and fluidity in this course, I want to talk about accepting and adjusting to change. In my first developer role, our company announced they were moving our office about 3 hours away. I wasn't planning on going, so I had the unique advantage of being a fly on the wall during this time. It was amazing to see lives that were thrown into chaos by this announcement, A lot of people, many more than I would have guessed, decided to forego the move and stay in the small town we were in. These were great jobs that would be hard to replace and a lot of people were sad. I was asked to create a section on our internet talking about change and change management. If change is inevitable, the question becomes, what can we do to adapt to change and weather the changes that come our way? I have a few ideas, but there's no shortage of books, podcasts, videos, and articles talking about change from many different angles. First, let me suggest you get really comfortable with change. I think I'm like most people, naturally change‑averse. I want to settle into something and enjoy that for a long time, but I've learned over many years I need to change my perspective on change. Instead of fearing it, I've learned to embrace it. Instead of looking at the disruption and discomfort, I look for opportunities and the good things that change presents. By no means am I suggesting this is easy. As I said, it has taken me many years to shift my first inclination, but simply working on anticipating, embracing, and looking forward to change has been instrumental in navigating a career that has been full of change. Once you have this new perspective, what do you do? Sometimes when change comes, you have to react in a way that is not your first choice. My friends at the company that moved across the state had to leave the company, changing their career plans, their retirement plans, even changing their work friends. If Daniel finds he doesn't like certain aspects of his job as CIO, he can leave it. Leaving your situation is always an option, although the repercussions can feel very expensive. Another option is to figure out how to work within the new changes, maybe adjusting your strategy and tactics. For example, what are specific things Daniel dislikes that he could change? If he dislikes the amount of administrative work he has, perhaps he hires an administrative assistant. If he dislikes some of the policies, perhaps he petitions to change the policy. If he dislikes the culture, he could work on changing the culture. Of course, some of these changes are easy fixes while others could take years. Maybe working on changes over years is the best answer. Another option is to do nothing. Maybe he's uncomfortable with certain things that are out of his comfort zone, but he considers the alternatives and realizes he actually has it pretty good, or his new role is yet another stepping stone along his journey and he needs to immerse himself for at least a couple of years before he takes the next step. Choosing to not make any changes, rather settle in and do the best job he can, is a legitimate and acceptable choice. He could take inspiration from Booker T. Washington and embrace his role and do the best he can while he's in that role. Benefits of doing this could include a strong professional brand and building respect amongst peers and colleagues. I imagine if he chooses this, he'd see a lot of personal and professional growth. When I've endured a role I didn't love, for sure there was discomfort. There was growth, there was working through the learning curve, and imposter syndrome. Every one of those roles prepared me for future roles in ways I didn't understand when I was going through them. My invitation to you is to embrace change and make the best of opportunities that come your way because of it.

Fulfillment through Purpose
My first real job after school was IT manager of a mid‑sized janitorial and building maintenance company. I loved this job. As the first IT manager, I had a huge impact on the tech strategy and operations. I had a lot of fun and I liked my colleagues. After I got laid off, I went through a miserable job search and then came up with the idea for JibberJobber. JibberJobber doesn't service companies, rather it helps people who are in a job search. I find a lot of my customers are in one of the most frustrating and stressful times of their life. I did not understand how different I would feel working with and helping job seekers. I loved my job at the janitorial and building maintenance company, but I don't remember ever going home thinking I was really impacting the world. Of course, that is noble and important work, but it wasn't until I worked with people who are at a very low point in their life that I felt an immense amount of fulfillment and pride in what I did. I felt like my work had a higher purpose than I had experienced before. I felt like I found my mission. Finding fulfillment and purpose is different for different people. For some, that might mean having opportunities to impact people. For others, fulfillment comes from changing technology or improving quality of life, or somehow making a difference in the world. When I have an opportunity to impact people, change technology, improve the quality of life or make a difference, I feel I have more purpose. I enjoy my work more. My why is more obvious and more of a driver of what I do. I have three examples of finding fulfillment through purpose. You may have heard of Ann Makosinski, also known as the flashlight girl. Ann was 15 when she made headlines about her awesome invention. She said she had a friend in the Philippines who was having trouble with her studies because when the sun went down there wasn't any light. Ann figured out a way to create light that was powered by thermal energy from human touch. Check out her story, it's all over the internet. Talk about finding fulfillment through changing the world. Richard Turere was a young boy when he figured out how to save cows, and maybe even people, from lions in his community in Kenya. Lions would regularly come to eat their animals at night. Richard tried a few solutions that didn't work, then he came up with an ingenuity idea that actually scared the lions away. His solution protected his community while not hurting the lions. This was such a brilliant idea that helped his and neighboring communities. Please look for his 6‑minute TED talk online. It's really a great story of someone who found fulfillment through purpose. William Kamkwamba, known as the boy who harnessed the wind, is another inventive young man in Africa. He was born in Malawi, which is to the south of Kenya. At 14, he figured out a way to generate electricity through a windmill he designed and built out of spare parts and scrap. Bringing electricity to the home made a significant impact on the villagers who now had access to light at night, as well as power for their radios. Watch his TED talk also. This is someone who found purpose and fulfillment from helping and inspiring countless others. I know I said I had three examples, but I want to share one more. I'm on some communication channels with other Pluralsight authors. Over the years, there have been many times where authors have expressed their delight in getting feedback from learners. When they, I should say when we, find out something in our courses has helped you in your career, perhaps getting a promotion or a new job, we are thrilled. It's so fulfilling to hear that something we put together was helpful. This adds to our resolve to make high‑quality content that can help others. Please take a moment after you finish this course to write down your why and how you get fulfillment. This might be one of the most important statements you come up with.

Job Bait-and-switch
The job bait‑and‑switch is when you get a role you think is one thing, and even was told it was that, but when you start the job you learn it's something different. I've talked to people who have had this bait‑and‑switch situation, and it's frustrating and confusing. I'm not going to suggest this happens because of sinister motives. I think this normally happens because of bad communication and sometimes poor management. Regardless of why it happens, which I'm sure is different across organizations and managers, I want to focus on what you can do if it happens to you. Here are three ideas on how to handle the job bait‑and‑switch. The first option, which is a strategy I'll almost always recommend, is to have an honest talk with your manager. Let them know about the discrepancy and what you thought the problem was and what you are finding it to be. This can be a kind, frank, and honest conversation to make sure you are both on the same page and remove assumptions. Your conversation should help set and manage future expectations. You should be able to figure out if this was a miscommunication or a mistake, allowing you to make an informed decision on your next step. During your conversation, you might realize they didn't know there was a discrepancy. Having an honest conversation can help you get to the root of the issue. The second option is to patiently work through the tasks assigned to you with the idea that you'll work your way into the job you thought you were getting This is a get‑it‑over‑with approach. I know when managers have a backlog of work they need done, they might stick you on it as part of your training and onboarding or just because you are the new person. If this was poorly communicated, it could be really confusing. I might recommend this strategy if you know you can work through this initial phase and soon get into the work you thought you were hired to do. Again, that frank conversation would really help you ascertain this. A third option, if you really are in a situation where your roles and responsibilities are different than what you expected and you don't see that changing, is to look for another job. If you feel comfortable, talk to your manager and ask if there are other options in the organization. This can be an honest, kind conversation. If there aren't options within your organization and you don't want to do the job you're in, I would suggest you immediately start looking for a job. Sometimes it makes sense to keep the job you're in while you're looking for another job, but you'll have to make that decision based on your circumstances. Supposedly, it's easier to find a job when you have a job as opposed to being an unemployed job seeker. If you choose this, do it in a wise and professional way. Having unexpected roles could be good. Evaluate the situation based on your career goals and other factors, including earning potential, the team and boss you'll have, etc. But sometimes, it just makes sense to find a job closer to what you want.

Techniques to Nurture Happiness
I talk to a lot of people who express frustration because they don't find all the happiness they want in their job. Gurus have said, you should only work in things that make you happy or that you love to do. Do that, they say, and you'll never work a day in your life. I love this idea, but I don't agree with it. I think many times we do things we don't love to do, but we do them because they finance our life and lifestyle outside of work. As I've counseled people, one of my messages is do work you can enjoy, but don't expect it to give you complete happiness. After hours, you can do your hobbies or spend time with friends and family, or whatever else really makes you happy. Having said that, I've already talked about enjoying the journey while you are on the journey. I don't want you to be miserable or resentful at work, and I'm intrigued by the idea that we can practice techniques to nurture real happiness. There's a great TED talk by Shawn Achor talking about training ourselves to realize more happiness. In his talk, Shawn shares five ideas to nurture happiness. Please go look for his TED talk and watch it. It's really good. Happiness is a skill we can learn about and improve on. The first technique is to list three things you're grateful for every day. When you do this, you train your brain to continually look for things to be grateful for. This reminds me of when I first started blogging many years ago. I thought I'd run out of things to write about, but after I got hooked on blogging, I found that every experience I had, whether at a store or on a support call, could become a blog post. I found blog posts in everything, the same way you could find gratitude in everything, if you're looking for it. Another technique Shawn recommends is to journal every day. He says you should write about a positive experience you've had over the last 24 hours. This conditions your brain to look for and recognize those positive things. I'll add that for many years, my blog was my journal and I found it to be very therapeutic. Another technique is to meditate. This is also a powerful therapeutic technique, and when you meditate with purpose, you can be more intentional about nurturing happiness. There are many other benefits of meditation. If you haven't considered it yet, let me strongly recommend it. The last technique I'll mention is to perform random acts of kindness. I love this suggestion because everyone around us could use any act of kindness. Out of the four techniques I'm mentioning, this is the one that will immediately and almost always benefit someone else. If you're looking for opportunities to be kind and act on ideas you have, you will make someone's day brighter. Looking for those opportunities will definitely have an impact on you. There are other techniques you could implement. Let me suggest you work on techniques to be happier as opposed to completely relying on your work to provide happiness for you. That's an unfair expectation, and why wait for them to make you happy when you can intentionally work on your own happiness?

Frank Talk About Depression
In this module, we've talked about joy, happiness, satisfaction, fulfillment, all those happy words. What happens when things don't work out and we deal with depression? Before I go on, I have to disclaim, I'm neither a doctor nor a therapist. I don't suffer from chronic depression, but I'm well aware of how debilitating it can be. My worst personal experience was during my failed job search in 2006. I didn't realize it at the time, but I was depressed and the decisions I made and the ways I acted were impacted by my depression. There's some chatter online about smiling or exercising your way out of a depression. You can eat healthier, do yoga, journal, and do other things. I love all of those remedies, but sometimes you need to visit a doctor or a therapist. Sometimes medication is what's most helpful. Other times, therapy is the best answer. I invite you to be open with the right people when dealing with depression and seek appropriate help. There is no shame in getting help. This is a serious issue that can impact not only joy and satisfaction, but relationships, work performance, just about everything in life. I've learned we aren't always going to be really happy. We have highs and we have lows. The lows are as okay as the highs are, but if you're stuck in lows or consistently lower than you want to be, please learn more about depression and yourself and get on a good path. Depression is a real issue. Depression can feel much bigger than we are and we can't always smile or exercise our way out of it. Please, get the help you need instead of just enduring through it.

Summary
In this module, we talked about Daniel getting the job he always wanted, but then wondering if he really wanted it. We talked about joy, happiness, and satisfaction. We talked about lessons learned from Booker T. Washington, navigating change, and finding fulfillment through purpose. We talked about what to do if you feel there was bait and switch in a new role and techniques to nurture happiness, and we had a brief, but frank discussion about depression. Now, it's time for you to get to work. Because this is a huge effort, something you'll work on for years, maybe even decades, remember to enjoy your journey. Please, reach out in the discussion area of this course and let me know how I can help you or how your journey is going.