= JIRA
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Learn JIRA with real-world examples (+Confluence bonus)

=== Section 1: Course Introduction

*JIRA - the 'What' & 'Why'*

Hey, guys, welcome back for some of you who are brand new to Gia. I just want to take a couple of minutes to introduce and talk about what JIRA is. If you're already familiar with all of that. Feel free to skip this video and head on to the next one where we'll talk about what Jiro version will be using in this course. But this shouldn't take too long. So what is Gia? Well, it's many things, *but I like to call it a work management tool that you can use to manage your projects, track issues, administer support*. I could go on and on, but it's essentially a part of a family of products made by Atlassian to help all kinds of teams manage their work. Atlassian is based out of Australia and have offices worldwide and is a publicly traded company. They're actually doing pretty well for themselves. So these are some of the products as part of Atlassian's family of tools. You can see that they are grouped into categories in terms of planning and tracking your work with JIRA or offering some kind of support service or help dissolution, coupled with incident management, or collaborating with your team members on work or content, and even having some development tools to help manage your source code and repositories. I'm not going to go into each one right now, but I encourage you to check out Atlassian's website to learn more about what each has to offer. In this course, we will be focusing on JIRA software and Confluence because both are very popular and go hand in hand. *Now, keep in mind, JIRA work management is for business teams, while JIRA Software is for software teams. But when you look at things like managing workflows, project boards issue types, all of that applies to both of them. It's just the agile methodology part of it that is specific to JIRA software*. But when you sign up for JIRA software, you also get JIRA work management. But to clarify, I will be focusing on the agile, specific functionality, and the course assumes we're managing software projects. Just know that the core concepts you learn around workflows and boards will apply to the business project templates available in work management. OK. So why go with you? First of all, I would argue that it is the number one project management tool out there with the comprehensive set of abilities that it has. I also like the fact that it focuses on helping agile teams manage software projects. In fact, I feel it is so comprehensive that companies now look for JIRA experience on resumes. But JIRA does have a steep learning curve and requires you to know what you're doing, especially if you're going to be the one managing it or even using it to manage teams. It's very customizable, and you even have countless add ons or apps to enhance the already existing functionality, but I'm guessing you already kind of knew most of this or else why would you be here, right? All right, so now let's talk about the different platforms and versions and what we will be using in this course.

*What Jira version we will use*

OK, so guys, Jira has different deployment types, we've got cloud server and data center. However, Atlassian has announced end of life for all their server based products by twenty twenty four. This doesn't concern you if you're not already on server. And we'll get into those details in just a bit. Now, regardless of which deployment side you're on, I recommend reviewing the entire course because the core concept between the different types are the same. You may only notice subtle UI differences. Now, when it comes to cloud, it is super easy to set up, just register your DuraSite site name and that's it. Atlassian sets up your entire site for you and going forward, you never have to worry about any maintenance work such as upgrades, security, scalability, all of that is managed and taken care of for you. But all of that comes with a subscription cost either on a monthly or annual basis. Server was probably the second most popular deployment type. But like I said, this is going away by 2020 for this setup required you to install in host cheer yourself on premise, either on a server in the office or in a data center or cloud server environment such as HWC or Azure. This is where you would be responsible for managing everything from upgrades, security, performance. But on the flip side, because it's locally installed, you have more power over customize ability. You have access to server logs that your database so you can run different queries to get the data, install custom code, things like that. But all of that did come with the headache of managing things yourself. So if your company is on Giris server, your options are to either migrate to JIRA Cloud or your data center, but definitely don't count on remaining on server after 20 24. And if you're brand new to Jira, chances are you'll be starting off on the cloud. So you can just take everything I said about your server and just pretend that didn't happen. There's no need to learn about it now that Atlassian is getting rid of it. Data Center is their third deployment type and is actually like server except on steroids. It's the same as server but at scale and is meant for enterprise level companies that are global and have thousands of users and have a requirement of uptime, high performance redundancy and things like that. So far it looks like Atlassian is going to keep their data center offering. *So it's basically going to come down to cloud versus data center*. But from all the events and webinars I've been to, especially recently, I've noticed Atlassian doing a massive push towards cloud and their server end of life announcement further validates that. So in this course, we will be using and focusing on Jira cloud only. OK, so now with respect to cloud, there are actually different versions of cloud. Believe it or not, there's now a free version of Geor Cloud. They once had this way back in the day, and then they did not have it for many years, but have now brought it back. So the free version gets you up to 10 users, but it misses some functionality in the form of advanced permissions and has limited automation and storage space and no support from Atlassian. You basically just have the community support available. Mind you, the Latino community is huge and their public forums are very active. The standard version is what we will be using in this course and is pretty much what Jira used to be before they gave out the free version, would your standard, your automation and storage limits are higher for up to 10 users? You have or I guess you only have to pay 10 bucks a month and you also get standard support from Atlassian whenever needed. The premium version has no restrictions on automation or storage. Well, there kind of is a restriction with automation, but it is so large that it's pretty much unlimited. They're guaranteed ninety nine point nine percent uptime offer premium support. And they have also included a bunch of other features, such as advanced roadmaps for project planning, admin insights, a cloud sandbox environment for you to test your JIRA config changes many things like that. I can definitely see the appeal in premium, but it is more expensive. I wish they also had a 10 user tier where you pay a fixed amount, just like we have Porgera standard. But that's not the case for premium. And you have to pay on a per user basis even if you have one single user. And no, there's actually an enterprise version of JIRA Cloud as well, which is basically everything you get with premium plus more. And the subtle difference here is that you can have unlimited instances of JIRA within your organization. You get Atlassian access, which is for centralising administration and user management. You can choose where your data is hosted in terms of geographical location, ninety nine point nine five percent uptime, 24/7 dedicated support, all that jazz. This plan is the newest of them all and actually requires you to contact Atlassian sales team for pricing, at least as of this recording. But clearly based on the features is really meant for those really big, large scale enterprise companies. So I invite you to check out the links have provided in the resources for more information on all these different cloud versions. So to confirm we will be using Giris standard on cloud. I know a lot of you will probably just sign up for the free version. Just keep in mind that some of the functionality I walk through in this course will not be available for you. But you do have the option of starting a standard free trial so that while you're learning, you have access to all the functionality. And I'll show you how to set all that up as well. In fact, we're almost there. Let me just do a quick walkthrough of the core structure, give you some tidbits, and then we'll set up our first cloud instant's.

*Course structure and tidbits*

Hey, guys, before we dive into actual content, I want to take another quick video and layout the land for the course. Explain the structure, give you some tidbits based on feedback I've received from students and end with a small favor to ask from you. In terms of the structure, JIRA software is heavily predicated on agile concepts. So I will be starting with a quick refresher on two agile frameworks, namely Scrum and Kanban and how they relate to JIRA. This section is going to be heavy on theory. So if you're already familiar with the frameworks and want to just get into JIRA, feel free to skip that section. Once we have the refresher, we will get into JIRA, and I've broken that up the same way that Atlassian's documentation is also organized. The first part looks at how JIRA is used by people working within an agile team, such as developers, designers, QA members and so on. Let's be honest, these guys are focused on getting stuff done, so that section will take the first dive into the JIRA interface and will focus on how you can work on issues, search for issues, navigate the various agile boards to update issues, and so on. By the way, if some of these terms are new to you right now, don't worry, we'll be going through them very soon. From there, we will take a step up into managing an agile team, either as a product owner or scrum master, and look at how JIRA is built for people taking on this kind of role. This section will focus primarily on managing agile boards, as well as the lifecycle of software projects from creating stories, managing sprints and tracking software releases. And then we will get into the customizable aspects of JIRA administration, which will show you the inner workings of JIRA and its features. In this section, one of the things we will be doing is walking through how all the features come together. There's a lot of content here, but after we're done, you'll essentially be able to think through how you would want to customize your own JIRA instance to suit your own team's needs. Now, I've also included a section on this relatively new type of project that Atlassian introduced called Next Gen or Team Manage projects that comes with its own advantages and benefits. So I thought it was important to cover from here on out. I have a bonus JIRA content section, either talking about new features introduced by JIRA or just a free for all not related to any specific topic in particular, but will include examples of how you can manage various scenarios using JIRA. And last but definitely not the least, I have a bonus confidence section, which is Atlassian's document or content management system, and that ties very well into JIRA and complements how teams can collaborate on projects and their associated content. OK, so now some coarse tidbits feel free to increase or reduce the speed of the videos using the options available in your video player in case you think my speed is too slow or too fast. This course caters to everyone beginners to experts. For someone that is more advanced, the intro stuff might appear a bit boring and slow, so feel free to skip to the sections that are relevant to you. And my apologies in advance for some of the longer videos in the course, I felt it wouldn't have been beneficial to cut certain topics just to make videos shorter. So you may run into some longer videos and similarly, with respect to the overall course length of actually receive feedback that the course is too long. Well, guys, this is a long course, and that's because of packed it with tons of information. JIRA is very comprehensive, and I've tried to capture a lot of features and tips and tricks. I honestly wouldn't want to make it shorter, and I made that decision in what I feel is in your best interest. Would you rather I split up the content into two courses and have you pay for each one? I didn't think so. I wanted to give you guys the best bang for your buck. And so my intent is to continue adding content that I feel will help you. You're not forced to review each and every video. So if you feel the course too long, just skip to the videos you feel are relevant and to get the core certificate at the end. You could just manually tick off the videos that weren't relevant to you. I hope you guys understand where I'm coming from. OK, so now in terms of UI differences, Atlassian is constantly and I mean constantly doing UI tweaks. And so there may be some subtle UI differences that you notice. It's impossible to keep on top of every single update and then rerecording videos. But I do my best. You'll notice some videos where I post tooltips to correct something that I might have said, or I've simply updated parts of videos. If you notice any change in the JIRA functionality or the user interface, feel free to let me know and I'll add that into my pipeline to update. And on that note, if you've got any feedback in general or have questions about the course content, feel free to post them in the Q&A section of the course or send me a direct message. All right now, I have a small favor to ask from you. Udemy is platform tends to ask you to leave a reading right at the beginning of the course. It's a bit confusing because students haven't even had a chance to get into the good stuff yet. So there are times where people might leave a bad review and talking like one or two stars with a comment saying, Well, I haven't learned anything in the first three videos of the numerous videos in the course, and that is completely expected. So guys, I would like to be completely transparent here and ask if you could maybe save your reviews for later in the course or whenever you feel you've gone through enough content to say something. You can either choose to review later or at the end. I rely on the standings of this course to keep it going, and that really drives and motivates me to make sure I'm keeping it updated. Responding to student questions promptly and adding new content on new features. But just to clarify if you want to leave a five star rating right off the bat, I would simply love that and nothing would make me happier. But if you're not there yet, just asking you to give the course a chance first and get through more content before posting an honest review. And as always, if you're unsatisfied with anything, feel free to reach out to me because I really value that feedback and I'm always working to make this course better for you.

