= Template
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== The Daily Journal - Habit of Successful People By Jawwad Siddiqui

=== Section 1: Welcome, Intro, & Overview

==== Welcome and Introduction

Welcome I'm excited to have you here and I hope you are just as excited! You have made a good investment in yourself by committing to learn a skill that is very common among successful people. And my role as your instructor is to help guide you along the way. Answer any questions you have to help you learn the skill of keeping a journal. Now let me start with my intro and why should I be your instructor too for keeping a journal. About about 10 years ago a decade ago. I got very curious as to what makes successful people successful. And when I started studying successful people like Nikola Tesla, Thomas Edison, Bill Gates and many more ... I started noticing this one habit that they all shared. They ALL kept a journal to make progress in their life. So I got very curious and OBSESSED as to how can I keep a journal to make progress in my life. Just like how these other successful people made progress in their life. *By doing that I was able to get high grades in school get scholarships and graduate with high grades*. (Pause) After that in for my career, *I was able to find a career that I truly enjoy as well as keep getting good at my skill and get promoted at my job. Furthermore it allowed me to do things in my spare time that I wouldn't have done otherwise. I started companies I started creating courses like these so I enjoy my spare time and get ahead in my career as well as my my other goals in life*. Today I am very excited to teach that skill to use so you can make progress in your life and now in the next video let me start off by giving you a course overview so you know what you were getting into and how is the course broken down. I will see you in the next video!

==== Course Overview - Hands-on Learning

Let's start by looking at how the Course is broken down the course is designed to be brief and hands on. So you have activities to do along the way. And actually practicing keeping a journal of yourself you won't be just watching videos. You will be watching videos but also doing activities at the same time. In part one we are going to understand the fundamentals of keeping a journal. *This will help you understand what the benefits of keeping a journal are and what are some of the disadvantages if you don't keep a journal*. Furthermore I will tell you this story of humans and how we used to writing to progress through our generation and how we should take lessons from that to progress in our personal life by keeping a journal. In part two we're going to start focusing on you the person behind the Journal. We're going to focus on some exercises that will help you understand your goals and motivations behind keeping a journal by you articulating these goals and motivations you are more likely to follow through with keeping a journal and develop this habit over time. I encourage you to pay attention because this will allow you to set goals for yourself and increase the chances of you keeping a journal. After this course and for many years to come. All right. And then in part three after having understood the fundamental theory of why you should keep a journal a little bit about yourself. In part three we're going to talk about the overview of keeping a journal to understand what journal keeping entails. What are the different options. How can you practice this habit. How often you should write and how can you use the journal keeping in your particular area of life. If you're a student teacher professor or an employee or a boss how can you use it to personalize it for your life. In Part 4 we're going to go get right into a step by step process of keeping a journal. We're going to start off with a template that allows you to follow through with how you should follow a specific structure daily or whichever frequency you want to keep a journal to articulate your goals to articulate your plans. So you can make progress in your life. I encourage you to follow along and practice this for quite some time so you can get to understand what a good structure for yourself is. Now in part 5 we're going to go over tips support and resources as to various questions you might have for keeping a journal and some additional advanced concepts that might help you in your journey of keeping a journal. With that overview I'm excited to have you and I'm excited to get started.

=== Section 2: Intro to the Daily Journal or Journal Keeping

==== Why keep a journal? History & Wisdom

Let me start with a bit of a history lesson a bit of context and background for you to understand why and how a journaling and writing was so important for a past civilization. Many years ago humans invented writing or journaling to better understand and control the many complexities they were facing such as as human population was growing their like. How do we keep track of who owes money to who versus when someone is traveling to another city. How do we tell them that they are another city on top of that. How do we pass knowledge from one generation to the other. Furthermore how do we write things down so we know how we can better organize ourself as communities tribes or or the communities that were forming around them. Now the lesson and the wisdom I want us to draw from this lesson from history is that you and I can use the same approach in our personal life as our lives get more complex and we have more goals and we need to organize ourselves. We can use the power and the benefits of journaling that I mentioned earlier to articulate ourselves and plan our personal and professional life now to help us do that. *I'm excited to take us to our next video in which we're going to focus on how you which I call the hero behind the journals can take some steps to understand your personal motivations your personal goals just like how our ancestors had their personal motivation and personal goals to invent writing and do journaling*. I want you to dig down deep within yourself to figure out your goals and motivations so you know why you want to keep a journal. So for for that I'm excited to see you in the next video.

==== 3 Big Benefits of Keeping a Journal

Now if you're not already convinced as to why you should keep a journal. Let me go over some mean benefits.

*Number one* keeping a journal helps you better articulate the problem or the situation at hand. For example if you're trying to tackle a big goal or a big challenge writing it down is going to help you articulate it so you can essentially make progress towards it. When you're articulate or when you understand the situation at hand you're more likely to make progress on your goal. *Our mind is a thinking machine. It is not. It is not a storage machine*. So use your journal as a storage or your hard drive. Whereas use your brain for thinking and once you use both of them in combination you can be better at articulating your goals and making progress.

*Number two* is it helps you relieve stress and feel more in control. So once you write things down when you use a journal you're going to be less stressed about making progress in life. And you can make you can you can use your energy to make progress about the things you have already written down.

*Number three* writing in your journal also makes it more likely that you will make take the steps to succeed or finish the goal that you have written down. Many times you just don't write down what we want to accomplish or don't organize our day. So it allows the journaling allows you to do all of that.

So in summary it allows you to be more articulate. It allows do to not allows you to not have as much stress and number two it allows you to be organized so you can make progress in your life. Now there is a lot there is many more benefits that I will attach in an article in the video notes. So please feel free to read that but I hope throughout this course as you make progress you get to experience these benefits for yourself.

=== Section 3: Focusing on YOU - Hero of the Journal

==== Focusing on YOU - Goals and Motivations for Keeping a Journal

Now we're going to spend some time on YOU. The author or (as I like to call it) the "Hero" of the journal! Knowing your goals and motivations will increase the chances that you will follow through with keeping a journal and improve your current journaling habit. Without these goals or motivations you might find yourself that you know days go by and you don't write in your journal or you haven't used the Journal to get ahead in your goals. Remember that journal is just a tool for you to help you accomplish those goals. So it's important for you to keep them front and center as you get good at keeping a journal or developing that habit. And as we discussed in previous videos some of the world's more successful people (like Einstein and Thomas Edison) knew their goals and motivation so they ended up using the Journal to get ahead in that. With that said I have a set of questions that you and I can go through to help you identify your goals and motivations. I encourage you to grab your pen and paper or your journal and answer these questions in your journal or you can download the digital document and answer it on your computer. So I'm looking forward to doing that with you in the next video. Thank you.


==== Guide to Identifying your "Why", Goals, and Motivations for Journal Keeping

Welcome to this section in which we're going to walk through the worksheet on your journal keeping goals and motivations. As a reminder, goals and motivations are like the fuel to your fire. These goals and motivations will make sure that you will continue keeping a journal and continue getting better at it! As we said earlier, the journal is just a tool for help before to help you accomplish your goals. ... So it's important to know your goals and motivations so you can see the value of keeping a journal. Now, the document you see in front of you on the screen is a one page simple document that will be available to you to download in many different ways. PDF and other formats that you can download and complete on your own! However, my recommended way of doing this is copying these four questions onto one page of the journal - just like how it looks on onto the screen just copy these questions and over the next few days try to answer them. Your first attempt should take 20 minutes don't overthink it and answer all these questions. Then take your time over a day or two and keep coming back to these questions every now and then. Until these questions almost become automatic or subconscious to you so copy this onto a one page and then answer these questions so you can better understand your goals and motivations for this tutorial and video we are going to complete this on this screen so it's better for you to follow along. One other resource document that might be also useful to you is I have linked to blog posts of other famous and successful journal keepers such as Thomas Edison and Einsteins of the world and you will be able to learn from their experience and get some inspiration for yourself. Now with that said let's get into answering some of these questions. The first question is really to help you identify why you want to keep a journal this should be approach very broadly. Think about your broad role that you have in life. For example. Start off by thinking about your role. So let's say if your role as a student could be a parent could be a career professional could be an entrepreneur and could be caretaker. Could be could be anything along those lines. So think about your role and then the second thing. Second thing is you know think about how you want to improve your role how you want to improve in that in that specific situation. So in this case how will the journal help you better your specific roles in this case if you're a student. Think about maybe you want to get better in school grades you want to accomplish more extra curricular activities you want to get better grades so you can graduate and get your dream job. Essentially you just think on a very high level on how a journal can help you accomplish that. Start from your role and then think about how the ideal future will look like for you. Don't set too specific goals such as I want to get ninety nine percent in my course or I want to make a million dollars. Or you one to take. I want to get a job promotion. Just think about more of a high level goals such as for a student. It could be I want to be better disciplined and improve my grades so I can get a better job or that I can get that scholarship for a career professional it could be something along the lines so I can continually learn and grow in my career and find more meaning in the work that I do. For entrepreneur or a caretaker it could be very much I want to constantly learn and grow so I can build products that add value to others in this case we're going to complete one for entrepreneurs. So as an entrepreneur as an entrepreneur I want to be able to create products that add value to others so that I can be a valuable member of society the Journal will help me organize reflect and plan this goal. Plan this. With that in mind you should have a really high level picture as to why you want to keep a journal and then you can move on to the second one here. I want you to think about what positive changes can a journal bring to your life. A good way to think about it is think about any bad habit you have you want to reduce such as procrastination discipline better focus. Maybe you don't know what your goals or motivations are in life. Maybe your health needs to be in a better place. Maybe you have some other bad habits with your anger or how you conduct yourself or how you keep in touch with friends. So really think about all the positive improvements you can bring and all the negative habits or things that you have noticed about yourself and write them down here and see how we can bring a change in your life. For example for me ability to reduce my procrastination by Rick estimation by my using the Journal to organize and plan my day another way it could be ability improve my personal health by better taking care of my mental thoughts and stress again I would encourage you to write as much as you can and again these are questions you should come back to and reflect on every now and then. Now in the third part is where you get started to think about very specific top priority goals. And then here is you can go back to your role and think about how can I have some very specific goals that will help me accomplish that. These goals should Dawn over overstress that these should not be all the goals that you have in your personal life. Just think about one or two or three. And again these goals will continue to change or continue to expand in their in their impact or scope as you go through life but just have this as a mini goal planning session and as you go through your journal keeping habit always come back to some of the goals that you have in mind so you can use the journal to help accomplish that. *For example one of the goals that I had is to better be grateful and thankful for all the things that I have all the blessings I have in life. I use the journal every now and then to remind myself of that*. So just have your specific goals here. Don't overthink it. Write some of them down and then come back to them every now and then and then again. Lastly the last section is just for you to write out your open thoughts. If you have any questions about any of your open thoughts you can reach out to us as journaling habit dot.com or Twitter Instagram or Facebook. Again this one page document will help you identify your specific goals and will help you keep focused on your journaling habit. I encourage you to take your time and reflect on these questions every now and then. And if you have any questions let me know. I will see you in the next section. Thank you and goodbye.

=== Section 4: Five-Step Breakdown of the Daily Journal Template

==== 1/5 Overview of the Daily Journal Entries

OK. Welcome back. Hopefully by now you have completed your exercise on identifying your soul which is the author of The Journal you know your motivations you know where it will help you get there and you know what will happen if you don't follow through. And if your life will change your world will change. So with all of that front and center I want you to keep that in mind because that's going to be your fuel as we go through the daily journal template. Also please grab a pen and a paper any journal any papers find and try to actually do what I'm teaching you heard in other words trying to complete a journal entry as in teaching you about these journals because the key is to just get started and improve it over time. So the first thing first I'm going to go over the whole template and then we're going to get into the specifics maybe in the next video. So the *first part* of the daily called daily quote essentially gives you not only the inspiration but it is essentially It packs a whole lot of lessons in just a few sentences. And if you know the author of the quote it's even better to write that code because you have a personal attachment with the author. And you know the other story has was you know with you know where the chord is coming from. *The next part* is this is called a five minute journal entry and this is really there to psychologically make you appreciate things in your life because we usually don't go back and appreciate the small things that happen. It allows you to have daily affirmations. Affirmations are something that you remind yourself off that hey this is my purpose this is my values this is how I operate. *And then it allows you to capture good things about your life and even the things you want to improve in a way where maximize your daily satisfaction because if you're daily satisfied those daily satisfaction is going to accumulate to bigger goals and bigger accomplishments later down the road*. So it's really important this section is one of my favorite sections and I completed every day in the morning. So in the morning I wake up I read the daily quote Every day the five minute journal entry I write my goals and then I get started and the rest of the journal is filled as I go throughout the day. So now the next section is called outcome goals for the day and the reason is called Auchan gold. I'm going to get into that later. *It's not really about what you want to do. It's more about what you want to accomplish* at the last party. You know if you have other noteworthy for example something you know about the day some quick time such as you buy milk bread or other things that are just not really our goals you can write them in the other note section which is which is right here. *And then you will also see a target completion time which is right in front of your goals. This is actually really key*. *You should write down how long is it going to take you to complete something*. So for example here I've been to it's going to take me to put my goals forward or Essentially it will take me 25 plus 25 50 minutes and I should be done by done this in 15 minutes and then I move on to the next 10 next task. At the end of the day this is before sleeping you do a quick productivity score you analyze your day OK how do they go what do they do. What did I didn't do. And you do this by asking yourself six trigger questions.

*The first few questions are actually very important do ask yourself at the end of the day because they help you identify if your beliefs and behaviors are aligning.* You know the fact of the matter is most of us will have to get better in shape get you know get through better in our careers. We have a good relationship there with our choices having more time but very few of us have the behavior to support our beliefs and wishes. So this helps you do that. And I just want to highlight that all of this process should take you roughly. I mean I spend less than 10 15 minutes in total in a day to write in my journal and that's almost nothing. But just to keep in mind don't get overwhelmed. This is something you do very quickly and once you get into the habit it's going to be a lot a lot easier. So in the next video we'll get into the how and where you quote and how great the each part of the journal. So I'll see you then.

==== 2/5 Writing Empowering Daily Quotes

OK. So let's get into the first part of our journal which is the daily quotes part and we do this first thing in the morning when you wake up before you go to work before you do any other rituals. I usually do this as the first thing I do in the morning and this is how you do it. You know selecting any chord is easy because the whole world is bombarded with chords. But you have to keep in mind the quotes to select a good quote it has to follow two criteria and if follow these two criteria as myself. The chords must resonate with me in other words I must resonate with the context with the author and the really the way I do that is you must know the author of the quote. Now you may be thinking oh I don't really know many authors. The best example to start from is start from your family your parents your grandparents they have taught you values or they've given you quotes that you can write down to remind yourself about how you should conduct that day. For example in the early and the early years I used to a Dunkers from my father my mother my mentors my teachers because they were the closest to me. They gave me personalized recommendation and their quote would be powerful for me to write before beginning the day because they know my abilities better then maybe when I don't or when I don't have confidence in myself. So we quote on someone you know about and something that resonates with you. And just for your information this is how I do it. No I haven't ever no document in which I quote saved over like four or five years. I'm just going to add I selective quoting the right dumb. For example you know if I wake up in the morning with my heroes which is I have a journal you can look into it if you want to on my blog but I will go into my hero Journal look at my heroes and say OK which one do I want. Which one do I want for two days. For example this is day before yesterday I chose someone from the Navy SEALs and this was like OK under pressure you don't rise to the occasion you sink to the level of your training and that's why we train so hard. So the good thing about here is that I know the author I know the Navy SEALs So this resonates with me and if I write you down I'm going to be able to hold myself too accountable to this code as I go through the day. OK so that's how you read the daily quote in the next video I'm going to get into how to do the five minute Journal which will allow you to maximize your satisfaction and notice small things on a day to day basis that will insure you you feel fulfilled meaningful and progressing towards your goals.

==== 3/5 How to be Thankful - Grateful, Affirmations, and Improving

All right so we're done the quote's part. We're not going to get into the five minute journal entry. *This is the entry that tells you to appreciate small things on a daily basis. Remind yourself what your values are how you're going to operate regardless of what say. I said all good times or bad times and what you will do to improve yourself. Baby steps every single day*. So let's get into that. And I will explain to you how it goes. So the five minute Journal is composed of three to three separate things. Actually four separate things you can see here. Are you using small abbreviations. So the way I start is I say three things I'm grateful for. So take three things I'm grateful for I would write it. For example I'm going to do a sample interview with you right. I will do it for today. As of today for example something I'm grateful for let me just zoom in so you can see clearly. First thing I'm grateful for is to the first so the three things you have to write three things. First thing has to do first thing has to be a person. This has to be a person people a person and preferably like an old person not someone really new. So you can appreciate them. So for example I have a buddy named Jim. He's been my mentor for a long period of time. And I will write I will write I appreciate him as a mentor because he has been in my life for three years. As a mentor. So I will. This is exactly what I would write in my journal. I would write Jim being a mentor. Right. You know you don't have to read the whole story but if you just write the name and write the gist of it you can understand that. And the second thing that's being a sighted person is you have to write like one thing that you really appreciated yesterday or today like something nice that really happened or something around you that you really truly appreciate really something small that you wanted to address on a daily basis for example or something that comes to mind is for example yesterday when I was on the train I helped someone who spilled coffee I gave them a napkin something to write things like OK so in my eyes I can appreciate small things or events. Sogard right. Helping a lady with coffee still and the last one is actually evoked an opportunity that you have today that you that you may like you know overlook or don't want really appreciate read for example opportunity you have today. So for example something that I wrote this morning is my my opportunity I have two opportunity I have to maximize my health. I'm you know I'm 23 years old. I had the opportunity to maximize my health. Take good care of my diet. Take good care of my exercise so I can write that down. So that is your That's the first part two things you're grateful for. Now you know three things three daily affirmations these are things that remain constant day to day basis. But you remind yourself what is your daily affirmation. For example some of my daily affirmations are totally committed. In other words every day regardless of the task at hand I'm going to get up and I'm going to get the work done regardless of how difficult it is. Yes. I'm compassionate. In other words you know you don't you can't be a mean boss or you can be a mean friend you have to have compassion so you understand the other person. And this last one is I'm focused. So if the task at hand needs to get done I'm going to be focused on getting it done and I won't get distracted again. This doesn't mean that I'm superhuman I'm always focused. But you at least remind yourself that these are my affirmations. We try to live by them as much as I can. All right. And then these are the two things that you actually did two things you actually feel love at the end of the day. So these these these two you fill up at the beginning of the day. So start of the start of day not the day. And this one is start of day to start day. This one is and end of the day. And this is and. OK so let's pretend I came. I was at the end of the day I would write feeling amazing things that happen to me I would say my old friend met an old friend to help my parents food and dishes and something even like the goal of this party is really to appreciate small things that happen every day. You can't expect yourself to become become like a superhuman every day. That once you start appreciating the small things you realize that there's something to appreciate about every single day. Sometimes you may not have all three. Even if it's one or two just write them down. But I've noticed if you really try and find it there's always more than three things to appreciate in it. Some man an old friend help someone at the gym you know and you know call all the French Jewish Happy working. That's something actually I did every birthday yesterday. And three things to do better tomorrow. This is usually you know if you noticed something throughout the day that I'm not focusing properly you can say not to browse Facebook not to browse Facebook knowing and knowing the way not to eat on time to eat on time and things like that so quickly you're able you know you quickly jot these things down in your daily journal and by completing this section the first one is in the morning you really get into a good mindset at night. And you know what I want to have this read good read usually symbolizes something evil. So I'm going to make this book. So once you do the first two these two parts in the morning you get yourself into a positive mindset. Once you do these two things afterwards you appreciate the day. If you do this day in and day out you realize you appreciate every single day you're you know you're psychologically optimized to do the best thing that day possible. And regardless of how [REMOVED] or crappy that day might have been you always find something to appreciate from it. So that's the five minute deal that a daily journal part. And then the next one we're going to get into how to set the ultimate goals. So I'll see you in the next video.

==== 4/5 Write Goals that Move You!

OK so we're done the daily art part done the fighting minute journal entry. Now let's get into the outcome goals outcome goals are essentially what you want to accomplish not necessarily what you want to do. For example let me give you an example. If you want to send someone an email to say you want to send him an email that is really a task but what are you trying to accomplish with that email for example you want Jim to tell you yes or no for a project that you want him to complete. That is really the outcome right. So once you make that OK I want him to tell me yes or no. Then you can come up with ways to get that yes or no faster than an email for example you may realize if I just give him a call and ask him I mean get done earlier. Or if I just go and visit him while I'm buying milk for the day I can just tell him to do that or get an answer then. So in other words the goal is to what you want to do not necessarily the tasks of focus on the outcome not the task. And this part is it is this part of several journal entry for this one is usually looks like this. So first you first specify the first you say the outcome so say outcome outcome then the second part is purpose. Purpose is actually key I'm going to go into it. Why. And then the third part is just to find like you know exactly what you're going to do. So if you take the example of Jame outcome is I want I want to know yes or no. The din is available to help me on project x ray let's just say that that is the outcome and the purpose is something that is very Keeva should be Why do you want to do this and this should be something that truly speaks to you speaks to you in a prayer. Is that what will this mean if it gets done right. So the purpose for me is I give up a purpose for me and it will help me it will help me finish the project which is tied to my career success. So you just have added a lot more meaning to getting that outcome done. And once you have that purpose in mind you are a lot more motivated to get that outcome were that planned out. So again here you may decide you go OK you know what I'm going to email him and email him or call him or even visit him. So whatever you decide I can just write it here and get it done. So the goal again here is focus on the outcome then the purpose and then go with the plan. So here I have a quick exercise for you to come up with the come up with the outcome purpose and the plan so you can read all these and you can come up with your outcome purpose and plan for each of your if each of your day I try to get almost let's say two three or maximum four all comes down each day because if you focus on outcomes you can get a lot done. On a typical day and this last part of getting outcomes or goals is the time constraint that is really the start time and the end time because usually you set goals but we don't and we don't know when to accomplish. And once you set yourself a time constraint you can say OK so I I must know this for the next 10 minutes or next 20 minutes and you have to get it done in that time period. It's a really good motivator and a really good way to be productive. OK. So in this section we covered the goals we covered why it's important to focus on the outcome. Knowing the purpose and then coming to the plan as to why you want to call it how you want to accomplish this and why I encourage you to go through the exercise to call with your own outcome plan and purpose. And I will include all these templates in the resources for this section. So in the next part we're going to get into the criteria the score and your trigger questions so I'll see you in the next video.

==== 5/5 Evaluate How You Did and Repeat

OK so congrats you almost done learning the daily journal template. The last part we're going to cover is the other note section and which is right here other notes and we're going to then cover these two together. Productivity's scored in District 6 triggered questions. So the other note is the part where things that you didn't plan for the day come. For example when someone else tells you hey get this done your mom tells you to grab milk. Your friends your family your kids your wife your girlfriend your boyfriend. Anyone who expects something from you. This is where you write those things down OK. Do this house do this or for example if you open your e-mail and you realize you have to do some other things you write those things there. And it's important for you to write them there because you know what I usually do I go back after a day or two and see how much of the things that I was supposed to do that day and how many of the things just came onto my plate. *And this allows you to kind of reflect and say OK am I getting the right price or priority work done or am I getting more of like other people's work and not taking time to do important things*. So that is the other notes section part.

Now we're going to get into the productivity score and the six triggered questions. So actually the six trigger questions are very key. They allow you to allow you to at the end of the day do a critique on yourself about if you were actually doing the actions and the behavior that you wanted to do. For example we all wanted to you know have a really productive day. But if you didn't spend time to get work done then your behavior is not aligning with your beliefs. And the goal here is to keep doing this on a day to day basis so you just even if you're not getting time to say accomplishing your goals or what you write down in your journal you're aware of it. Read again the goal here. Even with me was not to become superhuman from day one and answer all of these questions. Yeah I'm doing my best to set clear goals and doing my best to do this or that. The goal is to be answering these questions regardless of how productive or unproductive your DVD. So this is how I would typically go for me. So at the end of the day I would go and ask myself these questions. I usually talk out loud. Some just to do the exact same thing here. I would say OK was what did I do my best to set clear goals and pay and *I would rate myself out of one to 10*. OK so I will I will look at my journal I will see OK I did I did. My goal is very clear and I did it did I publish them and I usually do this around 9 p.m. which is the end of the day for you and I look at it OK. All right. So I set clear goals. I would rank myself maybe six out of 10. And I was focusing on what I have what I want not necessarily what I should do. And then I would go to the next question. The key part is really to ask yourself Did I do my best. Because you're always always wanting to improve we are always wanting to get better. So once you ask yourself these things you get into the mindset of self-improvement. Always improving always asking more of yourself than I would ask the next question do I do my best to make progress towards goal achievement. Yes I did I accomplished three of the four goals that I wrote down. I accomplished them before my deadline. And within that time period I had. And then I would go to the next question. So this just part will take me quickly. You know maybe 30 to maybe a minute or two of your self-analysis and then I will get myself a proper score after I've answered all these extra questions. So these this doesn't have to be like you know super perfect. But usually if you give yourself seven out of 10 that means you have super super productive day. I haven't given myself 10 in five years. Well I only started doing this last year but I still haven't given myself 10 out of 10 because I don't want to tell myself that there is something. As such it is a perfect day. There's always ways you can improve yourself. So again that is the part that is how you conclude your daily journal and congratulations. Now you have learned the whole template of the daily journal how you start your day with it quote the five minute journal entry the outcomes which is right here the target completion time and the target completion times as well as other notes and productivity section just down below. So I want to congratulate you and hopefully I want you to get a pen and paper and do a journal entry for today and then watch the remaining videos there maybe some bonuses there maybe some more tips that I might include later on. So all the best. Please keep me posted give me any feedback you have ask any questions. I'm more than happy to help but I'm excited to have taught you this and I'm excited to see how you use this to access all of your life and overcome your go and obstacles to get to where you want to get to and you in the.