= Notion
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Learn JIRA with real-world examples (+Confluence bonus)

=== Section 1: Introduction

*Introduction*

Hey, it's Jared. Welcome to my getting started with Knowshon course in this course, we're going to look at Knowshon and talk more about some of the features and how to set up Knowshon from the get go, depending on what it is that you're trying to achieve. Knowshon could be a lot of things for a lot of people, and it can be different depending on what it is that you're trying to achieve. So I'm going to talk about how I have thought about going into setting things up, *a notion whether I'm setting up a new area for work or I'm trying to get more organized in another aspect of my life notion is definitely become a powerful tool because it allows us to create our own systems where most other applications we have to fit into their system somehow. So I think that's what the real power is in utilizing notion*. So as we jump in the first couple of videos here, we're going to talk about organizational structure, kind of having the right mindset as far as how you want to put things together so that you don't end up building something that ends up becoming burdensome over time. I think that's definitely a pitfall that we could fall into with notion it's setting things up in a way that it just becomes unmanageable. I know for me, with different journaling systems and organizational structures that I've tried to implement in the past, it's been too overwhelming to actually make all of that happen. And it's not a sustainable process. So we're going to be looking at how we can set that up in a quick and simple way as we go through the process of learning how to use Knowshon and setting it up so that we can organize and structure our lives accordingly. So I hope that you enjoy this course, make sure to jump around as needed. Maybe not all sections are for everybody. Definitely go to the section that you are most interested in. But I do recommend first watching this introduction section that will help you kind of get in the right mindset for setting things up in Knowshon. I'm definitely going to talk about some of the pitfalls and some of the things that I've fallen into through my almost year of utilizing Knowshon and *getting it to the point where I organize my entire life and my business within Knowshon*. So let's jump in.

*Introduction*

So before we dive in the notion, I wanted to talk to you about a couple of things and a mindset, I guess, just to have as we're setting up notion now, if you're like me, when you first got started, you imported some templates and you started using them and you found that they just weren't fulfilling the needs that you had. Maybe they weren't talking to each other because they were separate templates, not designed to talk to each other, or maybe they were just so convoluted that it became burdensome every day to actually go through the process of utilizing them. Now, what I want to help you build is a platform that's going to be easy for you to use. Every day you can get in there, you could find the information that you need. You can log the information that you want to remember. And all of this stuff is tied together. Templates are powerful, but they're only powerful if they work for you. And the templates that I put out there and a lot of my YouTube videos, I do in a way where I show how it's built and the reason that I show how it's built and not just talk about how cool it is and then give the template, because I want people to understand how to set it up themselves so they could install the template or download the template and look at it and see how it works. But the real power is implementing it into a system and connecting everything together. *So as we build out a system together and learn how to use Knowshon together, we're going to be connecting things and learning how to actually build something that works, that is going to help you keep organized. And not only just, you know, we can be very organized by keeping everything in a notebook or, you know, Evernote or Apple notes or something like that. But when we want to start tying information together that is in different areas of our life, that's when Knowshon really becomes powerful* and just the structure and capabilities that notion has there. But we need to understand what those are before we dive in too deep and get in so deep and find ourselves in a hole of information. And we can't tie it together. We can't find what we're looking for. That's what I want to help you avoid. So as we dive into Knowshon together, don't be afraid to click on something in Knowshon and try it, set it up, configure it, manipulated around a little bit and don't be afraid to delete it if it doesn't work out. We have a lot of templates available to us and they're fun to play with, but don't feel like you just have to install that and then make it fit. Your life notion is about customization and being configurable in a way that makes sense for you. And I'm hoping that through this course we'll be able to discover what that is and help you utilize Knowshon better. And then in future courses that I have coming out that you'll, of course, be notified of, we'll look at more specific areas and how we can build out Knowshon to improve organization and structure in those areas of your life as well. So let's jump in to Knowshon and start looking at how to set up Knowshon for the first time together.

*Notion Overview*

Now, briefly, before we dive in, I'm just going to show you the different elements and aspects of Knowshon so that you know your way around, we're looking at a basic workspace here that just has one section and one page over on the left hand side. You can see where in this workspace and I have two different workspaces, my personal workspace and then also the workspace I created for this course. We have a quick find area that is a really good search tool that will allow you to search within all of your workspaces. So even if I'm searching within this workspace, I can also find things that are in other workspaces, which is really nice. Update's is a great area for reminders and mentions and other things that are going to show up. And so the all updates inbox is a very useful tool because as you start to use Knowshon for setting reminders and different stuff like that, this area will be where you can see those most recent reminders. In case you missed the prompt that shows up in the notifications of your computer or your smartphone settings is where you just configure Knowshon appropriately, upgrade your account from the free account to maybe one of the premium accounts, and just look at adding members to your page as well. If you were going to invite your workspace, invite other people to your workspace like family members or if co-workers, other people that you're working on projects with, you can do that there. Then in this section, we have our different pages and underneath pages we will have databases which will take a look at shortly. So in this section, you can create multiple pages. You can also utilize these as folders, as places to archive things as well. Templates is a great way for you to look at templates and to add templates. But we're going to be looking at building things from scratch in this course, which I believe is the way that you get the best understanding on how to use Knowshon. You can also import additional information. When I first got started, I imported all of my Evernote notes and a notion and then just put them in a folder over here off to the side so that I can get to them through search or by mentioning them in another area of notion that I'm utilizing more often. We also have the trash can that's going to show any pages or databases or information that you have decided to delete. And the main body, we have the title above the title. We can add an icon, which is like an emoticon, or we can upload an image, we can add a cover image, and then we can also add comments. Comments is really good for collaborating with others. It's not a super useful tool if you're just utilizing notion by yourself underneath that we have the ability to just start typing and build and a page in Knowshon or we can add a database or we can even implement a template from here as well. So if we click in, we're immediately creating a page and we can start typing into a page and create and build out a page. Every time we hit the return key, we can hit the backslash and get access to all of our different blocks. Blocks are the true power and notion where we're able to build out our pages and style them and structure them and mention other pages, embed things from other websites and all that good stuff. We're going to look at doing that throughout the course as we build project manager, as we build page templates and all that good stuff. So as we go through the course, we're going to be looking at to do lists and different headings, sizes and bulleted lists and toggle lists and all of that good stuff. We're going to be looking at embedding inline databases. We're going to look at linking databases together between pages. We're going to look at adding images and bedding, different elements like a tweet and different stuff like that. And then as we scroll down looking at the different color options and styling options of the content that we add into Knowshon. So rather than going through that exhaustive list of stuff right now, as we go through the course together, we're going to be looking at those things and utilizing all of them. Keep in mind that this is a introduction kind of basic course. So we're not going to dive deep into everything, but we will utilize the most common things as we move through this course.

=== Section 2: Databases

All right, so we're in Knowshon and we're starting completely empty. You don't have to delete everything and start empty like me. I just recommend that you start with a new top level page in your workspace so that we could start building this out in a structure that makes sense moving forward. And then with any additional stuff that you've already started building, a notion that can be kind of married in and connected later on as we get through this course together. So if you've already started using some templates and you are afraid to ignore those or that we're going to throw them away, know that later on we will bring that in and we will look at how we bring that all together. So we have a base page here and we're going to call this base page dashboard. You can call it something else. I've called mine Jarrod's, which is kind of a mash up of my name, Jared and OS four operating system. It's I'm a nerd. And so that's why I called it that. But you can call it anything. I'm calling a dashboard in this video because a lot of people do tend to call it a dashboard and it is kind of a dashboard. It's going to be a place that we organize everything. Think of this as the root of your hard drive and we're going to be creating folders and connective structures from here. So with a dashboard, we have the ability to just start typing into this page and make it a page or actually add a database right to it, because as we start building out, our dashboard will be relating databases and displaying information on our dashboard. We don't want to immediately create this as a database. We want this to be a page. So go ahead and just click right into it, clicking right into it. We're going to create some pages that we are going to turn into databases. So we're going to look at what we want to build out first, simply type plus and then start typing the name of something. I'm going to put a tasks page and there that will become a database. I'm going to create a projects. I'm going to create a people. And a calendar. We might even go a step further and put in something like expenses, if you wanted to do an expense tracker or if there was something else that you wanted to add in. But we're going to look at this here being kind of our base structure for what we're building together now, it doesn't look too exciting. But in the next video here, we're going to set up databases for each of these. And then as we go into each one of these four sections together, we're going to build out the structure for these databases and then we're going to connect them together so that they work together and create a kind of ecosystem for you to stay structured and organized with your projects, tasks, different areas of your life and the people that are involved around them.


