= Template
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===


== Kizomba

=== Section 1:

==== Introduction

Ello welcome to kill zone bon fire Yorkie Zumba. Course I'm very very happy that you are here with us. My name is John Capella and along with alongside with me will be Vera Gomez my lovely wife and we together we will teach you all to dance. Key zone by starting from the beginning and till very very not the end but almost but too until a good level that. Well we'll be able to go out and dance Zumba and add fun. So now that you are here I have some tips so you can take this course to the next level so you can take the most of this course is all I have on my laptop to to help me. So first think let's start save this web page on your browser so you can access the speech mark week. OK. Don't forget to save it on your favorites. Some things Wara and add it. And so you can come back here very quickly. OK. Second use the sections. OK. The models the menu that you have in this course to go through to do the levels and the videos you're usually on your left. Right. Use the sections to go through the levels. So great. Great. Numbers three. Don't forget and this is very important. Don't forget to follow the course from the beginning until the end. Don't skip lessons don't go immediately to the last videos the wedding maybe will be the more beautiful steps no. Take the course from the beginning because then you can learn all the names all the things that he means and then when you arrive to the more advanced steps it will be better much easier to understand and of course the first videos are most important are the basic ones. So take it from the beginning though. OK. Don't jump force ethics. Ethics is the most important thing. We are talking about dance. We are talking about Zumba. So if you are going to be on your stair stair. Yeah. Cher Cher. Just watching the videos. You will not learn. Maybe a real thing. Yes I know Keyes zone but now that I am here for two hours of watching this. No you have to practice. And don't forget practice immediately after each video. Don't go to the next video. We don't practice seemed to be the one before. OK. This is very important. OK. Now these is for advanced students. These courses for beginner to intermediate. As you know. But we have many students that had already advanced. And of course if you want to go you can jump immediately to more intermediate stamps suggest if you want but also for you I advise you to watch the first videos where you can learn the basic steps in the correct way our way. OK. At least and these way you will understand much better the intermediate steps. OK. So this is my advice. Also learn the basics and do all all week call each step. And finally this is me asking you for help. Don't forget please share this course with your friends. OK let's bring our all the world here to learn the key zone. But let's make these a bigger and better place and help me to spread the passion about key Zumba to the world. Me and Val of course. So don't forget to share this course with your friends. And we will be very very appreciated. OK. And now just one thing more If a lot of fun. Don't forget it. See you on the next video. Bye bye.

=== Section 2

==== Differences Between Tarraxa and Kizomba

Hello hello welcome to this model and we are going to teach you what is that hash or that hashing it like in our language. So you have to understand the difference between Zumba and to hash out the hashing it. And when you understand these differences you will be more able to to dance and to repress the music *so tarraxa is did the slow movements the wave movements that lay these were moving the hips. And when you are very slowly dancing with your lady or with your partner because the music is smooth there are not many strong beats. And so in these parts of music we dance taraxxa. So taraxxa his all the wave movements all the slow movements*. And on the beginning this was a difference a different dance at all. But now it's fusion with key Zumba and we we mix the both and everything is key Zumba now. *So when the music starts usually you start with taraxxa because that music usually never starts with strong beats so or a strong accent. So he's in these beginning you should start with the waves movements* and these will teach you on to the next video. Don't worry then these video you just need to know how it works what is one thing and then another thing. So on the beginning of music you will start with the waves with the E movements on the place very slow movements. *And then when the beat starts you start to read the key Zumba steps that is on the next movement*. OK so far this I have my beautiful partner and wife Vera. Not yet please. And two that she actually started pitching music because she's wonderful but not yet. And we are going to teach you or to show you we the music when to do Tasha and when to do it keep Zumba so we will start with the music and do you'll see that the beginning of the music. There are not many strong beats so we will start with some Tasha movements. And then when the beat starts you will see us dancing a little bit off key Zumba. OK. Let's see OK. This was one example the beginning with the Haitian. And now we have this Zumba next music Zumba and now we are dancing Zumba. OK. I hope you could understand the musicality the difference between the parts where you are going to dance the Harsha and wedding when you are going to dance key Zumba for these it is very important that you keep listen to a lot of musics. *And another thing sometimes and mostly of the times in the middle of the music the beat stops. And so you should do again that tarraxa*. So when you are dancing you should always be listen to the music. This is obvious. So you listen to the music when the music tells you OK. This is a smooth part I should do that tarraxa or disease and accent parts so I will do Zumba steps. So musicality is very important. And now you have a little bit of information about where and when to do Tasha and went to Duke his Zumba let's go to the next video where we are going to teach you exactly some hardship steps SEO.

==== Taraxxa - Wavce and Double Time

A low a low and let's start to really learn some Tarraxa movements. Tasha steps. So the first one then the one that everybody loves. Let's start to learn the way of movement. The ones that melt mostly the lady but also the man does during the harsher music. Okay.

*First* exercise I will ask you exactly veritable to do on the site. I will be like these feet apart. Relax. *One man one hand on the belly another on the back*. So you can really feel the wave. And let's do this. This is the easy easiest way to learn to wave first. Let's go down a little bit. Dan Beck with the IPS then app. And then to the front with the ape let's continue down. Back up front. *Down. Back up front*. Down. Back up front. Down. Beck continues. And why. *And very small*. You should not do this. He's very small your head almost is on the same place. You should not go up and down. Okay. Very difficult to do exactly. This is the exercise that you should do. Facing the Mirror always practicing this.

*Now we will practice even doing this with our weight on the right foot*. So we are facing our partner and the weight is on the right for both of you. Okay. And let's go do the same thing but mostly on the right leg and down and slowly. Boom boom boom boom. Down. Back front and continuous. Boom boom boom boom boom boom exact. Let see that out my left feet is a little bit to the outside right to the front. And now we do this on the left side OK. And where in knees a little bit always a pot split. Not together. Exactly. And now the same exercise a little bit but from behind so you can see both EVERYTHING ON THE RIGHT FOOT AND BOOM BOOM AND BOOM BOOM. Exactly. And on the left foot and boom boom boom boom boom boom. OK very good. So just go back and forward and try to practice as much. Now another step and now we're ready with some movement and weight transfer that is the *double time* on the double time is the first step that you are going to really step on your feet. *So first thing you always step with all foot* not with this great difference like point eel point. Not so much 0 foot. Everything. Then second thing don't work don't think about the wave right now it's a great thing too putting time but don't think in the most of the important is that *if you are with your weight on the right you are transferring the weight to your left foot. And imagine pressing and going play* you are pressing in and for that you need to lose your IPs and always upwards movement never these spend a our movement OK weight transfer you know use the hips go down sit on your feet OK varies already here. No Are you OK sit on your hip and you go left up right up all foot up. Remember key Zumba comes from Africa from Angola. You dance without shoes with all your foot on the land. Exact exam. OK. And now if you want it it's great. On the double time you can add do wave and so we will do on the side and wave. Oh OK. Wave. *You are going up and your hips are doing the way so together how can we do this*. Let's start with the Wave wave. *The man should be on the right foot and the lady on the left foot*. Here OK. And we will do the wave on the place because if you change weight is not the wave is the double time and one two. This is a great way to do the wave. *All you lead the lady with your right and push down up down up*. So our back is doing this wave OK. If you transferred the weight shear we'll try. Sorry is not the wave is the double time and this is exactly what we're going to do now. Transferring the weight and doing the double time double time double time one two one two one two one two one. And if I want I can stay here and I just do the weight. I don't allow words to go there. I stay e and wave and the wave OK. So on the wave and also on the double time you you always used two times. One two one two one two. Are you under double time. One two one two. These two. The reason is it calls the double time and you use your right and to slightly massage our back to do the wave. OK so let's do it. Oh. The music.