= Udemy Official Course
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Udemy Official Course

=== Section 1: Welcome

==== Introduction to the course

Hello, everyone. My name is David. And throughout this course, I will tell you a story of how I learned to *create a great course outline*. It's not hard. To be honest, it's actually pretty simple. But when I started, I didn't know how to really approach it. I had no real structure. I was really trying to rush through the process to get my course out. I had made some bullet points and then just started filming. But what happened was I went off on way too many tangents and by day three I'd forgotten whether if I had covered already the topic or not. I realized what I really needed was a process that I could follow and dedicate some time to doing it right. So in this course I will teach you what I learned so you can avoid the same mistakes that I made. For you to get the most out of this course, you will need to have completed the course goals Worksheet from the instructor insights course on setting your course goals. If you haven't completed the Worksheet yet, it's fine, you can find it attached to this lecture. Throughout this course, I will share my experiences going from a very messy process to a structured outline that saved me so much time and production. An outline is such a helpful tool for so many reasons. An outline allowed me to make sure that my target students would actually be able to achieve the larger goal. It also helped me have an easy to read map on topics that I'm covering. It helped make sure that each section is well rounded with the proper beginning a middle and an end. Having a helpful starting place for scripting with some notes about what I plan to include in each lecture. And most importantly, it helped me project manage my course creation process. It's great to have this big picture view because if you film your lectures over multiple days, or sometimes even weeks, you can use the outline to remember what you already scripted or recorded and you know what to do next. I didn't go on this journey alone. And neither will you. I've had help from *Lauren*, who is our course creation expert, who'll be jumping in to provide some actionable steps and tips to help you complete your course outline. Hi, everyone. My name is Lauren and I will be your course creation guide throughout this journey. I will provide you with best practices and expert tips that I've used in my work with hundreds of instructors. Also, you won't be passively listening in this course. As you go through each section, you will actually be working on your own course outline. I'll break down the process into digestible steps, so that by the end of this course you'll have completed your outline. We're going to show you real examples of outlines, go over some of the most common problems you might encounter and most importantly, we will guide you through creating your outline step by step. Let's get started. 

=== Section 2: Drafting your sections

==== Get your course goals

IMPORTANT: Need to  work on Course Goals.

By the end of this section you'll have picked an outline template and you'll have created a rough skeleton of the sections that you'll include in your course. Let's dive into an overview of that process. When I started my Udemy course, I quickly realized that it's not just about creating a presentation and recording it. You're creating a course, not just for entertainment, but to help students learn something.

I learned that outlining is a process and it all starts with your course goals. You break larger goals into section goals and then you start mapping out which lectures and topics will help your students reach those section goals.

If you're like me, I know it can sound a little painstaking and even overwhelming, but trust me, the clarity I got from this exercise made the rest of the course creation process ten times easier. Your course is a little like a bridge that carries students from point A to point B. When you structure your course well, and know how each portion of the bridge is constructed and supported, you can feel confident that the students will achieve the course goals.

Lauren took me through *four main steps*: *First*, work backwards from your goals to determine what materials and skills are essential to include. You'll bundle these skills and concepts into content building blocks called sections. *Next*, choose a logical order for your sections. Also, you want to shape your students' journey by adding notes about things you should do at the beginning, the middle and the end of your course to make it engaging, professional and effective. And lastly, add lecture level details to prepare for scripting.

What I want you to do now is get your course goals Worksheet out. If you haven't completed it yet, you can also download it in the attached resources in this lecture and fill it out. Look at the Udemy insights course on course goals if you need help. Once you've reviewed your course goals, meet me in the next lecture, where I'll teach you how to turn your goals into sections for your course.

==== Turn your goals into sections

In this lecture you'll learn how to create an outline skeleton based on your course goals. By the end of the lecture you'll have a rough idea of the sections that you'll teach in your course. So the first thing I was wondering about was what exactly should be included in the section? So I asked Lauren and she was like: "On Udemy, your course is split up into different sections. And each section is a collection of lectures and activities. *You teach one skill per section and teaching that skill is your section goal*." "So what do I do with my course goals worksheet? Why am I starting with that?" "Here's the deal, you want to work backwards from your course goals to ensure everything you covered in your course is relevant to your goals of your target student. In the end, you will have one goal for each section. You may notice that some goals on your worksheet seem too broad for a section goal and some seem too small. So you want to split the broad ones up into multiple sections and combine the ones that are too small." So here are some of my goals from my goals Worksheet.

When you look closely, you might notice that these goals are requiring varying degrees of difficulty to accomplish. The process of finding the right size section goal is more of an art than it is a science. As you look at your goals, some of them might be too broad some are too small and some others are just right. Once I break those main components down into manageable sizes, I'll have my sections. Lauren gave me some great valuable questions to ask to help me move towards the best size goal. When I look at my goals I realize that achieving goal number one, which is cutting editing time in half, can't be taught in a single section. So when you have a goal that's too broad, you need to ask yourself: "What are some of the smaller skills needed to accomplish this goal?" So in order for students to cut their editing time in half, students need to master keyboard shortcuts and they need to be able to apply changes to multiple clips at once. Now, I have two more section goals planned out. Let's look at goal number two: properly name their folder structure. There is no way I would spent multiple lectures talking about this issue. I was going to teach this in one lecture. For goals that feel too small, Lauren told me to ask: "Where could I fit this subgoal? What section could it be a part of?" My next section goal I will include in my course is project managing your video editing project. Finally, I had a goal on using morph cuts to make smooth transitions between videos. I think it would take me just one section to teach that material. That goal is just right. The great thing about a goal like this is you don't need to split it up or consolidate it. Now, I have my main sections, I was ready to put them in order.

To recap: The first step of creating an outline is taking your course goals and making sure they are the right size to cover a chunk of content that is possible for students to finish in one sitting. Now it's your turn. Look at your goals worksheet and slowly start to identify the core sections or big topic areas you'll want to teach. You can do this initial brainstorm on a piece of paper or at Google Doc.

==== Order your sections

You might feel like the sections you created still feel like kind of a mess, but don't worry. In this lecture, you'll learn how to put your thoughts in order. And by the end of it, you'll have a linear structure for your course.

At this point, I had worked out these section goals. Now, *I needed to put them in a logical order*. Lauren told me: "There are a few different ways that content can be structured. Students need to learn things in a particular order. You can't learn how to ice a cake, if you don't know how to bake it first. There will probably be a natural order to things once you take a step back to consider the big picture." Lauren showed me five different ways to put sections in a logical order. If your content has no hierarchy or sequence, then you can think about ordering it by categories, like tasks or products. Think about a cooking course, you could organize by recipes or spices used. Or an Excel course could be organized by formatting tools, data analysis tools and common formulas. Another way to structure your course is by cause and effect. This makes sense if the content presents problems and many solutions. Many IT or personal development courses could be organized in that way. *If the content already has an inherent structure or sequence, like needing to be in chronological order, or a series of steps in a process or procedure, it makes sense to keep that inherent structure when outlining your course*. If students need to build up to understanding a complex problem or concept, it might make sense to *structure it from simple to complex*. It can help build learners confidence and knowledge by starting slow and then adding complexity as you move along. A project management course might start by introducing useful management tools, before talking about agile process management. And lastly, instead of starting simple and getting more complex, some content may actually be learned better if you see the big picture and that's introduced first. And then, what you do is dive into each part. This provides context to the students so they can make better sense of how each piece of information is important and where it fits in. This course you are watching now is actually structured in that way. So, if we use my editing course that I'm working on as an example, I decided to order it by problem and solutions. I want to help students with three problems: Get more organized, cut editing time in half and have a better looking finished video. So, this is the order that I came up with for students to learn Adobe Premiere. This might sound really obvious, but knowing the inherent structure of your course will give you confidence that it will make sense to your students.

So, now it's your turn. Go through your sections and put them in a good order. Think about what makes most sense for your target student and for your content. Remember, your students are learning this from scratch. Here are a few questions you can ask yourself if you get stuck: *if you were new to the subject, starting to learn it all over again, what would you benefit from knowing first*? Or are there any concepts, skills or backstory that you need to already know to be successful in certain sections? If so, it's best to move those earlier in the course. That will ensure that you're covering the pre-requisite material for what you're going to cover later in the course. And just a quick note on that: keep in mind that if you're creating an advanced level course, you usually don't need to include as much introductory content. It all depends on your target student.

=== Section 3: Deciding on your outline template

==== Section components

Now that you have a basic course skeleton with all your main sections, it's time to get more granular. In this lecture you'll get a good understanding for what makes up a section, so you know what elements you need to plan for in your outline. *Let's go back to the bridge analogy, I learned that my course is the bridge between where my students are and where I want them to be*. The bridge has individual sections. Now, I needed to understand each of the components in a section. Every section should have its own section goal, so students know what skill they will learn in that section.*But now, how do students reach that goal? There are two components that make up a section: lectures and activities*. Lectures, on Udemy, are often videos, but can also be text. In lectures you teach your students information and concepts. The other component is the activities. Activities help students learn by doing or to apply what they've already learned.

In the following sections of this course we'll work on your lectures and activities, but keeping track of all the components can be messy. So to get you started in the next lecture I'll share an outlining template that I also gave to David. This will help you stay organized and better manage your course creation process.

==== What you need in an outline template

One thing a lot of instructors struggle with is finding the right format to outline their course. In this lecture we'll share what you'll need to include in your outline and show you some examples of outlines that other Udemy instructors have created. I will also provide you with the template that I've used with many instructors. By the end of this lecture you'll decide on a format that's right for you. To be honest, I had no idea what format to use to create my outline. I mean, I knew that I was going to have sections, lectures and activities, but what else did I need to think of or keep track of? So I asked Lauren, and Lauren was like: "Well, different instructors certainly have different preferences and have had success with all kinds of outlining tools and templates, but I would say a majority of our instructors use Google Sheets or Excel to outline. We also have instructors who use Docs, Evernote or Mindmanager. Or old school pen and paper. Or even their living room wall. Let me tell you what your outline should include and then you can choose your format.

*I learned that I will need my outline template to: show me if I have enough practice opportunities, show me the estimated time each lecture will take, highlight where I might add additional resources like checklists, templates or PDF articles that may be beneficial to add for the students. Add notes for myself for scripting, add the lecture format. Will the lecture be talking head, article or screen cast? Include section titles and lecture titles and add the section goals*.

The fact is our instructors get organized and create an outline. It might seem like a pain at the beginning, believe me, I thought the exact same thing, but it will save you so much trouble down the road and your course quality will be way better, I guarantee it. To get you started on the right track, I have created an outline template that you can use. I have also asked some Udemy instructors to share their outlines so you can look at a few different successful examples. Check them out in the next lecture, then pick an outline template that works for you or create your own. In that template add the sections in section goals that you've worked on so far.