= Udemy Official Course
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Udemy Official Course

=== Section 1: Welcome

==== Introduction to the course

Hello, everyone. My name is David. And throughout this course, I will tell you a story of how I learned to *create a great course outline*. It's not hard. To be honest, it's actually pretty simple. But when I started, I didn't know how to really approach it. I had no real structure. I was really trying to rush through the process to get my course out. I had made some bullet points and then just started filming. But what happened was I went off on way too many tangents and by day three I'd forgotten whether if I had covered already the topic or not. I realized what I really needed was a process that I could follow and dedicate some time to doing it right. So in this course I will teach you what I learned so you can avoid the same mistakes that I made. For you to get the most out of this course, you will need to have completed the course goals Worksheet from the instructor insights course on setting your course goals. If you haven't completed the Worksheet yet, it's fine, you can find it attached to this lecture. Throughout this course, I will share my experiences going from a very messy process to a structured outline that saved me so much time and production. An outline is such a helpful tool for so many reasons. An outline allowed me to make sure that my target students would actually be able to achieve the larger goal. It also helped me have an easy to read map on topics that I'm covering. It helped make sure that each section is well rounded with the proper beginning a middle and an end. Having a helpful starting place for scripting with some notes about what I plan to include in each lecture. And most importantly, it helped me project manage my course creation process. It's great to have this big picture view because if you film your lectures over multiple days, or sometimes even weeks, you can use the outline to remember what you already scripted or recorded and you know what to do next. I didn't go on this journey alone. And neither will you. I've had help from *Lauren*, who is our course creation expert, who'll be jumping in to provide some actionable steps and tips to help you complete your course outline. Hi, everyone. My name is Lauren and I will be your course creation guide throughout this journey. I will provide you with best practices and expert tips that I've used in my work with hundreds of instructors. Also, you won't be passively listening in this course. As you go through each section, you will actually be working on your own course outline. I'll break down the process into digestible steps, so that by the end of this course you'll have completed your outline. We're going to show you real examples of outlines, go over some of the most common problems you might encounter and most importantly, we will guide you through creating your outline step by step. Let's get started. 

=== Section 2: Drafting your sections

==== Get your course goals

IMPORTANT: Need to  work on Course Goals.

By the end of this section you'll have picked an outline template and you'll have created a rough skeleton of the sections that you'll include in your course. Let's dive into an overview of that process. When I started my Udemy course, I quickly realized that it's not just about creating a presentation and recording it. You're creating a course, not just for entertainment, but to help students learn something.

I learned that outlining is a process and it all starts with your course goals. You break larger goals into section goals and then you start mapping out which lectures and topics will help your students reach those section goals.

If you're like me, I know it can sound a little painstaking and even overwhelming, but trust me, the clarity I got from this exercise made the rest of the course creation process ten times easier. Your course is a little like a bridge that carries students from point A to point B. When you structure your course well, and know how each portion of the bridge is constructed and supported, you can feel confident that the students will achieve the course goals.

Lauren took me through *four main steps*: *First*, work backwards from your goals to determine what materials and skills are essential to include. You'll bundle these skills and concepts into content building blocks called sections. *Next*, choose a logical order for your sections. Also, you want to shape your students' journey by adding notes about things you should do at the beginning, the middle and the end of your course to make it engaging, professional and effective. And lastly, add lecture level details to prepare for scripting.

What I want you to do now is get your course goals Worksheet out. If you haven't completed it yet, you can also download it in the attached resources in this lecture and fill it out. Look at the Udemy insights course on course goals if you need help. Once you've reviewed your course goals, meet me in the next lecture, where I'll teach you how to turn your goals into sections for your course.

---

---