= Template
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Course Name

*Maximizing Value*

* [ ] *Fundamentals*: Learn the concepts
* [ ] *Information*: Do POC from the course
* [ ] *Skills*: Use / Implement it in Project
* [ ] *Innovation / Expert*: Value for next 2 Years


*Objective*

* [ ] *History*:
* [ ] *Agenda-While doing this course what is the Agenda [1,2,3,4,5..]*:
* [ ] Exam Notes
* [ ] *Why OneNote Notes*:
* [ ] *What is Pending*:

== Emotional Intelligence - Joel Natalie-Rivera

=== Section 1: Introduction

*Introduction*

Welcome to master your emotions, including uncertainty, stress, anxiety and fear.  Most of us have been told lies about emotions for all of our lives.  We're told that they're bad, that we shouldn't express certain ones.  We're told that we should trust our gut.  But at the same time, we're told that emotions are irrational and shouldn't be trusted.  We're told that emotions happen to us and therefore we have no control over it.  *But the truth is that that you can control your emotions.  You can get really good at experiencing the ones that you want and avoid the ones that you don't want*.  Think about an astronaut for a moment.  They train themselves to be completely in control of their emotional state.  And of course, they do that because it's a life or death situation and they have to have that control.  But they're human beings just like us, so they can control their emotions.  So can we.  The truth is that emotional self-control is possibly the most valuable skill that you could ever acquire.  *It helps you cope with whatever life throws at you.  It helps you prevent stress, anxiety and fear.  And it helps you unlock your abilities, frees you to live the life that you really want, and actually  has been linked strongly to what differentiates between people who are successful versus people who  are not*.  For most of us, no one ever taught us what emotions are or how they work.  No one taught us that we can control them because we can control our mind and therefore we can control  our lives.  *No one ever told us that it was the lack of emotional management that ends up leading to drama, to  suffering, to addiction, and to poor decisions, and that all of those things can be avoided*.  Emotions matter, and that's why we've created this course.  We'll focus on three of the most undesirable emotions uncertainty, insecurity, anxiety and worry and  fear, and how you can use emotional awareness and self-control techniques to take back control of your  emotions and feel better now.  What did you what your emotions really mean?  How to recognise them and how to direct them in a way that really allows you to move towards your life  goals and really your desires and what you want to create.  *We'll teach you how to get out of your head and become the observer of your emotions as they happen  so you can avoid being hijacked by your own brain and really feel control again*.  So after learning these tools, you'll be able to really feel good, or at least better.  *No matter what's going on around you or what life throws at you.  You stop your emotions from spiraling out of control.  You'll feel resilient and capable of handling life stressors.  You stop raising thoughts and calm your anxiety, your de-escalate, overcome, or prevent your fears.  You develop mindfulness by focusing on the present moment, and you also feel confident and in control  of your emotional state and your life*.  In this course, you will learn what emotions are and how they work, how to recognise them and identify  them.  How to direct your thoughts so that you can direct your emotions.  How to reframe situations that make you feel bad.  Find the blessing and then feel better.  You're going to learn stress reduction techniques, proven processes for preventing yourself from losing  control.  Emotionally, you learn tools to de-escalate.  When you're feeling anxiety or fear, you'll learn NLP or neuro linguistic programming techniques for  rewiring your emotions and anchoring positive ones.  You'll learn how to cope using humor and other self-empowerment techniques.  You'll develop self-confidence, uncertainty, and you'll master the feelings of hopefulness and feeling  joyful.  Joel and Natalie Rivera of Transformation Academy are life coach trainers and entrepreneurs who have  trained hundreds of thousands of people from around the world.  Their content is based on their educational background in psychology and education.  Nearly two decades of experience in the fields of life coaching, social services and entrepreneurship,  as well as Joel's background as a psychology instructor, his master's degree in counseling and research  on happiness for his dissertation for a Ph.D. in psychology.

*Mind Body Emotional Connection*

I'm going to walk you through two quick activities that help you be able to experience the mind, body,  emotions, connection, and so if you understand that your emotions are almost always influenced by  your thoughts, then you can identify the emotion, identify the thoughts, change the thoughts, and  it gives you power over your emotions.  So I'm going to give you a quick demonstration.  So imagine your phone is ringing and you know who is calling.  And it's somebody that you have a feeling it's going to be telling you something really good and exciting.  So you answered the phone eagerly.  And sure enough, on the other end, they're telling you the best news you have ever, ever heard and  you can feel yourself getting really excited.  And the more you talk to them about it, the more wound up you get and you can feel yourself smiling.  It's like you can't hold it back and you can feel the excitement in your body and you feel yourself  to starting to move around.  And you're so overwhelmed with joy that you just want to put your hands up in the air and shake them  around and and you almost want to scream.  You're so excited.  So I want to ask you a question.  When you were imagining this, could you feel anything?  Could you feel any of those things I was talking about?  Did you have any sensations in your body that you feel yourself wanting to smile?  Did you feel any emotions now?  We only did that for a few seconds.  And if you were feeling a response to it, it's not like you actually received good news or a phone  call.  Right.  We were just pretending.  But yet your body and your mind react anyway.  And so that's a really great illustration that all it takes is our imagination to make us feel something.  And so what I'm here to tell you is that that is always happening to you.  What you are thinking in your mind is causing your emotions.  So it may be that the way you perceive things is you're seeing things around you and you're thinking  about the things that you're seeing and that's causing an emotion.  And so you blame the things that you're seeing.  But truly, the source of your emotion doesn't come from those things around you.  It comes from what's going on up here.  And so here's another example and this one, take that a step further.  And it shows you that it's not just that your emotions respond to your thoughts, but your whole body  does, too.  And so all three of these things are connected in this short visualization helps give you that idea.  So just imagine that I'm in their room with you and I come in with a plate full of these big, fat,  juicy limes.  And so I start cutting into the limes and even before I'm next, you can smell them.  That's how pungent they are.  And as I continue to cut them into quarters, the juice that just drips all over the place and I'm making  a huge mess.  And so I bring one over to you.  And I want you to imagine grabbing this big, juicy lime for me that I'm handing you right now.  And I want you to take the lime and I want you to put it in your mouth and take a big bite.  And feel the juices squirting into your mouth.  Now, ask yourself, do you feel anything funny in your mouth?  Is your tongue tingling?  Are you producing saliva?  Now it is happening and the reason why it's happening is because your mind doesn't know the difference,  it doesn't know that you're not eating alive because you're thinking about eating alive.  It's actually preparing your body, your mouth, your tongue, your digestive juices to break down the  acid in that lime.  And so just by thinking about eating alive, your body is responding.  So I hope that that gives you an illustration of how powerful your mind truly is in creating reactions,  both in your emotions and in your body.