= Jonathan Levi pdf
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

=== Section 1: Introduction and Setting Yourself Up For Success

* http://www.keytostudy.com/practice-smart-suffer-headaches/

Practice smart or suffer headaches
Some of our students occasionally report headaches. There are many sorts of headaches, but they  have one thing in common: wrong technique.

There are many common ideas between going to gym and training your brain. Just like bad practice in gym can cause back aches and orthopaedic damage, bad practice with your brain can cause head aches or eyes strain etc.

The first thing you should do when training your brain, is *resting regularly*. Adopt 5 min of rest for every 15 min of work or similar tactics. When resting, close your eyes or look at far landscape. Do not brain-train for more than 2 hours straight, even if you do take the short breaks. Coffee helps, as long as you do not drink too much of it. Make sure you drink a lot of water

The next thing to watch is *breathing technique*. You brain should get enough oxygen.  Take several long deep breathes before and after each article. See this video for explanation. You may want to practice breathing exercise like pranayama-yoga see this video.  I use my own breathing methodology similar to this article, adapting the specific breathing routine to my current mood. Whatever you choose, it is important to get enough oxygen in your brain.

Just like any other activity, when superlearning you want to have ergonomic posture, healthy diet, good amount of sleep. This is basic. Some people get it, others do not get it. We had no luck teaching people good habits, so we trust your better judgement.

Some of the recommendations are more specific. *When practising visualization always try to make funny stuff.  Creative markers* are refreshing for your brain and willpower. Do not fixate: try to move quickly from one marker to another. Make the markers highly active in space: they may rotate, get smaller and larger, morph, collide, and do things that cartoon characters do.

By far the most challenging practice is the saccade reading.   If your eyes hurt you are doing something wrong. Stop immediately, close your eyes and think how you can improve your practice.  The eye muscles are very similar to other muscles in your body: what is hard now may be easy in a  couple of days. The saccade reading assumes eye “jumping” in a controlled fashion with a small overlap on horizontal field of view between jumps. Before you are ready to jump, move continuously. Only when the continuous movement gets too slow for you start jumping.  At the beginning the control is not that good, and your eyes may point to places in the line you did not intend to look at. Do not worry and do not try to force your eyes to move “just right”. They will adapt themselves. Do not fixate too long at any point in space, allow your eyes to move. And make sure to pause between paragraphs.

Proper brain training is like magic and may transform a healthy brain into a super-power, may heal an injured brain and may eliminate boredom.  Bad practice causes headaches. So do practice smartly  and be mindful of your body.