= Jonathan Levi Summary
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

== Become a SuperLearner 2: Learn Speed Reading & Boost Memory - Jonathan Levi

=== Section 1: Introduction and Setting Yourself Up For Success

*About Us: How This Course Came To Be*

Either way, you're here because you wanna learn faster, remember more, and unlock the vast potential of your mind.

He told me that, no, actually, the speed in which he was scrolling down the page was actually the speed of him reading.

I have to say this with no exaggeration, that course changed my life. When I went off to a condensed one year MBA, those skills saved me so much time and allowed me to keep up with the near-superhuman workload assigned by my professors.

The biggest one is, can anyone do this? And the answer is yes, you can do this, but only with the proper instruction,

We're going to teach you a new way to create and store memories, how to triple your reading speed, and we're going to give you the tools to do rigorous at-home training. It's not going to be easy. Becoming a super learner is about much, much more than some of the traditional speed reading programmes out there. It's a comprehensive shift in the way that you learn. This means that we're going to have to retool the way you learn and remember new information first and foremost. What I'm trying to say is this. You're going to have to work for this, and it's not going to happen overnight. But, with the lectures and the worksheets and exercises we've provided, you can and you will succeed.

*Downloading The Course Resources & How To Succeed*

the PDF syllabus. In this all-in-one document, you’ll find a week-by-week guide explaining your weekly goals and expected milestones, as well as convenient and easy-to-use links to each and every one of the resources, games, worksheets, and supplemental materials.

You’ll notice that we ask you to #set aside five to six sessions of about 40 minutes in length every week#. Sure, you can commit less time and still dramatically improve your skills, but this is the amount that we recommend for students who really want to succeed - and that includes you - doesn’t it?

and so we want you to limit your practice and studying to no more than 8 hours per week, to prevent fatigue, burnout, and frustration, and also to allow your brain the necessary time to adapt and build the new connections and habits we’re going to be studying.

*Progressive Overload & What To Do If You Get Frustrate*

Throughout the course, we're going to be using a training methodology called progressive overload, progressive overload is a fundamental principle at the core of all strength and fitness training, and it's applicable to your mental skills as well. The basic idea is to always be training near or just below your limits. You always lift weights that are relatively heavy or run at a pace that is relatively challenging, by doing this, you avoid the injury and the damage and the frustration that could result in training beyond your limits. But you also avoid getting stuck in a rut by not pushing yourself enough. Most importantly, every time you progress, you immediately increase the level of intensity to maintain your progress.

The truth is that some frustration and struggle is unavoidable, but this actually works in our favor. As my friend Peter S. Brown, author of the book Make It Stick, The Science of Successful Learning, says when learning comes easily, it doesn't stick.

The next thing we want you to do to avoid frustration is to check out the articles in the PDF syllabus. One is about something called the *Pomodoro technique*, which is a method used to prevent fatigue and frustration. Basically, you'll train for twenty to twenty five minutes and then take a five minute break and then train for another twenty to twenty five minutes and then take another five minute break after four pomodoro or twenty to twenty five minute periods, you'll take a longer break, a 15 to 30 minutes. This method has been proven to be one of the most effective ways to maintain focus and creativity. So check it out.

Any time you feel frustrated, check out one of these supplementary materials and you'll be completely inspired. They'll also remind you that you can do this with a little hard work and the proper techniques.

=== Section 2: Understanding Your Memory (So You Can Improve it!)

*Why We Need To Improve Our Memory First*

If we take this metaphor for our learning process, it's easy to understand why we have to first upgrade the bucket and then the funnel before we finally upgrade the hose. #You see, the hose itself represents your input speed or your reading speed, whereas the funnel represents the combination of two different types of memory, your working memory and your short term memory#. You may have heard the term #working memory# before, since people often incorrectly use it as interchangeable with #short term memory#. It's best to explain the difference clearly though. Working memory is the type of very short term memory that allows you to remember what I said at the beginning of this sentence so that you could connect it all together and understand the complete idea and then analyse it at the end of the sentence.

Like the name suggests, working memory is really for working with and understanding new information in real-time. It's actually a lot less about memory than about understanding and analysis. One last point on working memory. Our brains do use several different types of buffers to work with the various types of information. This basically means that words, ideas, images, and scenes, they don't all use the same path to get to the short term memory,

Well, once you've used your working memory to process, understand, and interact with a piece of information, your short term memory is what keeps it in your mind for about 15 to 20 seconds. This might seem like a really short amount of time, and it is, that's why for the majority of the course, we're going to focus on improving the connexion all the way from your working memory to your long term memory. This is because if you do a good enough job creating those short term memories that'll stick till you get to the end of a page or an article, you'll only need to use some simple review techniques and regular maintenance to keep things in your long term memory, where we eventually want all our new information to remain.

This means that right now, our working and short term memory are the primary bottlenecks. Without the right infrastructure and base skillset to improve these two types of memory, speed reading is pretty useless, even impossible.

But comprehension and retention or actually understanding and remembering what you read are the major challenges to speed reading that most people fail to overcome. Don't believe me? No problem. Let's read an article together at my average speed.

To put it bluntly, this is why we need to upgrade your memory first and foremost. Unfortunately, academic institutions don't teach sophisticated memory or learning techniques. We're expected to just remember things without ever being taught the proper skills to store a large number of effective, high-quality memories fast.

*How We Store Information: A Very Brief Explanation*

Personally I believe that it's easier to use a technique if you understand how it works. This is why whenever I teach someone to drive a manual car, I always make sure that they understand what's happening when you move the gear shift and what the clutch actually does. And so while I'm certainly not a cognitive scientist, I want to give you a very basic explanation of how your memory works. This is important because it'll help you understand why we do some of the strange things that we're going to do throughout this course. It's all linked to the actual inner workings of your mind and it's all based on neuroscientific research.

*So first and foremost, let me say that your mind is made up of about 100 billion tiny little cells called neurons. These are basically electrically excitable cells that process and transmit information using electrochemical signals. These signals are a lot like the electrical signals firing between different parts of your computer except in your brain there are no wires. Instead, we have synapses, and those are specialised connexions between the neurons*. I don't want to get too technical here because this is stuff is definitely over my head, and in fact the way our memory works is not yet fully understood even by leading cognitive scientists. *But basically memories are created when your brain sends neurotransmitter signals to two neurons at the same time. This strengthens the connexion between those two neurons and presto, you have a new memory. This is an important point to make because it shows that the creation of memories requires connexion between two neurons or a connexion to existing neurons in your brain. The other thing you need to know is that when this happens over and over again the cluster of neurons and their synaptic connexions become something called a neural network. From artificial intelligence research we know that neurons work better in these types of clusters. This means that when several neurons fire together the signal is actually amplified. That's why it's so crucial to store memories in several connected neurons and to further connect them to the memories that we often use*.

Now this is where it gets really important. Your brain has these two incredibly powerful parts called hippocampi, interestingly named for the fact that they look like little sea horses. You have one hippocampus for each hemisphere that, among other things, regulates how memories are created. As far as we're concerned, the most important function of these hippocampi is to determine what's worth remembering. There are a lot of criteria here including novelty, but perhaps one of the most important criteria for the hippocampi is to determine that something is relevant based on existing memories in our brains. *The net effect of this as we hinted before is that the more connexions there are to a piece of information, the more likely your hippocampi are to determine that it's worth storing.* But what about forgetting things over time? Well, our brains have a capacity of about 2.5 petabytes. That's plenty of room for all the things we want to super learn, so why does it seem like we're constantly forgetting things? As researchers have recently found, our brains actively forget memories in order to remain efficient and healthy. *Our brains know they're only two percent of our body mass, take up 20% of our energy consumption, so keeping them efficient is a huge evolutionary advantage for our bodies*. In fact, forgetting irrelevant information is so important that there are numerous mechanisms in the brain used to forget things based on whether it determines it should be forgotten because of trauma or just because it's not useful. In some of these processes the hippocampi are at play again and they're always searching for relevance and applicability. At the end of the day, this means that having many connexions to our memories has another massive benefit. It makes it less likely for them to be removed or to fade away. To give you a metaphor of this, I want you to imagine two roads, one is a six lane highway connecting eight medium-sized towns and another one is a country road connected one house to another. Now imagine that the state budget only has room to repair and maintain some of these roads, not all of them. Which road is more likely to receive regular maintenance and improvements? Which is more likely to be neglected and erode away? This for example is why you rarely forget information like your childhood address even if you haven't used it for years and years. Because there are so many connexions and stories and experiences around that piece of information your brain determines that it's critical and will never erode it away. Knowing this can benefit us tremendously. *The process of super learning necessitates that we create more connexions to the information we want to learn*. This way the mind is forced to remember it like we would remember everyday information that we use. Think about how children learn. For example, they pick up a spoon and they play with it time and time again. They eat with it, they drop it on the floor, all the while they're building connexions and an understanding and a history around that spoon, what it does and how it feels. Finally they learn to remember a sound, a name for it, spoon. This is also why writing things down or any type of pneumonic, even the basic ones, is a useful tactic for learning. You see, you're simply creating new memories in the form of stories or sentences and tying new information like the order of operations First, outer, inner, last in mathematics, to a word that you already know, FOIL. But what about in the adult brain? Of course, there are different requirements for adults to learn than for children, right? Well first and foremost I want to dispel the myth that children's brains are somehow better at absorbing new information or that they have a higher neuroplasticity.

*Recent studies have actually shown that this is simply not true. The reason that children seem to learn with more ease is that they're learning literally every waking hour and all information is new and exciting information for them. Furthermore, research shows that our brains do play by the use it or lose it rule. Most adults lose the ability to learn rapidly simply because they settle into their day-job and they stop learning in the volume that they used to as children, not because their brain chemistry or neuroplasticity have actually changed*. With that said, there are definitely some requirements that are unique to adult learners. In fact, in the 1950s one of the leading researchers in adult education, Malcolm Knowles published a book around the five requirements for adult learning. Now that we understand how the brain works a little bit, I don't think any of them will surprise you. T

here are *number one*: self-concept. Adults are self-directed and independent. They need to take an active role in creating their learning experience.

*Number two*: the role of experience. Adults have a growing reservoir of experience including mistakes that is a critical resource for their learning.

*Number three*: readiness to learn. Adults are most ready to learn things that are pertinent to their daily life situations.

*Number four*: orientation to learning. Adults respond best to learning that will be immediately applicable. Adults are more problem-centered than subject-centered in their learning.

*Number five*: motivation to learn. For adults, the motivation to learn is internal. This means that they must know why they need to learn this new information. So do you understand why we've done some of the things we've done in the last few lectures? Explaining why you need to know things, making you set your own goals and schedule your own learning sessions. In general you can leave it up to us as your instructors to make sure that this course follows along with all five requirements for adult andragogy as well as to conform to the formula that best suits your very picky hippocampi. But as we said before we can go far beyond this, beyond just setting up the materials in a way that's interesting to you and your brain. We can actually build synaptic connexions and memories in a much more efficient and rich way. And that is what we're gonna be learning in the next lectures, but first make sure to check out the PDF syllabus because there's a good amount of homework and a tonne of optional reading materials on everything we've learned in this lecture.


*The Importance Of Combining Games With Real Life Application*

the PDF syllabus or in the daily training log.

To sum it up: Do the exercises, but please, make time every day to apply these techniques to something besides the games in the upcoming sections. Really, because until you actually try to use these techniques for the areas of life that you need them the most, you simply won't figure out how to best adapt, apply, and enhance them to meet your specific goals. So, as you go along throughout the rest of the course, I want you to remember that the games are important, but that the real test of your super-learner skills is whether or not you can memorise everyday information, speed-read your daily reading assignments, and learn actual skills faster.

*Chunking: Navigating The Brain’s Natural Limitations*

Soon we're going to learn how to "trick" the *hippocampi* into viewing things we want to learn as novel, exciting, relevant, and totally worth storing in our short term and longterm memory. However, before we get there, we need to focus on the working memory, that funnel that we were talking about earlier. This is pretty exciting because we can actually start to see some huge gains to our memory capacity very quickly by understanding how to take advantage of our working memory properly. Have you ever wondered why in every country in the world phone numbers are broken up into three to four digit clusters? Or why your credit card number has those spaces between the numbers? *This phenomena is intentional and it's because of a powerful little brain hack called chunking*. You see, for most people, the working and short term memory can only remember sequences of seven plus or minus two pieces of information. Meaning that three to four pieces of information is easy for just about everyone. That might not seem like a lot, but remember that *your short term memory is, like we said, just a temporary stage that information passes through for about ten to fifteen seconds before going into longterm memory, assuming that the hippocampus deems it's worthy*. It's also worth noting that some people can remember larger chunks of information. If you're curious, you can try to remember chunks of up to seven, eight, or even ten numbers to see where you get stuck. From there, you know how small of chunks you need to break things into. *The chunking system is very good because it's an entry level mnemonic technique. It's not only much faster and easier to learn and play with than some of the heavier visual memory techniques we're going to learn later, but it's also a critical element of the overall technique. This is to say that even after we teach you the methods to remember things way more easily, you're still going to be chunking details or memories into groups of three or four so that they can better comply with the requirements of your short term memory. Sure, we could train your short term memory to hold a larger number of items, but that would only slow you down and place a larger cognitive load on you. At three to five items there is no slow down so it's preferable to work in this range. Furthermore, by chunking groups of items into one entity, we can stack five chunks of five objects each into our working memory and effectively store 25 items in our short term or working memory without any cognitive overload. Because of this massive advantage, you'll notice that all of the world's top memory athletes use systems that are based on chunking combined with powerful visual and spatial memory techniques that we'll be learning later on in the course. The other nice thing about chunking is that it works with just about everything. Take a sequence of numbers or a couple pieces of information. For example, brown dog, tall fence, lost Frisbee. You can even try to chunk information about people into neat little bundles. It might seem strange, but remembering that information in chunks is actually much easier than if it were to be put all together*. The brown dog who saw the tall fence where the Frisbee was lost. Chunking is a well documented psychological phenomenon and we've provided some further reading on it in the PDF syllabus in case you're interested. In the next lecture, we're going to give you a worksheet to show you the power of chunking and to practise this foundational skill a little bit. While we haven't gotten to the really incredible memory techniques yet, you'll already start seeing some improvements if you start breaking information into chunks and this skill is going to come in handy later

*Demonstration: Chunking*

Chunking, and that's because students often misconceive it as a technique when in fact, what Chunking is is kind of a psychological phenomenon.

you're going to be learning about markers, visual markers, and you're going to be learning about compound markers and combining chunking multiple details

But the point is for you to understand this is where chunking shines is instead of creating one visualization for each word, you're going to do the same thing that world memory champions and memory athletes do, which is chunk things together.

I might pick some different chunks here, but by condensing and memorizing three to four things at once, think of it kind of like compression. I need one visualization and I've chunked four to five different words or pieces of information into that visualization.

*Dual Coding & ‘Brute Force’ Learning*

By now, you understand a lot about how the different types of memory work and what's required for adults to learn new information. Maybe you've even started thinking about ways to adhere to these protocols and ways that you could change your learning process to maximise your success. One such strategy is an important practise called dual coding. Remember how we learned that the brain has different buffers for working memory depending on the type of information it's interacting with? Well, in dual coding, we try to get different types of working memory buffers to activate at once, thereby increasing the chances of retention and storage in long-term memory. In the coming lectures, we are going to emphasise how important it is to look at a text or a piece of information from different angles, to ask different types of questions and to use different senses, such as vision and smell, or even emotion, to engage with the material in different ways than you normally would. And this is why. This is also why we advocate a style of learning that I like to call "brute force" learning. This is a term that has been lifted from hacking, where a hacker will attack a server by trying thousands or even tens of thousands of passwords in the same form rapidly, often with a few different machines or different angles. What does this have to do with learning though? Well, as we've just established, the most successful learners attack a piece of material from many angles and perspectives. They read about it, they check out contrasting opinions about it from different sources, they jot down some notes, they teach a few friends about it, they try it out themselves, they look at pictures, you get the idea. All of these different approaches and methods reinforce the learning, connecting it to other types of memory, such as experiential memories, and overall they strengthen the neural network associated with what you are trying to learn. My point is that if you want to learn effectively, at some point you'll need to get your nose out of the book and engage with the material in different ways, from different angles that appeal to you, and apply to the material at hand. A great example of this, by the way, would be to try and explain to some of your friends what you learned in the last few lectures about your memory and about chunking. By teaching this information, you force your brain to look at it from a different angle, to deconstruct it, to form it into your own words, and then to present it in a compelling way. As they say, something once taught is something twice learned, and we would absolutely love to see you get out there and share what you've learned with your friends so far. Since you, as an adult learner, need to be self-directed and make decisions about your experience in order to learn effectively, we leave a lot of the stuff up to you. Though, in the coming chapters, we will give you lots of different exercises to choose from and ensure that your learning is very multidimensional.

=== Section 3: The Incredible Power Of Visual Memory

*Why Images Are The Most Powerful Way To Remember & Learn*

Well, it means that we can not only spot an approaching predator very quickly, we can also remember visual information, or pictures, far faster and with more clarity than we can remember things like spoken words.

It also has to do with the fact that pictures are more heavily encoded and they speak to different types of working memory buffers, as we mentioned before. Pictures are imbued with rich and detailed information, such as colour, context, shape, and size, and they're more likely to have a higher number of neural connexions, as they convey emotion and depth, interaction, and so much more. As they say, a picture is worth a thousand words. Visual information is also alarmingly fast. Research has demonstrated that we can comprehend the contents of an image in just a fraction of a second.

This little demonstration shows us just how effective it is to see things as pictures and symbols rather than auditory information. For this reason, in addition to all the other steps we have to take to prime our memory, it's best that we also learn to transform concepts, ideas, and other important information into imagined visual pictures, or what we call markers, as soon as we possibly can. It won't surprise you to learn, additionally, that the best and most memorable types of visual markers are strange, bizarre, or emotionally connected to memories. After all, adult learners need to connect information to pre-existing knowledge, and as always, our hippocampi are busy working away to determine what stuff matters and what stuff doesn't.

However, the detailed, experiential images, the emotionally significant experience of interacting with a dead body, and the very concrete, minute details are what allowed her to memorise the ligaments much better than the bones.

*When & Why Creativity Training May Be Necessary*

In the last lecture, we told you that one of the goals of SuperLearning is to transform any and every piece of information you want to remember into an image, which we call, a marker.

It's called The Multiple Uses Test and it goes like this. Grab the nearest object to you, perhaps it's a pen, perhaps it's a keyboard, perhaps it's a sheet of paper, it doesn't really matter. Now, write out as many uses as you can think of for that object. Chances are, if you're about average, you can think of around 20 uses and even if you generate 20, you'll probably find that they fall into about seven plus or minus two chunks of similar uses or things that are really close to one another.

But, you can go much further, thinking about things that are completely unrelated to the object, things you may like or dislike.

*What Types Of Images Come Naturally To You?*

As you know doubt remember, connecting new information to existing, strong and inter-connected neural networks is probably the best way to guarantee that the hippocampi will start paying attention.

Ultimately, you have to learn to go with what images come naturally for you. Try to lean towards whatever type of image you find most conductive for you to remember, but just make sure that, number one, there's as much detail as possible

With time, you too will build up a visual library like this one, which will make calling up images much faster and make it much easier to link together strings of images to form complex concepts that easily convert into long term memory.

=== Section 4: Mental Markers: Visual Memory Meets Learning

*How Do We Apply Visual Memory To Reading?*

Since so much of what we learn today comes from books and other forms of written materials, you're probably wondering how we're going to apply the visual memory techniques we've been learning to reading. This is a great question, and it's one of the biggest areas of confusion for most students. After all, it's extremely difficult, maybe even impossible, to generate visual markers while your brain's visual processing power is focused on reading and looking at the symbols on the page. This lecture will explain how it all works. If it's confusing at first, don't worry, because there are plenty of demonstrations and additional lectures on this process coming up soon. *One of those future lectures will come up when we get to speed reading, and it'll explain in detail how you'll use regular intervals of pauses during your reading. This is not just because speed reading is very exhausting for the eyes and for the brain, but also because these pauses allow us to optimise the process of learning*. Think of this as a sort of Adam Smith division of labour type thing, if you've studied economics, or if you've read Tim Ferriss' work, it's what he calls batching like tasks. It's a very well known productivity and efficiency trick, used in factories and companies all over the world, and we're just applying it to reading. *You see, just like there are at least three types of memory, there are also three stages, or processes, of memory. They are, encoding, storage, and retrieval. Where most people get into trouble is that they try to do all three at once. Have you ever read a paragraph or a page of text only to realise that you've been deeply immersed in thought and you haven't actually paid attention to anything that you just read? This is what happens when you're trying to do all three memory processes at once. On the other hand, if you've ever studied process operations management or economics, you know that grouping similar tasks together is an efficient way to minimise waste. I mean, you don't wash one shirt at a time and then put it in the dryer all by itself. You wash all of your clothes together, put them all in the dryer together, and then fold them when they're all done, right? With reading, you've been doing it one shirt at a time, trying to multitask the washing and drying and folding for each shirt. It's just as inefficient as it sounds, and so we're going to separate it out into three separate processes to reduce cognitive strain and improve overall efficiency*.

*Now I know what you're thinking, how exactly do we do that? Well, because of the limitations on your short term memory and the inherent difficulty in multitasking visualisation with reading, we'll be learning how to make short pauses of about one to two seconds after each page, or even take micro pauses of just fractions of a second after reading information-dense paragraphs. You'll also take longer pauses every 10 minutes or less to review what you've already hopefully put into the beginning stages of long term memory. As we're going to discover, when we learn about space repetition software, you brain needs to periodically repeat and review information in increasingly long intervals in order to remember it and prove to the hippocampi that it's relevant and worth remembering. This is similar to the idea that you must continue weight training to improve your strength and increase muscle mass. If your brain, like your body, thinks that the information you're using is a one off occurrence, it won't waste the time investing the resources to remember it*.

*In short, this is why we take small pauses after each page and much longer pauses of 15 to 30 seconds after each chapter, to play back and retrieve our stored markers and perform a form of spaced repetition to improve our long term retention. This also means that it's not a bad idea to spend a few minutes a week reviewing markers and ideas from books you've read months or even years before, if you really wish to remember them*.

Don't worry, we're gonna go into a procedure and a habit for all that stuff later on in the course. But for now, you need only to be aware of this process and how it works. Before we can get into any of this, we need to master the concept of markers, or the quick visual associations that we've been learning about up until now. *While we're discussing images and visual markers, it's worth noting that not all markers have to be visual. In fact, smell is actually a more memorable sense than vision. Of course, we can't understand an entire book using our sense of smell alone, and so we're focusing on images, but if you read about, say, chocolate, and you can conjure up the smell or the taste of chocolate, that's actually a great marker for remembering that data point. And if it works for you, even better. Whatever types of markers we use, whether they're visual or sensory or some other types that we have yet to learn about, it'll almost certainly be a mix in the end. This mix of markers, when retrieved and reviewed, reminds us of the details that we've decided we need to remember. And when combined with our existing knowledge and opinions and ideas about the content, it allows us to dual code and store information into long term memory very quickly and very effectively*.

*So, instead of reading back over the chapter, we can retrieve all of the markers we've created and start thinking about how they're connected together logically. We play them back almost like a film strip in our minds, and that helps our retrieval*. It also, as an added benefit, serves as little landmarks throughout the page, which if we need an extraordinarily detailed level of information, like exact dates, we can actually go back because we have our landmarks of markers and they tell us exactly where we need to find that information. In time, we'll be learning to sight read, which will take visual information in the form of words and symbols and convert them much more quickly and efficiently into sets of markers that relate to one another and form a cohesive picture. We're getting there, but for now just be patient, and keep working hard on your foundational memory skills like markers and chunking.

---

*Demonstration: Visualization Of Words And Concepts From Text*

---

*Creating Effective Markers For Better Memory*

*So what makes a good, high quality, memorable marker that can be easily linked and stored in our long term memory?*

*first and foremost, markers represent a concept or an idea, not a generic fluffy concept idea, but rather a very specific picture that articulates a concrete concept, one that can be easily retrieved from memory*.

*The next important criteria is that our markers are imbued with rich details*.

*However, even if descriptive details are not given, you should create your own because this mental process will make the images much more memorable.*

*So when I say that I'm picturing a very detailed image, it doesn't actually mean that it should take any longer. It just means I'm making sure that the images that pop up have a level of detail. That means that they are either specific images from memory or images that we can describe with a high level of vivid detail. The third important criteria of each marker is that it can be easily connected to other markers that come with it.*

*But for now, it's important that you understand that by using these highly detailed markers, we are able to remember more details with fewer memory points, a sort of chunking or compression of memory information, because each detail encodes some information*.

*This leads me to the fourth critical aspect of a good marker, and it probably won't come as any surprise. Good markers can be easily and quickly converted to images*.

*The fifth important point to consider when creating markers is the differentiation between problems and solutions*. If the paragraph you're reading presents both a problem and a solution or a conflict and a resolution, it's always better to prioritize the solution or resolution, not the question.

*The sixth and last element of a good marker is that it connects to existing knowledge whenever possible*

*In a sense, you want to create markers for one hundred percent of important details so that if and when your brain forgets the 80 percent of details that are mere set up an explanation, you will still have markers for the 20 percent or less of details that are crucial for understanding. This 20 percent will become your anchor for remembering the overall thoughts and ideas in the books and articles you read. And so you want to make sure they are high quality*.

*First and foremost*, high quality markers represent specific ideas or concepts that can be easily understood.

*Next*, high quality markers are themselves imbued with rich detail such as colors, textures and so on.

*Third*, high quality markers are clearly and logically interconnected to one another.

*Fourth*, high quality markers emphasize outcomes or resolutions, not questions or initial conflicts

*Fifth* high quality markers come in volume. At this stage, the more the merrier.

And *finally*, markers draw upon existing memories whenever possible. Great.

*There is no such thing as the perfect marker for you is the marker that's going to be easy to create and easy to remember. Simply transitioning your learning and memory process from a strictly auditory to a visual one is going to give you a quantum leap in how well you're able to memorize the things you learn*.

---

