= Template
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== Course Name

*Maximizing Value*

* [ ] *Fundamentals*: Learn the concepts
* [ ] *Information*: Do POC from the course
* [ ] *Skills*: Use / Implement it in Project
* [ ] *Innovation / Expert*: Value for next 2 Years


*Objective*

* [ ] *History*:
* [ ] *Agenda-While doing this course what is the Agenda [1,2,3,4,5..]*:
* [ ] Exam Notes
* [ ] *Why OneNote Notes*:
* [ ] *What is Pending*:

=== Section 1

*The Soft Tech Savvy Way to Always Be Essential*

You want to be that person when there's a new promotion open, you're the first person considered for  that.  You want to be the last person any boss considers.  When the boss is told we have to fire 20 percent, get rid of the least productive people, you don't  want to be on that list. *That's what having strong soft skills is all about.  It's about protecting yourself and really making yourself indispensable for any organization and for  any industry and for any career*.  You don't remember all 11 skills, but think of it this way.  If you have a colleague who has to travel across the country three days a business trip, how do you  get to be that person that is indispensable for this trip?  How do you get your colleague to say, oh, yeah, we need that person with us for a variety of reasons,  not just because you're fun or likeable, but because you're absolutely indispensable.  That's what this course is all about.  And I want to start off an area that may surprise you.  I want to talk about technology skills now.  I don't mean computer programming and learning C++ or HTML.  I'm assuming that even if you have those skills, that's not why you're in this course.  These are the soft skills that things that don't show up on the resume where you would put computer  skills.  *But when I say technology skills, I mean simply being more patient and being better able to use the  technology in your office, in your industry*.  Here's a simple fact.  If you're the only person who knows the password into your office database, you'll never be fired.  You're simply seen as too indispensable.  If you are the only person who knows how to get into the Twitter account for the office and there's  a crisis, you're going to be seen as indispensable.  So what I mean by technology is simply learning the basics and not being the last person to the party.  Unless you're really we all know people who had to be pulled into using Facebook.  Oh, I don't want to mess with that.  I don't have time for that.  And of course, they all eventually got on Facebook or Twitter.  Some of you may be old enough to remember those who refused to use texting or even email.  Don't be the last person to use communication technology.  Be the first person.  Be the person in your office, in your organization who knows how to help other people do that.  Think of it this way.  One hundred years ago, someone showed you a toaster.  You look at what is that?  I don't know how to use this technology.  This is crazy.  Where is the electricity?  But now if someone hands you a toaster, you know what to do.  You don't think of it as, oh, I'm now using the toaster technology.  Let me plug it in.  Let me know.  You just toast your bread.  To you, it's not technology, it's just a toaster.  Well, increasingly, with so many technology tools used in a career in an office, whether it's Facebook,  whether it's Twitter, whether it's the database, whether it's auto responders for people who use it  every day.  It's just Facebook, it's just Twitter, it's not fancy technology, you need to really be on top of  that I had of everyone else.  And guess what?  It doesn't require a computer science degree.  Quite often.  It just requires a little patience.  It requires going to a frequently asked questions.  Section one young man I hired many years ago right out of college, he had no computer skills other  than he used email and a word processor to write term papers.  But what he had was patience.  So every single time we got new software for shooting videos or recording or editing, he was the person  when I said, how do we do this?  He said, I don't know, but I'll find out.  What did he do?  Did he go to community college and study computer science programs 12 hours a day?  No, he simply went to the website, read frequently, asked questions section, and he had the discipline  and the patience to call an 800 number for help.  These days, when it comes to most technology that you're going to need in your office, in your career,  unless you're a computer programmer, it's not about knowing complicated technology.  It's not about knowing complicated computer science programs are wildly sophisticated databases.  It's just about patients unwillingness to learn, willingness to call an eight hundred number, occasionally  a willingness to go to a frequently asked question section.  So this is an incredibly important skill.  Too many people have the idea.  Well, I'm not a technology person.  I'll tell you what.  A lot of bosses here, when you say I'm not a technology person, what they really hear is I'm lazy.  I don't want to learn.  I want to be able to sit back and let someone else handle my problems.  That's not impressive to anybody.  Now, the boss may be the same, but I'm the same way.  Sometimes I get lazy.  But if you want to focus on helping your career, you've got to cut through that.  You've got to really get to the point where you might not be the earliest adapter with new technology,  but you are going to be earlier than other people in your office, other people then or already in your  industry.  That's the way you stay ahead.  So here's the exercise for you right now.  I want you to look at some aspect of technology.  You already know it could be how to create a Facebook group page.  Nothing very hard, but something you think might be of interest, other people in your office and then  just let them know Friday at lunchtime, you're going to be giving a little demonstration for fifteen  minutes.  It could be in the office lunchroom.  It could be at your desk.  You'll take questions because if you pick the right topic, there will be people who are more senior  to you, your boss, your boss's boss, other people within your organization who want to learn this  as well.  And they don't have the patience to go to our website or call an eight hundred number.  This way you start to show you are technologically savvy, you're not the technologist, you're not  the IT department, but you're someone who is a little quicker, a little faster at learning things.  So it could be had to put up a Facebook page.  It could be how to do a simple Facebook live video, something I teach people.  It doesn't matter what it is, as long as it's using technology, some light and you're comfortable  using it and you can show others do that.  And that's a soft skill that's going to help you for the rest of your career.

*Not My Job and I am Happy to do it*

Hey, that's not my job.  Not my problem, not in my job description.  Those words in the modern era are career kiss of death.  You have to realize you have one job.  Your one job is to please your boss.  And related to that, please customers, please clients.  Now, I'm not asking you to do anything illegal or immoral.  And if you think you're in an oppressive situation, that's a whole different issue for a different  course.  I'm assuming that you have a perfectly fine relationship with your boss and you want to make it even  better.  Well, one way of doing that is by constantly exuding the attitude that this is my job.  Anything you want to throw at me is my job.  When you look at so many people who have become wildly successful, talk to anyone who worked with them  earlier in their career, certainly.  And their attitude is always the same.  I'll do anything, anything I can do to learn anything I can do to help the organization.  If you look at any of the top network news anchors, major TV networks around the world, the people  who are the primetime network anchors so often when they were twenty three, twenty four or just starting  off in their news network, their bosses will tell you the attitude was always the same.  I'll do any story, I'll go anywhere.  I'll hop a plane to the most remote part of the world with two minutes notice.  That is their attitude.  Certainly you can be hired for one position and be given a task that you think is way beneath your dignity,  way beneath your educational credentials and background.  And legally, you may have a point.  But do you want to fight legalities, do you want to be litigating your career?  That's typically a surefire path to career death.  Now, I'm not suggesting you should you have to go to the boss's home and on your own free time, cook  and clean the boss's house.  I'm not suggesting anything like that.  But when it comes to any organization, any industry, any office, there's always a lot of things that  are not technically in anybody's job description.  *And if you can fill the void, that's a way for you to provide more value, meet more people and really  display the fact that you have certain competencies*.  Could be starting a trade organization that no one thought up.  It could be just as simple as putting a label on the trashcans, which one is for recycling in which  one is for trash if you really keep your eyes open.  For things that need to be done to advance the organization, going can be a million things that are  not officially your description.  Now this relates to the first soft skill we mentioned a moment ago on technology, simply learning the  technology, being comfortable with the databases, being comfortable with new social media, whether  it's Facebook Live or whatever, is relevant to your career.  It's certain related to that, but it's related to everything that goes on in your office, in your  organization, because no organization is so big and has so many people that they have someone with  a title for every single task that needs to be done.  That's why it's critical for you to have an open mind, have your eyes open and always be looking for  things that are important.  But you don't really want to do it and nobody else does, too.  So that's your exercise.  *Look around your office right now, find some task that you know needs to be done that you don't particularly  want to do.  Do it anyway.  You don't have to brag about it forever.  Eventually people will know and you'll develop a reputation as the person who does things, even though  it's not officially their job*.  When you build a reputation as someone who does stuff that isn't just your job, that is career gold  right there.

*Update for Pandemic Times - Soft Skill of Being Able to Work from Home*