= RFP
:toc: left
:toclevels: 5
:sectnums:
:sectnumlevels: 5

NOTE: NOTE

TIP: TIP

IMPORTANT: IMPORTANT

CAUTION: CAUTION

WARNING: WARNING

[cols="1,3"]
|===
| Name | Description

| Asciidoctor
| Awesome way to write documentation

|===

== RFP

=== Section 1: Course Introduction and Overview

* So far, I have not found much take away from this section.

==== Welcome to the class

Hello and welcome to the complete proposal, writing and management course on You to me with APAP Foundation level exam prep. My name is *Tom Moore from Thought Progress* and I'm happy to be your instructor through the length of this course. No matter what brings you here today, I want to assure you that this course has everything you need to be a well-rounded proposal writer or proposal manager. So it might be that you're a business owner and you're interested in maturing your business development process. If so, this course has what you need. Or maybe you're an employee in a larger company and you'd like to have the foundation level certification to prove your abilities as a writer or manager. If so, this course has everything you need. Or it might be that you're just starting out as a small business and you're trying to get your hands on that big government money, if so, this course has everything you need. So I'm happy to have you with me. Please introduce yourself to in the comments below. Just write your name and your goals for why you're taking this course, what you hope to get out of this proposal, writing and management course. And I look forward to answering any questions you have as we move along in the course. Let's get started.

==== Instructor Introduction

Before we dive into the course content, I wanted to take this opportunity to tell you a little bit more about myself and also my experience as a proposal writer and proposal manager. So, again, my name is Tom More. I'm a member of the Association of Proposal Management Professionals AP, and I'm also chief proposal strategist at Thought Progress LLC. And my experience comes mainly from the information technology field. I worked with companies of all sizes as they wrote complex solutions to federal agency requests for proposal. So whether it was cybersecurity services, records management, technology solutions or technical training, *I worked with subject matter experts turning their complicated technical information into readable and persuasive text* targeted to federal agency stakeholders and decision makers. So I know the business development process outside and inside from the technical writing level to the client relations level, and I hope to bring some of that experience to this course. So I'll be able to let you know where the pain points are going to be. Roadblocks you're bound to experience as you dip your toes into the waters of proposal writing and proposal management and also some tips and tricks to help you be effective. I'm particularly interested in the psychology of persuasion and influence that can be incorporated in your proposals to increase your probability of win and also set you above your competition. So I'm going to be sharing some of that insight with you also. And I look forward to talking with you in this course. And also, if you have any comments, questions, concerns, please reach out. You have the notes section below. Also the question and answer form. I love to hear from my students. So no matter what your question is, please reach out. I'd be happy to answer and I look forward to being with you through the length of this course.

==== Benefits of APMP Certification

So, as I mentioned, the purpose of this course is to give you everything you need to be an excellent proposal, writer or manager. So this might be for some of you. You're already in the space, you're in business development, and you just want to improve your skills. Or it could be that you're trying to get started. Whatever the case, having a certification on your resume is of immense benefit to you. So in the proposal, writing and management space, there are two main organizations that are respected. *One is APMP Association and proposal management professionals, and also the other is the Shipley Institute. So Shipley has a good reputation in the space*, but APMP is gaining on their heels. It's growing in reputation and also it is particularly respected outside of the United States. So it's an internationally recognized certification. The other thing is it's substantially cheaper to get the AP certification as it is the Shipley's certification. So for something like 400 dollars, 500 dollars, you can get this shiny logo that you see here on the slide on your resume, set yourself apart among proposal writers. So what are the benefits of having this certification? Well, it proves your ability as a proposal writer and manager. So having a certification means that you've been assessed by a third party organization that has standards. You've passed their tests, and it can prove to employers and clients that you really know your stuff. Having a logo like this, you can put it right on your resume. You can put it on your LinkedIn and draw some attention to you and cuts through the clutter and really gives you a competitive advantage. It demonstrates that you are improving your skills. And this is particularly important if you already are employed in a business development team to show your employer that you're actively pursuing certifications, gives them an idea of how serious you are about your career and can gain you some attention, which will help you get a promotion or more responsibility in the organization. So it's really worth the effort and expense for this certification.

And let's talk numbers. Proposal writers, particularly in information technology, make from 60 to 80 thousand dollars a year proposal coordinators. They usually have a little bit more responsibility than a proposal writer. They might work with a team of writers and graphic designers they make from fifty five to eighty thousand a year. And then finally, a proposal manager who is usually like a like a project manager for proposals is very valuable to a company. And they usually make from sixty five to ninety thousand dollars a year or more. And you're very valuable to a big corporation as a proposal manager. Corporation executives are interested in growing their businesses, accessing new funding opportunities. But there's a significant gap in the field for for persuasive writers and technical writers who can turn their dreams into reality by getting that money from the client agencies. So somebody who can take on the responsibility as a proposal manager and fill that gap is very valuable to an organization. So there are some significant benefits to getting the AP certification. If you don't want to get it, that's fine. This course is still going to cover all the basics and make you a great proposal writer. So let's get started.

==== Proposal Writing & Management Course Outline

Let's take a look at the syllabus for the course so you know what is coming up. Feel free to hop around topic materials if you like. If there's something that you want to learn specifically, you can refer to this outline to head to the section that you're interested in. But I strongly encourage you to just work through it point by point and to follow the syllabus as it's presented here so that you can get the full understanding of the information as it's presented. After we do the course introduction, we're going to talk about proposal management as part of a larger business development process. And it's important to understand where you feature in this cog of a larger machine, which is business development, the corporation's efforts to get in front of federal or private clients to convince them to use your company as a provider of solutions. And so you, as a proposal manager, play a part in that larger process. So we'll talk about that in Section three. We're going to talk about being customer focused to get your mind out of your own head and on the customer, allowing you to be persuasive to use marketing techniques and tactics and how to make sure you're always writing in a way that speaks to decision makers. Section four talks about creating proposal documents and deliverables, specific proposal templates, how they're written, how to create an outline, how to incorporate other teams of writers. Section five, the proposal management lifecycle, how to keep the whole process in order. It can be overwhelming for companies when they get a new opportunity. They're excited. They have a lot of professionals on the team, but we do need to be orderly in the way that we approach the process. And that's what we're going to talk about in Section five, Section six plans and tools for proposal development. This is some templates, some outlines. We talk about compliance matrix. We talk about calendars. We talk about writing plans for individual technical writers and proposal writers. All of that is covered in Section six. And finally, Section seven, we'll talk about preparing for the foundation level exam and we will talk about how you can be successful not only in your exam preparation, but also as a proposal writer.

==== APMP Official Resources

So as I mentioned earlier, APMP does provide a lot of great information to help you pass the foundation level exam and also to prepare you to be a proposal rider and a proposal manager. So one of the main features that they offer is membership and membership does cost some money. If you go here to membership and click on APAP membership, you have the opportunity to join as an individual for one hundred sixty dollars a year. Or if you happen to have a student ID with a university email address, you can get it for twenty five dollars a year. And the main feature that you get from paying for that is access to the body of knowledge. So to get to the body of knowledge, if you're a paying member, you just click on this tab and I'll show you mine as a paid member of the organization here. You have access to this body of knowledge. This is all the information that you're going to need for the exam. In fact, you can even change the view from body of knowledge, be OK to study guide. So if you click on Study Guide, it's arranged differently to help you get through the material for the exam. So all the information's here. It's a great way to study, you know, exactly what you're going to see on the test. And it's an option for you in preparing for the exam as a proposal manager. The tools and templates is an excellent feature of the body of knowledge. The tools and templates actually allow you to download and edit strategy documents, proposal outlines, planning, meeting minutes and outlines. There's an incredible amount of tools here and templates that you get access to. You download them as word files and you can use them in your company. So this alone is worth a membership to have access to those tools and templates. Very valuable stuff. They're going back to preparing for the exam. You have the option again to join membership and have this online edition of The Body of Knowledge. But you can also pay for a PDF version, so. You know, if you choose not to become a member, but you still want to prepare for the exam, you can do so also if you're like me and you need to see things not only in digital form, but also in paper form so you can highlight and write notes and access it away from your computer. This is a great option, too. You can either get a printed copy or you can download it and print for yourself. So there's some cost involved there, but it's a great resource. Again, if you print this out when you take the exam, you'll be able to have it right there with you. You can market and you can flip straight to the page where you know, the information's at. So a great tool there. And also the glossary of terms. This used to be a free document, but now they charge twenty five dollars for it. It's included or it's cheaper if you have a membership. But again, it gives you all the acronyms and definitions that you need to pass the test. So you have a couple options there. Again, you can download the study guide and study from that, or you can become a member and have access to the body of knowledge. And again, if you click at the top here on certifications and then go to foundation level, that's the one that we're preparing for here, you will have access to all the information about the exam and also how to prepare for the exam. So, by all means, please go to APM, pig, peruse the website. Think about becoming a member and having access to the body of knowledge and all those great templates which are going to come in handy for you as not only you pass this exam, but you become a respected proposal writer and proposal manager.

==== Foundation Level Certification Exam Overview

So now that we've talked about how to access all the excellent tools that AP provides, let's talk about the exam itself. Now, this is not an exam that you need to get overly nervous about if you prepare well, if you take this course, if you read through the printed version of the book or the online version, you are going to be well prepared for this test. It's an hour long test. Seventy five questions in total and you only have to get fifty six percent correct. To pass the test and get your certification. So it is also open book, which is a relief. That doesn't mean that you don't have to prepare because since you have a little under a minute for each question, you do need to make sure that you can get through most of them without referring to the book. But it is a relief to know that if you get hung up on any question, you can flag it and you can look at it in your printed version of the book and get the correct answer. And it's also not proctored. So you do have the opportunity even to open another window on your browser, have the online version of the AP Body of Knowledge up, use the search feature and find the answer to any question that you might be struggling with. So no need to worry about this test. Again, it is significantly cheaper than other proposal management and proposal writing certification tests for members of AP. It's only four hundred dollars us. And if you're not a member. Six hundred dollars. So the way that the exam is divided up is into 23 entry level and early career competencies, and these are listed very clearly in the body of knowledge, and they are also notated based on their emphasis on the exam. So some topics have a strong emphasis, which means that they're heavily referenced on the exam, others only medium and some only a moderate emphasis, which means that they're not touched on very often or very heavily on the exam. So when you're preparing for this test and you're preparing your study time, you know which topics to focus on in particular, and you can target your study preparation accordingly. Here are the high emphasis topics taken note of these, you might want to print off this slide or circle the star them in your printed version of the body of knowledge. These are the ones that you're going to get a lot of questions on in the exam. Here's the medium emphasis topics. Not a lot of not too much time, but but you're really going to need to know these ones. And then finally, the moderate emphasis, pricing and data, unsolicited proposals, production management, things like this, less emphasized on the exam. So, again, be familiar with all of this information so you know how to target your study time effectively and be prepared for that exam.

=== Secton 2: Proposal Management: Part of the Business Development Lifecycle

==== Section 2 Overview

Proposal writing and proposal management is part of a larger effort inside any mature company called Business Development, Business development is how leaders of a company try to grow their business, how they try to get more money. So it includes marketing efforts. It includes client relationships, building business relationships with client agencies that will later put out a request for proposal for contracting services. So there's a lot involved here in this overall process and you play a part in it as a proposal, right. Or proposal manager. So in this section, we're going to talk about how to look for opportunities, how to identify markets that you want to target, how to identify accounts or agencies that you want to target, to position yourself so that you can improve your probability of winning when you submit a proposal. Now, as a writer or manager of proposals, this might be above your pay grade. This may not be your responsibility, but you are going to be rubbing shoulders with the business development team. So it's important that you have a thirty thousand foot view of the business development lifecycle so that you can really be a good team player and contribute to the efforts of the company and be indispensable as a proposal writer, as a and as a proposal manager. So in this section, we're going to talk about market ID account strategies and then also the proposal development process.